<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<link rel="alternate" hreflang="de" href="https://oa-datenpraxis.de/rankings.html" />
<link rel="alternate" hreflang="en" href="https://oa-datenpraxis.de/en/rankings.en.html" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Open Access in institutional Rankings – OA Datenpraxis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>
<script src="site_libs/quarto-nav/quarto-nav.js"></script><script src="site_libs/quarto-nav/headroom.min.js"></script><script src="site_libs/clipboard/clipboard.min.js"></script><script src="site_libs/quarto-html/quarto.js" type="module"></script><script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script><script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script><script src="site_libs/quarto-html/popper.min.js"></script><script src="site_libs/quarto-html/tippy.umd.min.js"></script><script src="site_libs/quarto-html/anchor.min.js"></script><link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script><link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f3966d63841dad6a94c94c7fab4e9718.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/iconify-2.1.0/iconify-icon.min.js"></script><script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script><link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="styles.css">
</head>
<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./images/logo_oa_datenpraxis.png" alt="" class="navbar-logo light-content"><img src="./images/logo_oa_datenpraxis.png" alt="" class="navbar-logo dark-content"></a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">OA Datenpraxis</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item"><div class="dropdown" id="languages-links-parent">
<button class="btn btn-primary dropdown-toggle babelquarto-languages-button" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="languages-button"><i class="bi bi-globe2"></i> EN</button><ul class="dropdown-menu" id="languages-links"><li><a class="dropdown-item" href="https://oa-datenpraxis.de/rankings.html" id="language-link-de">DE</a></li></ul>
</div></li>
<li class="nav-item">
    <a class="nav-link" href="./partners.html"> 
<span class="menu-text">Project Partners</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./publications.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-project-plan" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Project Plan</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-project-plan">
<li>
    <a class="dropdown-item" href="./arbeitspakete.html">
 <span class="dropdown-text">Work Packages</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-news" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">News</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-news">
<li>
    <a class="dropdown-item" href="./events.html">
 <span class="dropdown-text">Events</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./archive.html">
 <span class="dropdown-text">Archive</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-oa-dashboards" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">OA Dashboards</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-oa-dashboards">
<li>
    <a class="dropdown-item" href="./dashboard_uebersicht.html">
 <span class="dropdown-text">OA Dashboards Contact</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./dashboards.html">
 <span class="dropdown-text">Open Access Dashboard Collection</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./dashboards_schema.html">
 <span class="dropdown-text">Metadata Scheme</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-notebooks" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Notebooks</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-notebooks">
<li>
    <a class="dropdown-item" href="./OpenAPC.html">
 <span class="dropdown-text">Open Access Cost Monitoring with OpenAPC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./OpenAlex.html">
 <span class="dropdown-text">Open Access Monitoring with OpenAlex</span></a>
  </li>  
    </ul>
</li>
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://openbiblio.social/@oa_datenpraxis" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-mastodon"></i></a>
    <a href="mailto:info.oa-datenpraxis@listserv.dfn.de" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-envelope"></i></a>
    <a href="https://github.com/oa-datenpraxis/oa-datenpraxis.github.io" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-margin-header"><div class="margin-header-item">
<p><a href="../images/logo_oa_datenpraxis.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="../images/logo_oa_datenpraxis.png" class="img-fluid"></a></p>
</div></div>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Open Access in institutional Rankings</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Institutional or university rankings attract a great deal of attention in science policy and the public sphere because they enable scientific institutions to be easily compared with one another on a global level. They serve various interest groups, such as political decision-makers, university managers and prospective students, as a tool for strategic decision-making, illustrating institutional excellence or choosing a place to study <span class="citation" data-cites="Waltman2012">(<a href="#ref-Waltman2012" role="doc-biblioref">Waltman et al., 2012</a>)</span>. The methodologies on which the rankings are based are repeatedly criticised, for example because of their tendency to summarise multiple dimensions of the performance spectrum of scientific institutions into a single, often intransparent score <span class="citation" data-cites="vanRaan2005 Piro2016 Diprose2023">(<a href="#ref-Diprose2023" role="doc-biblioref">Diprose et al., 2023</a>; <a href="#ref-Piro2016" role="doc-biblioref">Piro &amp; Sivertsen, 2016</a>; <a href="#ref-vanRaan2005" role="doc-biblioref">van Raan, 2005</a>)</span>. This approach not only makes it difficult to interpret the rankings, but also fails to take sufficient account of the different tasks and priorities of the institutions <span class="citation" data-cites="Waltman2012 Huang2020">(<a href="#ref-Huang2020" role="doc-biblioref">Huang et al., 2020</a>; <a href="#ref-Waltman2012" role="doc-biblioref">Waltman et al., 2012</a>)</span>.</p>
<p>Five institutional rankings with Open Access as a comparative dimension could be identified: the Leiden Ranking 2024 (LR), the Leiden Ranking Open Edition 2024 (LROE), the SCImago Institutions Ranking 2024 (SIR), the Quacquarelli Symonds World University Rankings: Sustainability 2025 (QS), and the COKI OA Dashboard 2025 (COKI). All five rankings include one or more Open Access indicators and are globally oriented in terms of geographical coverage.</p>
<p>This page provides an overview of the characteristics of the five rankings, as well as an investigation into the extent to which the results of the rankings are comparable. This includes, among other things, a comparison of the data sources and Open Access indicators used by the rankings, as well as a review of the extent to which institutions can participate in the data collection by the ranking providers. The focus is particularly on the Open Access dimension.</p>
<section id="leiden-ranking" class="level3"><h3 class="anchored" data-anchor-id="leiden-ranking">Leiden Ranking</h3>
<p>The Leiden Ranking has been produced annually by the Centre for Science and Technology Studies (CWTS) at Leiden University in the Netherlands since 2007 <span class="citation" data-cites="Waltman2012 LR_updates">(<a href="#ref-LR_updates" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-e</a>; <a href="#ref-Waltman2012" role="doc-biblioref">Waltman et al., 2012</a>)</span>. The ranking does not offer a traditional league table where an overall score is calculated; instead, it provides various bibliometric indicators along the dimensions of <em>scientific impact</em>, <em>collaboration</em>, <em>Open Access</em>, and <em>gender</em>. The indicators are presented in both size-dependent (absolute numbers) and size-independent (relative proportions) forms to account for differences in the size of universities. The ranking also offers trend analyses over time periods and stability intervals to account for statistical uncertainties <span class="citation" data-cites="LR_general LR_method">(<a href="#ref-LR_general" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-c</a>, <a href="#ref-LR_method" role="doc-biblioref">n.d.-a</a>)</span>.</p>
<p>The 2024 version of the Leiden Ranking includes bibliometric data for 1,506 universities worldwide <span class="citation" data-cites="LR_method">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>)</span>. Indicators are provided for four-year time periods, with the 2024 version extending this to the period 2019–2022 <span class="citation" data-cites="LR_method">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>)</span>. The bibliographic data comes from the Web of Science, but only articles and reviews published in international scientific journals are considered <span class="citation" data-cites="LR_method">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>)</span>. The selection of universities is based on their research performance, with a minimum of 800 so-called <em>core publications</em> required for inclusion in the ranking. <em>Core publications</em> are defined as publications in international scientific journals in fields suitable for citation analysis. These publications must be in English, have at least one author, not be retracted, and appear in a <em>core journal</em>. <em>Core journals</em> are characterized by their international orientation and must be situated in a field suitable for citation analysis. The Leiden Ranking does not use data directly from universities <span class="citation" data-cites="LR_method LR_general">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>, <a href="#ref-LR_general" role="doc-biblioref">n.d.-c</a>)</span>.</p>
<p>A key feature of the Leiden Ranking is its focus on Open Access publications. Open Access indicators were added to the ranking beginning with the 2019 version <span class="citation" data-cites="LR_updates">(<a href="#ref-LR_updates" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-e</a>)</span>. To determine the Open Access status of publications, the Leiden Ranking uses OpenAlex as its data source <span class="citation" data-cites="LR_method LR_general">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>, <a href="#ref-LR_general" role="doc-biblioref">n.d.-c</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 2024</p>
<p><strong>Website:</strong> <a href="https://www.leidenranking.com/" class="uri">https://www.leidenranking.com/</a></p>
<p><strong>Creator:</strong> <a href="https://www.universiteitleiden.nl/en/social-behavioural-sciences/cwts">Centre for Science and Technology Studies (CWTS)</a></p>
<p><strong>Ranking Type:</strong> University ranking</p>
<p><strong>Sectors:</strong> Universities</p>
<p><strong>Link to Methodology:</strong> <a href="https://traditional.leidenranking.com/Content/CWTS%20Leiden%20Ranking%202024.pdf" class="uri">https://traditional.leidenranking.com/Content/CWTS%20Leiden%20Ranking%202024.pdf</a></p>
<p><strong>Data Sources:</strong> Web of Science (Publikationen), OpenAlex (Open Access Status)</p>
<p><strong>Dimension with Open Access Indicators (Weight):</strong> Open Access</p>
<p><strong>Open Access Indicators (Weight):</strong></p>
<ul>
<li>Total number of publications by a university</li>
<li>Number and proportion of open access publications by a university</li>
<li>Number and proportion of gold open access publications by a university</li>
<li>Number and proportion of hybrid open access publications by a university</li>
<li>Number and proportion of bronze open access publications by a university</li>
<li>Number and proportion of green open access publications by a university</li>
<li>Number and proportion of publications by a university whose open access status is unknown</li>
</ul>
<p><strong>Publication-/Update-Frequency:</strong> annually</p>
<p><strong>Number of Institutions:</strong> 1.506 universities</p>
<p><strong>Geographic Scope:</strong> global</p>
<p><strong>Presentation:</strong> multi-indicator ranking</p>
<p><strong>Data Availability:</strong> Data of ranking results available under CC-BY licence: <span class="citation" data-cites="LR2024_data">Van Eck (<a href="#ref-LR2024_data" role="doc-biblioref">2024a</a>)</span></p>
</div>
</div>
</div>
</section><section id="leiden-ranking-open-edition" class="level3"><h3 class="anchored" data-anchor-id="leiden-ranking-open-edition">Leiden Ranking Open Edition</h3>
<p>The Leiden Ranking Open Edition has been produced annually by the Centre for Science and Technology Studies (CWTS) at Leiden University in the Netherlands since 2024 <span class="citation" data-cites="LROE2024">(<a href="#ref-LROE2024" role="doc-biblioref">Waltman et al., 2024</a>)</span>. It is an approximate reproduction of the traditional Leiden Ranking using open data sources <span class="citation" data-cites="LROE2024">(<a href="#ref-LROE2024" role="doc-biblioref">Waltman et al., 2024</a>)</span> and also does not offer a traditional league table but provides various bibliometric indicators along the dimensions of <em>scientific impact</em>, <em>collaboration</em>, and <em>Open Access</em>. The indicators in the Open Edition are also presented in both size-dependent (absolute numbers) and size-independent (relative proportions) forms to account for differences in the size of universities. The Open Edition of the Leiden Ranking also offers trend analyses over time periods and stability intervals to account for statistical uncertainties <span class="citation" data-cites="LROE_method LROE_updates">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>, <a href="#ref-LROE_updates" role="doc-biblioref">n.d.-f</a>)</span>.</p>
<p>The 2024 version of the Leiden Ranking Open Edition includes bibliometric data for 1,506 universities worldwide <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Indicators are provided for four-year time periods, with the 2024 version extending this to the period 2019–2022 <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. The bibliographic data comes from OpenAlex, but only so-called <em>core publications</em> are considered <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Compared to the traditional Leiden Ranking, the Open Edition also includes publications of the type “book chapters” published in book series as <em>core publications</em>. Furthermore, all publications must include author affiliations and references to be considered <em>core publications</em>. All other criteria for <em>core publications</em> and <em>core journals</em> are identical to those of the traditional Leiden Ranking <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>.</p>
<p>The Leiden Ranking Open Edition also focuses on Open Access publications and offers largely the same Open Access indicators as the traditional Leiden Ranking, with the exception of indicators for publications with unknown Open Access status <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Additionally, the Leiden Ranking Open Edition has the distinctive feature that the publications underlying the indicators can be viewed on the web interface <span class="citation" data-cites="LROE2024a">(<a href="#ref-LROE2024a" role="doc-biblioref">van Eck, Waltman, et al., 2024</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 2024</p>
<p><strong>Website:</strong> <a href="https://www.open.leidenranking.com/" class="uri">https://www.open.leidenranking.com/</a></p>
<p><strong>Creator:</strong> <a href="https://www.universiteitleiden.nl/en/social-behavioural-sciences/cwts">Centre for Science and Technology Studies (CWTS)</a></p>
<p><strong>Ranking Type:</strong> University ranking</p>
<p><strong>Sectors:</strong> Universities</p>
<p><strong>Link to Methodology:</strong> <a href="https://open.leidenranking.com/Content/CWTS%20Leiden%20Ranking%20Open%20Edition%202024.pdf" class="uri">https://open.leidenranking.com/Content/CWTS%20Leiden%20Ranking%20Open%20Edition%202024.pdf</a></p>
<p><strong>Data Sources:</strong> OpenAlex</p>
<p><strong>Dimension with Open Access Indicators (Weight):</strong> Open Access</p>
<p><strong>Open Access Indicators (Weight):</strong></p>
<ul>
<li>Total number of publications by a university</li>
<li>Number and proportion of open access publications by a university</li>
<li>Number and proportion of gold open access publications by a university</li>
<li>Number and proportion of hybrid open access publications by a university</li>
<li>Number and proportion of bronze open access publications by a university</li>
<li>Number and proportion of green open access publications by a university</li>
</ul>
<p><strong>Publication-/Update-Frequency:</strong> annually</p>
<p><strong>Number of Institutions:</strong> 1,506 universities</p>
<p><strong>Geographic Scope:</strong> global</p>
<p><strong>Presentation:</strong> multi-indicator ranking</p>
<p><strong>Data Availability:</strong> Raw data and data of ranking results available under CC0 licence:</p>
<ul>
<li>Rohdaten: <span class="citation" data-cites="LROE2024_raw">Van Eck (<a href="#ref-LROE2024_raw" role="doc-biblioref">2024b</a>)</span>
</li>
<li>Ergebnisdaten: <span class="citation" data-cites="LROE2024_results">Van Eck (<a href="#ref-LROE2024_results" role="doc-biblioref">2024c</a>)</span>
</li>
</ul>
</div>
</div>
</div>
</section><section id="scimago-institutions-ranking" class="level3"><h3 class="anchored" data-anchor-id="scimago-institutions-ranking">SCImago Institutions Ranking</h3>
<p>The SCImago Institutions Ranking has been produced annually by the SCImago Research Group since 2009 <span class="citation" data-cites="Rousseau2018">(<a href="#ref-Rousseau2018" role="doc-biblioref">Rousseau et al., 2018</a>)</span>. The ranking offers a traditional league table of scientific and research-related institutions based on a composite indicator on a scale between 0 and 100. The composite indicator combines evaluations along three dimensions: research, innovation, and societal impact. The composite indicator is derived from a weighted combination of metrics along these dimensions, using both size-dependent and size-independent metrics. For each institution, the ranking also provides a series of graphs, for example, on rank development over time, comparisons at national, regional, or global levels, or comparisons with similar institutions based on publication profiles <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>.</p>
<p>The 2025 version of the SCImago Institutions Ranking includes data for 9,756 institutions worldwide <span class="citation" data-cites="SIR">(<a href="#ref-SIR" role="doc-biblioref">SCImago Research Group, n.d.-b</a>)</span>. The composite indicator is provided annually for a five-year period ending two years before the ranking’s publication, meaning for the 2025 version, the period is 2019–2023. The bibliographic data comes from Scopus. The selection of institutions is based on their publication performance. In the last year of the period considered, institutions must have published at least 100 Scopus-indexed publications to be included in the ranking. Furthermore, at least 75% of an institution’s total publication volume must consist of citable documents. For the SCImago Institutions Ranking, citable documents include the publication types articles, book chapters, conference contributions, reviews, and short surveys <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>.</p>
<p>Within the research dimension, which accounts for 50% of the composite indicator, an Open Access indicator was added to the ranking beginning with the 2019 version. This indicator accounts for 2% of the research dimension and measures the percentage of documents published in Open Access journals or indexed in Unpaywall. To determine the Open Access status of publications, the SCImago Institutions Ranking uses Unpaywall as its data source <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 2025</p>
<p><strong>Website:</strong> <a href="https://www.scimagoir.com/" class="uri">https://www.scimagoir.com/</a></p>
<p><strong>Creator:</strong> <a href="https://www.scimagolab.com/">SCImago Research Group</a></p>
<p><strong>Ranking Type:</strong> Institutional ranking</p>
<p><strong>Sectors:</strong> Government agencies, universities, companies, health organisations, non-profit organisations</p>
<p><strong>Link to Methodology:</strong> <a href="https://www.scimagoir.com/methodology.php" class="uri">https://www.scimagoir.com/methodology.php</a></p>
<p><strong>Data Sources:</strong> Scopus (publications), Unpaywall (Open Access status)</p>
<p><strong>Dimension with Open Access Indicators (Weight):</strong> Research (50%)</p>
<p><strong>Open Access Indicators (Weight):</strong> Share of documents published in open access journals or indexed in Unpaywall (2%)</p>
<p><strong>Publication-/Update-Frequency:</strong> annually</p>
<p><strong>Number of Institutions:</strong> 9,756 universities and research-related institutions</p>
<p><strong>Geographic Scope:</strong> global</p>
<p><strong>Presentation:</strong> league table</p>
<p><strong>Data Availability:</strong> Data of ranking results available via the ranking website, no licence information provided: <a href="https://www.scimagoir.com/rankings.php" class="uri">https://www.scimagoir.com/rankings.php</a></p>
</div>
</div>
</div>
</section><section id="qs-sustainability-ranking" class="level3"><h3 class="anchored" data-anchor-id="qs-sustainability-ranking">QS Sustainability Ranking</h3>
<p>The QS World University Rankings: Sustainability has been produced annually by Quacquarelli Symonds since 2023, following a pilot version released in 2022 <span class="citation" data-cites="QS_date">(<a href="#ref-QS_date" role="doc-biblioref">Quacquarelli Symonds, 2024</a>)</span>. The ranking offers a traditional league table of universities based on a composite indicator for individual categories and subcategories (<em>Lenses</em>), as well as an overall score. The ranking evaluates institutions along three dimensions: <em>Environmental Impact</em>, <em>Social Impact</em>, and <em>Governance</em>.</p>
<p>The 2025 version of the QS World University Rankings: Sustainability includes data for 1,744 universities worldwide <span class="citation" data-cites="QS_date">(<a href="#ref-QS_date" role="doc-biblioref">Quacquarelli Symonds, 2024</a>)</span>. The bibliographic data comes from Scopus and covers a five-year period <span class="citation" data-cites="QS_papers">(<a href="#ref-QS_papers" role="doc-biblioref">Quacquarelli Symonds, n.d.-c</a>)</span>. Only the publication types articles, reviews, conference contributions, books, book chapters, articles in press, and business articles are considered <span class="citation" data-cites="QS_paperdef QS_scopus">(<a href="#ref-QS_paperdef" role="doc-biblioref">Quacquarelli Symonds, n.d.-d</a>, <a href="#ref-QS_scopus" role="doc-biblioref">n.d.-e</a>)</span>. Institutions are included in the QS World University Rankings: Sustainability only if they meet eligibility criteria for inclusion in at least one of the rankings <em>QS World University Rankings</em>, <em>QS Rankings by Region</em>, or <em>QS Rankings by Subject</em> and also achieve a non-zero score for specific indicators within the <em>Environmental Impact</em> and <em>Social Impact</em> dimensions <span class="citation" data-cites="QS_sustain">(<a href="#ref-QS_sustain" role="doc-biblioref">Quacquarelli Symonds, n.d.-f</a>)</span>.</p>
<p>Within the <em>Governance</em> dimension, which accounts for 10% of the overall score, an Open Access publications indicator is included. This indicator accounts for 1% of the <em>Governance</em> dimension and measures the proportion of Open Access publications in the institution’s total publication volume. The proportion is calculated individually for the six fields considered and aggregated into a weighted sum. Gold and hybrid publications are weighted more heavily in the calculation than green Open Access publications. To determine the Open Access status of publications, the QS World University Rankings: Sustainability uses Unpaywall as its data source <span class="citation" data-cites="QS_governance">(<a href="#ref-QS_governance" role="doc-biblioref">Quacquarelli Symonds, n.d.-a</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 2025</p>
<p><strong>Website:</strong> <a href="https://www.topuniversities.com/sustainability-rankings" class="uri">https://www.topuniversities.com/sustainability-rankings</a></p>
<p><strong>Creator:</strong> <a href="https://www.qs.com/">Quacquarelli Symonds Ltd.</a></p>
<p><strong>Ranking Type:</strong> University ranking</p>
<p><strong>Sectors:</strong> Universities</p>
<p><strong>Link to Methodology:</strong> <a href="https://support.qs.com/hc/en-gb/articles/8551503200668-QS-World-University-Rankings-Sustainability" class="uri">https://support.qs.com/hc/en-gb/articles/8551503200668-QS-World-University-Rankings-Sustainability</a></p>
<p><strong>Data Sources:</strong> Scopus (publications), Unpaywall (Open Access status)</p>
<p><strong>Dimension with Open Access Indicators (Weight):</strong> Governance (10%)</p>
<p><strong>Open Access Indicators (Weight):</strong> The proportion of an institution’s total research output that is available as open access according to Unpaywall (1%)</p>
<p><strong>Publication-/Update-Frequency:</strong> annually</p>
<p><strong>Number of Institutions:</strong> 1,744 universities</p>
<p><strong>Geographic Scope:</strong> global</p>
<p><strong>Presentation:</strong> league table</p>
<p><strong>Data Availability:</strong> Data of ranking results available on the ranking website after registration, no licence information provided: <a href="https://www.topuniversities.com/sustainability-rankings" class="uri">https://www.topuniversities.com/sustainability-rankings</a></p>
</div>
</div>
</div>
</section><section id="coki-oa-dashboard" class="level3"><h3 class="anchored" data-anchor-id="coki-oa-dashboard">COKI OA Dashboard</h3>
<p>The COKI Open Access Dashboard has been produced by the Curtin Open Knowledge Initiative since 2022 <span class="citation" data-cites="COKI_date COKI_newsletter">(<a href="#ref-COKI_date" role="doc-biblioref">Curtin Open Knowledge Initiative, 2022</a>; <a href="#ref-COKI_newsletter" role="doc-biblioref">Curtin Open Knowledge Initiative &amp; Wilson, 2022</a>)</span>. The dashboard is not a traditional ranking but allows institutions and countries to be sorted by Open Access percentage and total as well as Open Access publication volumes <span class="citation" data-cites="COKI_date">(<a href="#ref-COKI_date" role="doc-biblioref">Curtin Open Knowledge Initiative, 2022</a>)</span>. The dashboard also shows, for individual countries and institutions, the platforms through which Open Access publications are made available, both aggregated over the entire publication period and broken down by individual publication years <span class="citation" data-cites="COKI_date">(<a href="#ref-COKI_date" role="doc-biblioref">Curtin Open Knowledge Initiative, 2022</a>)</span>.</p>
<p>The version of the COKI Open Access Dashboard from August 18, 2025, includes data for 227 countries and 56,187 institutions worldwide <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>. The bibliographic data comes from multiple open data sources and covers the publication period 2000–2024, with Crossref being used primarily for publication identification <span class="citation" data-cites="COKI_how COKI_dashboard">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>, <a href="#ref-COKI_dashboard" role="doc-biblioref">n.d.-d</a>)</span>. The selection of publication types is less restrictive compared to the other rankings, with only specific types such as datasets, databases, components, report components, peer reviews, funding acknowledgments, conference proceedings, journal issues, report series, book catalogs, and publications without a specified type being excluded <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>. Institutions must have at least 50 publications to be included in the COKI Open Access Dashboard, unless the institutions were already included in the dataset when it was based on the Microsoft Academic Graph dataset <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>.</p>
<p>The COKI Open Access Dashboard focuses exclusively on the Open Access activities of institutions and countries. While the list view primarily displays the absolute number and percentage of Open Access publications, detailed views for individual institutions and countries provide more differentiated breakdowns of publication activities and locations, supplemented by visualizations <span class="citation" data-cites="COKI_dashboard">(<a href="#ref-COKI_dashboard" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-d</a>)</span>. To determine the Open Access status of publications, the COKI Open Access Dashboard uses Unpaywall as its data source <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 18.08.2025</p>
<p><strong>Website:</strong> <a href="https://open.coki.ac/" class="uri">https://open.coki.ac/</a></p>
<p><strong>Creator:</strong> <a href="https://openknowledge.community/">Curtin Open Knowledge Initiative</a></p>
<p><strong>Ranking Type:</strong> Country and institutional ranking</p>
<p><strong>Sectors:</strong> Funding organisations, government agencies, universities, companies, health organisations, non-profit organisations, infrastructure organisations, archives, others</p>
<p><strong>Link to Methodology:</strong> <a href="https://open.coki.ac/how/" class="uri">https://open.coki.ac/how/</a></p>
<p><strong>Data Sources:</strong> Crossref (publications), Unpaywall (Open Access status)</p>
<p><strong>Dimension with Open Access Indicators (Weight):</strong> –</p>
<p><strong>Open Access Indicators (Weight):</strong></p>
<ul>
<li>Percentage of open access publications</li>
<li>Total number of publications</li>
<li>Total number of open access publications</li>
<li>Percentage of articles accessible via open access through the publisher</li>
<li>Percentage of articles accessible via open access through other platforms (repositories, preprint servers, etc.)</li>
<li>Percentage of articles that are accessible via both the publisher and other platforms</li>
<li>Percentage of closed articles</li>
<li>Percentage of articles published in an open access journal</li>
<li>Percentage of articles published in a hybrid journal</li>
<li>Percentage of articles that are open access via the publisher without reuse rights</li>
<li>Percentage of articles that are open access via institutional repositories</li>
<li>Percentage of articles that are open access via preprint servers</li>
<li>Percentage of articles that are open access via subject repositories</li>
<li>Percentage of articles that are open access via other public repositories</li>
<li>Percentage of articles that are open access via other websites or portals</li>
</ul>
<p><strong>Publication-/Update-Frequency:</strong> regularly</p>
<p><strong>Number of Institutions:</strong> 56,187 institutions</p>
<p><strong>Geographic Scope:</strong> global</p>
<p><strong>Presentation:</strong> Multi-indicator dashboard</p>
<p><strong>Data Availability:</strong> Data of ranking results available via the ranking website under CC-BY licence: <a href="https://open.coki.ac/data/" class="uri">https://open.coki.ac/data/</a></p>
</div>
</div>
</div>
</section><section id="comparability-of-ranking-results" class="level3"><h3 class="anchored" data-anchor-id="comparability-of-ranking-results">Comparability of Ranking Results</h3>
<p>To assess how comparable the results of the selected rankings are, the following sections focus on examining the data sources used by the rankings, the Open Access indicators and their weighting, the number of institutions represented in all rankings, the geographical distribution of institutions across countries and world regions, and the possibility of institutional participation in the data collection process of the ranking providers.</p>
<p>The aim is to identify how the individual ranking systems differ and what implications this may have for the use of a particular ranking in Open Access monitoring activities or strategic decision-making.</p>
</section><section id="data-sources" class="level3 page-columns page-full"><h3 class="anchored" data-anchor-id="data-sources">Data Sources</h3>
<p>This section examines the data sources used by the five rankings, focusing on two categories of data sources: those used for collecting bibliographic data and those used for determining the Open Access status. Differences in the coverage, completeness, and methodology of these data sources can lead to discrepancies in the calculation of metrics and thus limit the comparability of the results across different rankings. Additionally, it is investigated whether disciplinary differences arise between the rankings due to the data sources used.</p>
<section id="bibliographic-data-sources" class="level4"><h4 class="anchored" data-anchor-id="bibliographic-data-sources">Bibliographic Data Sources</h4>
<div id="tbl-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 1: Data sources used for collecting bibliographic data
</figcaption><div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: left;">Ranking</th>
<th style="text-align: center;">Web of Science</th>
<th style="text-align: center;">Scopus</th>
<th style="text-align: center;">OpenAlex</th>
<th style="text-align: center;">Crossref</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Leiden Ranking</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Leiden Ranking Open Edition</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCImago Institutions Ranking</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">QS Sustainability Ranking</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">COKI OA Dashboard</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section><section id="open-access-data-sources" class="level4"><h4 class="anchored" data-anchor-id="open-access-data-sources">Open Access Data Sources</h4>
<div id="tbl-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 2: Data sources used for determining the Open Access status
</figcaption><div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: left;">Ranking</th>
<th style="text-align: center;">Unpaywall</th>
<th style="text-align: center;">OpenAlex</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Leiden Ranking</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leiden Ranking Open Edition</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCImago Institutions Ranking</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">QS Sustainability Ranking</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">COKI OA Dashboard</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section><section id="disciplinary-differences" class="level4 page-columns page-full"><h4 class="anchored" data-anchor-id="disciplinary-differences">Disciplinary Differences</h4>
<div class="column-page">
<div id="fig-fields" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-fields-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe width="1040" height="560" src="https://app.powerbi.com/view?r=eyJrIjoiZmI0YzljYjYtYWZlNy00YzUzLWE1YjYtYjdkNmYwMDUzNjFmIiwidCI6ImNhMmE3Zjc2LWRiZDctNGVjMC05MTA4LTZiM2Q1MjRmYjdjOCIsImMiOjh9"></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fields-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 1: Disciplinary differences between the traditional Leiden Ranking 2024 and the Leiden Ranking Open Edition 2024 (Source: <a href="https://app.powerbi.com/view?r=eyJrIjoiZmI0YzljYjYtYWZlNy00YzUzLWE1YjYtYjdkNmYwMDUzNjFmIiwidCI6ImNhMmE3Zjc2LWRiZDctNGVjMC05MTA4LTZiM2Q1MjRmYjdjOCIsImMiOjh9">Open Dashboard 2024</a>, <span class="citation" data-cites="LROE_resources">(<a href="#ref-LROE_resources" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-d</a>)</span>)
</figcaption></figure>
</div>
</div>
</section></section><section id="open-access-indicators" class="level3"><h3 class="anchored" data-anchor-id="open-access-indicators">Open Access Indicators</h3>
</section><section id="institutional-overlap" class="level3"><h3 class="anchored" data-anchor-id="institutional-overlap">Institutional Overlap</h3>
<p>To determine the institutional overlaps between the rankings, the available results data from the rankings were first downloaded<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. In addition to the names and locations (country information, sometimes also region and sub-region) of all institutions, the data from both versions of the Leiden Ranking and the COKI OA Dashboard also include identifiers from the <em>Research Organization Registry (ROR)</em>. Furthermore, the data from the COKI OA Dashboard and the SCImago Institutions Ranking include sector classifications for all institutions represented in the rankings.</p>
<p>To uniquely assign ROR IDs to identical institutions across the rankings, the ROR dataset (version 1.69) <span class="citation" data-cites="ror_data">(<a href="#ref-ror_data" role="doc-biblioref">Research Organization Registry, 2025</a>)</span> was downloaded in full. A machine-based matching process was then performed for both the SCImago Institutions Ranking and the QS Sustainability Ranking using institutional names and country information. For the QS data, which included entries for a total of 1,743 institutions, ROR IDs could be assigned to 1,204 institutions through machine-based matching. For the remaining 539 institutions, manual assignment of ROR IDs was performed, although no assignment could be made for 7 institutions. Therefore, only 1,736 institutions from the QS Sustainability Ranking could be considered for the analysis of institutional overlaps.</p>
<p>Assigning ROR IDs to the 9,755 institutions included in the SCImago Institutions Ranking proved more challenging. Through machine-based matching using institutional names and country information, ROR IDs could only be assigned to 4,714 institutions. In part, this may be due to the fact that the SCImago Institutions Ranking also lists institutions classified as multinational <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>. This seems to particularly affect companies that operate globally, such as <a href="https://www.scimagoir.com/institution.php?idp=89900">Google</a>. While ROR also provides IDs for companies (see <a href="https://ror.org/00njsd438">Google</a>), it appears to assign clear country classifications. However, the greater difficulty for machine-based matching likely stems from differences in name spelling between the SCImago Institutions Ranking and ROR<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. To increase the coverage of ROR IDs for the SCImago Institutions Ranking, a fuzzy matching approach was tested, which also considered alternative name forms and acronyms from the ROR dataset. However, the result was not sufficiently accurate and would have required extensive data cleaning. Overall, this constitutes a significant limitation for the usability of the SCImago dataset for a global analysis of institutional overlaps.</p>
<p>Due to the difficulties in assigning ROR IDs, it was decided to limit the analysis of institutional overlaps to institutions from Germany. In the QS Sustainability Ranking dataset, a total of 50 institutions from Germany could be identified, all of which could be assigned ROR IDs. In the SCImago Institutions Ranking dataset, a total of 364 institutions from Germany could be identified, of which 342 could not be assigned ROR IDs through machine-based matching. Therefore, manual assignment of ROR IDs was performed, although no assignment could be made for 6 of the 342 institutions. For the analysis of institutional overlaps among German institutions, 385 institutions from the SCImago Institutions Ranking could thus be considered.</p>
<p><a href="#fig-2" class="quarto-xref">Figure 2</a> quantitatively represents the institutional overlaps of German institutions with ROR IDs in the five ranking systems. The figure only includes institutions that could be assigned ROR IDs.</p>
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="upset">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/all_de_institution_upset.png" class="lightbox" data-gallery="upset" title="Figure 2: Institutional overlaps for all German institutions with ROR IDs in five ranking systems"><img src="rankings/plots/all_de_institution_upset.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 2: Institutional overlaps for all German institutions with ROR IDs in five ranking systems
</figcaption></figure>
</div>
<p>Overall, 2.928 unique institutions from Germany could be identified across all ranking systems. From <a href="#fig-2" class="quarto-xref">Figure 2</a>, it is evident that the COKI OA Dashboard clearly includes more German institutions than all other ranking systems, both in total (2.927 institutions, 99,97 %) and in terms of the number of institutions that are not represented in any other ranking system (2.570 institutions, 87,77 %). This could be particularly due to the fact that the COKI OA Dashboard covers a relatively long publication period (2000–2024) and also includes institutions from multiple sectors, as well as institutions with a relatively small publication volume of at least 50 publications <span class="citation" data-cites="COKI_how COKI_data">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>, <a href="#ref-COKI_data" role="doc-biblioref">n.d.-b</a>)</span>.</p>
<p><a href="#fig-2" class="quarto-xref">Figure 2</a> also shows that of the 358 institutions from the SCImago Institutions Ranking, 1 institution (0,03 %) is not represented in any other ranking. In contrast, all institutions from both versions of the Leiden Ranking and the QS Sustainability Ranking are also represented in at least one other ranking. Overall, only 47 institutions (1,61 %) are represented in all five ranking systems.</p>
<p>While the QS Sustainability Ranking and both versions of the Leiden Ranking only include universities in their rankings, the COKI OA Dashboard and the SCImago Institutions Ranking also include institutions from other sectors. Universities in the COKI dataset are classified with the institution type <em>Education</em>, while in the SCImago Institutions Ranking dataset, the sector <em>Universities</em> is assigned to universities. To further investigate the institutional overlaps of German universities between the five ranking systems, a <em>sector</em> column was added to the merged dataset of all ranking systems. For institutions represented in both versions of the Leiden Ranking or in the QS Sustainability Ranking, the sector classification <em>Universities</em> was added. For institutions represented in the SCImago Institutions Ranking or the COKI OA Dashboard, the original classification was retained. The dataset was then filtered to include only institutions assigned to the <em>Universities</em> or <em>Education</em> sectors.</p>
<p><a href="#fig-3" class="quarto-xref">Figure 3</a> represents the institutional overlaps of German universities between the rankings. The figure also only includes institutions that could be assigned ROR IDs.</p>
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="upset">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/univs_de_institution_upset.png" class="lightbox" data-gallery="upset" title="Figure 3: Institutional overlaps for German universities with ROR IDs in five ranking systems"><img src="rankings/plots/univs_de_institution_upset.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 3: Institutional overlaps for German universities with ROR IDs in five ranking systems
</figcaption></figure>
</div>
<p>Overall, 395 different German universities could be identified across all ranking systems. From <a href="#fig-3" class="quarto-xref">Figure 3</a>, it is evident that the COKI OA Dashboard also includes more German universities than all other ranking systems, both in total (395 institutions, 100 %) and in terms of the number of institutions that are not represented in any other ranking system (287 institutions, 72,66 %). According to the German Federal Statistical Office, a total of 422 German universities were counted in the 2024/2025 winter semester <span class="citation" data-cites="destatis">(<a href="#ref-destatis" role="doc-biblioref">Statistisches Bundesamt, 2025</a>)</span>. Accordingly, the COKI OA Dashboard currently represents 93,6 % of all German universities. It is also the only ranking system that includes universities not represented in any other ranking. The absolute number of German universities represented in all five ranking systems remains the same as the absolute number of all German institutions represented in all five ranking systems.</p>
<p>The COKI OA Dashboard and the SCImago Institutions Ranking are the only two of the analyzed ranking systems that do not exclusively include universities. With regard to Germany, of the total 2.927 German institutions represented in the COKI OA Dashboard, 13,5 % are German universities. In comparison, of the total 358 German institutions represented in the SCImago Institutions Ranking, 30,17 % are German universities. For both ranking systems, it can thus be concluded that the majority of represented institutions, at least with regard to Germany, are assigned to other sectors.</p>
</section><section id="geographical-distribution" class="level3"><h3 class="anchored" data-anchor-id="geographical-distribution">Geographical Distribution</h3>
<p>Figures <a href="#fig-leidenmaps" class="quarto-xref">4</a> and <a href="#fig-maps" class="quarto-xref">5</a><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> show the geographical distribution of institutions in terms of the countries and world regions in which they are located. While all five rankings have a global orientation, the figures aim to visualize whether there are differences in the geographical distribution between the rankings. To ensure better comparability, the institutions in all ranking systems were limited to those assigned to the university sector (<em>Universities</em>, <em>Education</em>).</p>
<div id="fig-leidenmaps" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-leidenmaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-leidenmaps" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-LR" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-LR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/lr_map.png" class="lightbox" data-gallery="map" title="Figure 4 (a): Leiden Ranking 2024"><img src="rankings/plots/lr_map.png" class="img-fluid figure-img" data-ref-parent="fig-leidenmaps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-LR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Leiden Ranking 2024
</figcaption></figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-leidenmaps" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-LROE" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-LROE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/lroe_map.png" class="lightbox" data-gallery="map" title="Figure 4 (b): Leiden Ranking Open Edition 2024"><img src="rankings/plots/lroe_map.png" class="img-fluid figure-img" data-ref-parent="fig-leidenmaps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-LROE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Leiden Ranking Open Edition 2024
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-leidenmaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 4: Geographical distribution of institutions represented in the Leiden Rankings across countries and world regions
</figcaption></figure>
</div>
<div id="fig-maps" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-maps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-maps" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-sir" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sir-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/sir_univ_map.png" class="lightbox" data-gallery="map" title="Figure 5 (a): SCImago Institutions Ranking 2025 (Universities)"><img src="rankings/plots/sir_univ_map.png" class="img-fluid figure-img" data-ref-parent="fig-maps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sir-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) SCImago Institutions Ranking 2025 (Universities)
</figcaption></figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-maps" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-qs" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-qs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/qs_map.png" class="lightbox" data-gallery="map" title="Figure 5 (b): QS Sustainability Ranking 2025"><img src="rankings/plots/qs_map.png" class="img-fluid figure-img" data-ref-parent="fig-maps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-qs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) QS Sustainability Ranking 2025
</figcaption></figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-maps" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-coki" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-coki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/coki_univ_map.png" class="lightbox" data-gallery="map" title="Figure 5 (c): COKI OA Dashboard 2025 (Education)"><img src="rankings/plots/coki_univ_map.png" class="img-fluid figure-img" data-ref-parent="fig-maps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-coki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) COKI OA Dashboard 2025 (Education)
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-maps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 5: Geographical distribution of institutions represented in the SIR, QS, and COKI ranking systems across countries and world regions
</figcaption></figure>
</div>
<p>If we consider the absolute numbers of universities, Figures <a href="#fig-leidenmaps" class="quarto-xref">4</a> and <a href="#fig-maps" class="quarto-xref">5</a> show that for both versions of the Leiden Ranking and the SCImago Institutions Ranking, the majority of universities are located in China (LR: 313 institutions, LROE: 313 institutions, SIR: 634 institutions). In contrast, for the QS Sustainability Ranking and the COKI OA Dashboard, the majority of institutions are located in the United States of America (QS: 238 institutions, COKI: 2688 institutions). Furthermore, the figures illustrate that, with the exception of the COKI OA Dashboard, several countries in the global South are not represented in the ranking systems.</p>
<p>In addition to the absolute number of universities, the relative distribution of universities across countries and ranking systems is examined using the <em>preference</em> metric according to <span class="citation" data-cites="Moed2016">Moed (<a href="#ref-Moed2016" role="doc-biblioref">2016</a>)</span>. <span class="citation" data-cites="Moed2016">Moed (<a href="#ref-Moed2016" role="doc-biblioref">2016</a>)</span> defines <em>preference</em> as follows<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>:</p>
<blockquote class="blockquote">
<p>The preference of ranking system R for a particular country C is expressed as the ratio of the actual and the expected number of institutions from C appearing in R, where the expected number is based on the total number of institutions across countries and across systems, under the assumption of independence of these two variables. A value of 1.0 indicates that the number of institutions from C in R is ‘as expected’.</p>
</blockquote>
<p>The resulting preference score (<em>preference score</em>) measures whether a country, measured by the number of institutions it hosts, is overrepresented or underrepresented in a ranking system relative to expectations. The metric is neutral at a value of 1.0, meaning the number of institutions from a country in a ranking system matches expectations. Values above 1.0 indicate that more institutions from a country are included in a ranking system than expected. Values below 1.0 indicate that fewer institutions from a country are included in a ranking system than expected.</p>
<p><a href="#tbl-pref" class="quarto-xref">Table 3</a> presents, for all five ranking systems, the top 5 countries based on preference score, as well as Germany, showing the absolute number of universities and the respective preference score.</p>
<div id="tbl-pref" class="quarto-layout-panel anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pref-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 3: Preference scores of the top 5 countries and Germany per ranking system
</figcaption><div aria-describedby="tbl-pref-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 37%">
<col style="width: 22%">
<col style="width: 24%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Ranking</th>
<th style="text-align: left;">Country</th>
<th style="text-align: left;">No. Universities</th>
<th style="text-align: left;">preference score</th>
</tr></thead>
<tbody>
<tr class="odd">
<td rowspan="7" style="text-align: left;">Leiden</td>
<td style="text-align: left;">Luxembourg</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,45</td>
</tr>
<tr class="even">
<td style="text-align: left;">Australia</td>
<td style="text-align: left;">35</td>
<td style="text-align: left;">2,34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Spain</td>
<td style="text-align: left;">47</td>
<td style="text-align: left;">2,32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Italy</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">2,22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: left;">313</td>
<td style="text-align: left;">2,15</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Germany</td>
<td style="text-align: left;">57</td>
<td style="text-align: left;">1,46</td>
</tr>
<tr class="even">
<td rowspan="7" style="text-align: left;">SIR</td>
<td style="text-align: left;">Faroe Islands</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">French Guiana</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grenada</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guadeloupe</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lesotho</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Germany</td>
<td style="text-align: left;">108</td>
<td style="text-align: left;">0,82</td>
</tr>
<tr class="odd">
<td rowspan="7" style="text-align: left;">COKI</td>
<td style="text-align: left;">Myanmar</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cambodia</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nicaragua</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="even">
<td style="text-align: left;">Somalia</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">El Salvador</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Germany</td>
<td style="text-align: left;">397</td>
<td style="text-align: left;">0,96</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 26%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Ranking</th>
<th style="text-align: left;">Land</th>
<th style="text-align: left;">Nr. Hochschulen</th>
<th style="text-align: left;">preference score</th>
</tr></thead>
<tbody>
<tr class="odd">
<td rowspan="7" style="text-align: left;">Leiden OE</td>
<td style="text-align: left;">Luxembourg</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,45</td>
</tr>
<tr class="even">
<td style="text-align: left;">Australia</td>
<td style="text-align: left;">35</td>
<td style="text-align: left;">2,34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Spain</td>
<td style="text-align: left;">47</td>
<td style="text-align: left;">2,32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Italy</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">2,22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: left;">313</td>
<td style="text-align: left;">2,15</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Germany</td>
<td style="text-align: left;">57</td>
<td style="text-align: left;">1,46</td>
</tr>
<tr class="even">
<td rowspan="7" style="text-align: left;">QS</td>
<td style="text-align: left;">Brunei</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">3,70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hong Kong</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">3,17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malta</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saudi Arabia</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">2,67</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jordan</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">2,50</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Germany</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">1,11</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</figure>
</div>
<p><a href="#tbl-pref" class="quarto-xref">Table 3</a> shows different geographical coverage of the various ranking systems in terms of overproportionally represented countries. Both versions of the Leiden Ranking tend to focus on Europe, the SCImago Institutions Ranking on North and South America, the COKI OA Dashboard predominantly on Asia and Central America, and the QS Sustainability Ranking primarily on Asia. A particular feature of the COKI OA Dashboard is that 68 countries have the same preference score of 1.61. The countries shown in <a href="#tbl-pref" class="quarto-xref">Table 3</a> are the first five entries resulting from a descending sort by the number of institutions from the respective countries. The observation that a large number of countries share the same preference score is due to the fact that the 68 countries are exclusively included in the COKI OA Dashboard.</p>
<p>With regard to Germany, <a href="#tbl-pref" class="quarto-xref">Table 3</a> shows that both versions of the Leiden Ranking and the QS Sustainability Ranking include a slightly overrepresented to overrepresented number of German universities, with preference scores of 1.46 and 1.11, respectively. This suggests that these ranking systems include a slightly higher to higher-than-expected number of German universities, with an absolute number of 50 and 57 universities, respectively. In contrast, while the COKI OA Dashboard includes a significantly higher absolute number of German universities (397), its preference score of 0.96 indicates that this number is below the expected value. For the SCImago Institutions Ranking, the preference score for German universities is only 0.82, indicating that German institutions are underrepresented in this ranking, even though the absolute number of German universities (108) is the second highest.</p>
</section><section id="institutional-participation-in-data-collection" class="level3"><h3 class="anchored" data-anchor-id="institutional-participation-in-data-collection">Institutional Participation in Data Collection</h3>
<p>This section examines the data collection procedures of the various ranking providers and investigates the extent to which institutions can participate in the data collection process relevant to them.</p>
<p>For the traditional Leiden Ranking, the CWTS does not collect any data directly from the ranked institutions <span class="citation" data-cites="LR_method LR_general">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>, <a href="#ref-LR_general" role="doc-biblioref">n.d.-c</a>)</span>. The ranking is based on data from the Web of Science, which is processed and standardized by the CWTS. Since the Web of Science is a proprietary data source with licensing restrictions, the CWTS is unable to make the raw and curated data openly accessible <span class="citation" data-cites="LeidenData">(<a href="#ref-LeidenData" role="doc-biblioref">van Eck, Visser, et al., 2024</a>)</span>. As a result, it is not straightforward for the institutions concerned to verify the data quality.</p>
<p>For the Leiden Ranking Open Edition, no data is collected directly from the institutions either <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. In contrast to the traditional Leiden Ranking, however, the Leiden Ranking Open Edition relies on open data sources, such as OpenAlex and ROR, for the creation of the ranking <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Due to the use of open data sources and the CWTS’s provision of raw and results data <span class="citation" data-cites="LROE_resources">(<a href="#ref-LROE_resources" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-d</a>)</span>, it is possible for the ranked institutions to verify the data quality and participate in the data curation process by reporting issues with data quality to the respective actors.</p>
<p>The methodology of the SCImago Institutions Ranking describes that data is collected from various sources: Scopus, PATSTAT, Google, Semrush, Unpaywall, PlumX Metrics, Mendeley, and Overton <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>. The methodology does not mention any possibility of institutional participation in the data collection process, so it is assumed that no data is collected directly from the ranked institutions. The bibliographic data for the SCImago Institutions Ranking comes from Scopus, a proprietary data source with licensing restrictions, similar to the Web of Science. The raw data from the SCImago Institutions Ranking is not publicly accessible, so it is assumed that ranked institutions are not easily able to verify or correct the data concerning them before they are included in the ranking. For determining the Open Access status, the SCImago Institutions Ranking uses Unpaywall, an open data source. Similar to the Leiden Ranking Open Edition, this could allow institutions to participate in the data curation process by reporting data quality issues directly to Unpaywall. Overall, however, the methodology of the SCImago Institutions Ranking provides little information regarding data quality and potential limitations, nor does it transparently communicate the opportunities for institutions to contribute to improved data quality.</p>
<p>The COKI Open Access Dashboard uses only open data sources for data collection, including Crossref, Unpaywall, and ROR <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>. The methodology of the COKI OA Dashboard describes the process of data collection from external sources in detail <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span> but does not provide any information about data submission by the ranked institutions themselves. Therefore, it is assumed that there is no direct institutional participation in the data collection process. Since the COKI dataset is based on open data sources, similar to the Leiden Ranking Open Edition, it is assumed that the institutions concerned can indirectly participate in the data curation process by reporting data quality issues directly to the various data sources. Additionally, COKI communicates limitations of its dataset <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span> and offers various contact options <span class="citation" data-cites="COKI_contact">(<a href="#ref-COKI_contact" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-a</a>)</span>, so institutions also have the opportunity to actively contribute to improving the quality of the COKI dataset.</p>
<p>The QS Sustainability Ranking is the only one of the five analyzed ranking systems that provides for direct participation of the institutions concerned in the data collection process. The methodology of the QS Sustainability Ranking describes that QS generally encourages all institutions to provide data for the QS Rankings <span class="citation" data-cites="QS_sustain">(<a href="#ref-QS_sustain" role="doc-biblioref">Quacquarelli Symonds, n.d.-f</a>)</span>. For data submission, QS provides a special platform, but the methodology does not offer a precise list of the data requested <span class="citation" data-cites="QS_sustain">(<a href="#ref-QS_sustain" role="doc-biblioref">Quacquarelli Symonds, n.d.-f</a>)</span>. If institutions that qualify for inclusion in the QS Sustainability Ranking do not provide data, QS evaluates these institutions based on proprietary and publicly available data or data previously submitted by the respective institution. A complete opt-out of the ranking by the institution is not provided for. QS argues that the inclusion of all qualifying institutions increases the reliability of the rankings <span class="citation" data-cites="QS_optout">(<a href="#ref-QS_optout" role="doc-biblioref">Quacquarelli Symonds, n.d.-b</a>)</span>. However, QS does not provide information on how many of the ranked institutions actually take the opportunity to submit data.</p>
<p>Overall, it is evident that the opportunity for institutions to participate in the data collection process of the ranking providers is limited. The QS Sustainability Ranking is the only ranking system that directly collects data from the institutions concerned, although it is not entirely clear which specific data is requested from the institutions. The other ranking systems use data exclusively from external sources that are not directly collected from the institutions. The use of open data sources, as in the Leiden Ranking Open Edition or the COKI OA Dashboard, can, however, provide institutions with an opportunity to improve the quality of the data concerning them. High-quality source data and transparent methodologies for creating rankings can further contribute to improving trust in the reliability and validity of the ranking systems.</p>



</section><a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default">
<section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-destatis" class="csl-entry" role="listitem">
Statistisches Bundesamt. (2025). <em><span class="nocase">Hochschulen nach Hochschularten</span></em>. <a href="https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Hochschulen/Tabellen/hochschulen-hochschularten.html">https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Hochschulen/Tabellen/hochschulen-hochschularten.html</a>
</div>
<div id="ref-ror_data" class="csl-entry" role="listitem">
Research Organization Registry. (2025). <em>ROR data (v1.69)</em> [Data set]. Zenodo. <a href="https://doi.org/10.5281/ZENODO.16762508">https://doi.org/10.5281/ZENODO.16762508</a>
</div>
<div id="ref-QS_date" class="csl-entry" role="listitem">
Quacquarelli Symonds. (2024). <em>QS world university rankings: Sustainability 2025 | now live!</em> <a href="https://www.qs.com/insights/articles/qs-world-university-rankings-sustainability-2025-now-live/">https://www.qs.com/insights/articles/qs-world-university-rankings-sustainability-2025-now-live/</a>
</div>
<div id="ref-LROE2024a" class="csl-entry" role="listitem">
van Eck, N. J., Waltman, L., &amp; Neijssel, M. (2024). <em><span class="nocase">Launch of the CWTS Leiden Ranking Open Edition 2024</span></em>. <a href="https://www.leidenmadtrics.nl/articles/launch-of-the-cwts-leiden-ranking-open-edition-2024">https://www.leidenmadtrics.nl/articles/launch-of-the-cwts-leiden-ranking-open-edition-2024</a>
</div>
<div id="ref-LeidenData" class="csl-entry" role="listitem">
van Eck, N. J., Visser, M., &amp; Waltman, L. (2024). <em><span class="nocase">Opening up the CWTS Leiden Ranking: Toward a decentralized and open model for data curation</span></em>. <a href="https://www.leidenmadtrics.nl/articles/opening-up-the-cwts-leiden-ranking-toward-a-decentralized-and-open-model-for-data-curation">https://www.leidenmadtrics.nl/articles/opening-up-the-cwts-leiden-ranking-toward-a-decentralized-and-open-model-for-data-curation</a>
</div>
<div id="ref-LROE2024" class="csl-entry" role="listitem">
Waltman, L., van Eck, N. J., Visser, M., Neijssel, M., Montgomery, L., Neylon, C., Kramer, B., Demes, K., &amp; Priem, J. (2024). <em><span class="nocase">Introducing the Leiden Ranking Open Edition</span></em>. <a href="https://www.leidenmadtrics.nl/articles/introducing-the-leiden-ranking-open-edition">https://www.leidenmadtrics.nl/articles/introducing-the-leiden-ranking-open-edition</a>
</div>
<div id="ref-LR2024_data" class="csl-entry" role="listitem">
Van Eck, N. J. (2024a). <em>CWTS leiden ranking 2024</em> [Data set]. Zenodo. <a href="https://doi.org/10.5281/ZENODO.12606083">https://doi.org/10.5281/ZENODO.12606083</a>
</div>
<div id="ref-LROE2024_raw" class="csl-entry" role="listitem">
Van Eck, N. J. (2024b). <em>CWTS leiden ranking open edition 2024 - data</em> [Data set]. Zenodo. <a href="https://doi.org/10.5281/ZENODO.13868129">https://doi.org/10.5281/ZENODO.13868129</a>
</div>
<div id="ref-LROE2024_results" class="csl-entry" role="listitem">
Van Eck, N. J. (2024c). <em>CWTS leiden ranking open edition 2024 - results</em> [Data set]. Zenodo. <a href="https://doi.org/10.5281/ZENODO.13868018">https://doi.org/10.5281/ZENODO.13868018</a>
</div>
<div id="ref-Diprose2023" class="csl-entry" role="listitem">
Diprose, J. P., Hosking, R., Rigoni, R., Roelofs, A., Chien, T.-Y., Napier, K., Wilson, K., Huang, C.-K. (Karl)., Handcock, R. N., Montgomery, L., &amp; Neylon, C. (2023). A user-friendly dashboard for tracking global open access performance. <em>The Journal of Electronic Publishing</em>, <em>26</em>(1). <a href="https://doi.org/10.3998/jep.3398">https://doi.org/10.3998/jep.3398</a>
</div>
<div id="ref-COKI_newsletter" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative, &amp; Wilson, K. (2022). <em><span>COKI 2022 Update Newsletter</span></em>. <a href="https://openknowledge.community/coki-2022-update-newsletter/">https://openknowledge.community/coki-2022-update-newsletter/</a>
</div>
<div id="ref-COKI_date" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (2022). <em><span>Tracking Global Open Access</span></em>. <a href="https://openknowledge.community/oa-dashboard/">https://openknowledge.community/oa-dashboard/</a>
</div>
<div id="ref-Huang2020" class="csl-entry" role="listitem">
Huang, C.-K. (Karl)., Neylon, C., Brookes-Kenworthy, C., Hosking, R., Montgomery, L., Wilson, K., &amp; Ozaygen, A. (2020). Comparison of bibliographic data sources: Implications for the robustness of university rankings. <em>Quantitative Science Studies</em>, <em>1</em>(2), 445–478. <a href="https://doi.org/10.1162/qss_a_00031">https://doi.org/10.1162/qss_a_00031</a>
</div>
<div id="ref-Rousseau2018" class="csl-entry" role="listitem">
Rousseau, R., Egghe, L., &amp; Guns, R. (2018). Research evaluation. In <em>Becoming metric-wise</em> (pp. 247–292). Elsevier. <a href="https://doi.org/10.1016/b978-0-08-102474-4.00008-x">https://doi.org/10.1016/b978-0-08-102474-4.00008-x</a>
</div>
<div id="ref-Moed2016" class="csl-entry" role="listitem">
Moed, H. F. (2016). A critical comparative analysis of five world university rankings. <em>Scientometrics</em>, <em>110</em>(2), 967–990. <a href="https://doi.org/10.1007/s11192-016-2212-y">https://doi.org/10.1007/s11192-016-2212-y</a>
</div>
<div id="ref-Piro2016" class="csl-entry" role="listitem">
Piro, F. N., &amp; Sivertsen, G. (2016). How can differences in international university rankings be explained? <em>Scientometrics</em>, <em>109</em>(3), 2263–2278. <a href="https://doi.org/10.1007/s11192-016-2056-5">https://doi.org/10.1007/s11192-016-2056-5</a>
</div>
<div id="ref-Waltman2012" class="csl-entry" role="listitem">
Waltman, L., Calero‐Medina, C., Kosten, J., Noyons, E. C. M., Tijssen, R. J. W., Eck, N. J. van, Leeuwen, T. N. van, Raan, A. F. J. van, Visser, M. S., &amp; Wouters, P. (2012). The leiden ranking 2011/2012: Data collection, indicators, and interpretation. <em>Journal of the American Society for Information Science and Technology</em>, <em>63</em>(12), 2419–2432. <a href="https://doi.org/10.1002/asi.22708">https://doi.org/10.1002/asi.22708</a>
</div>
<div id="ref-vanRaan2005" class="csl-entry" role="listitem">
van Raan, A. F. J. (2005). Fatal attraction: Conceptual and methodological problems in the ranking of universities by bibliometric methods. <em>Scientometrics</em>, <em>62</em>(1), 133–143. <a href="https://doi.org/10.1007/s11192-005-0008-6">https://doi.org/10.1007/s11192-005-0008-6</a>
</div>
<div id="ref-LR_method" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-a). <em><span>CWTS Leiden Ranking 2024: Methodology</span></em>. Retrieved June 11, 2025, from <a href="https://traditional.leidenranking.com/Content/CWTS%20Leiden%20Ranking%202024.pdf">https://traditional.leidenranking.com/Content/CWTS%20Leiden%20Ranking%202024.pdf</a>
</div>
<div id="ref-LROE_method" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-b). <em><span>CWTS Leiden Ranking Open Edition 2024: Methodology</span></em>. Retrieved June 11, 2025, from <a href="https://open.leidenranking.com/Content/CWTS%20Leiden%20Ranking%20Open%20Edition%202024.pdf">https://open.leidenranking.com/Content/CWTS%20Leiden%20Ranking%20Open%20Edition%202024.pdf</a>
</div>
<div id="ref-LR_general" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-c). <em><span class="nocase">Information about the CWTS Leiden Ranking</span></em>. Retrieved June 11, 2025, from <a href="https://traditional.leidenranking.com/information/general">https://traditional.leidenranking.com/information/general</a>
</div>
<div id="ref-LROE_resources" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-d). <em><span>Resources</span></em>. Retrieved November 14, 2025, from <a href="https://open.leidenranking.com/resources">https://open.leidenranking.com/resources</a>
</div>
<div id="ref-LR_updates" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-e). <em><span class="nocase">Updates and corrections</span></em>. Retrieved November 14, 2025, from <a href="https://traditional.leidenranking.com/information/updates">https://traditional.leidenranking.com/information/updates</a>
</div>
<div id="ref-LROE_updates" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-f). <em><span class="nocase">Updates and corrections</span></em>. Retrieved November 14, 2025, from <a href="https://open.leidenranking.com/information/updates">https://open.leidenranking.com/information/updates</a>
</div>
<div id="ref-COKI_contact" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (n.d.-a). <em>Contact</em>. <a href="https://open.coki.ac/contact/">https://open.coki.ac/contact/</a>
</div>
<div id="ref-COKI_data" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (n.d.-b). <em>Data</em>. <a href="https://open.coki.ac/data/">https://open.coki.ac/data/</a>
</div>
<div id="ref-COKI_how" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (n.d.-c). <em>How it works</em>. <a href="https://open.coki.ac/how/">https://open.coki.ac/how/</a>
</div>
<div id="ref-COKI_dashboard" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (n.d.-d). <em>Open access dashboard</em>. <a href="https://open.coki.ac/">https://open.coki.ac/</a>
</div>
<div id="ref-QS_governance" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-a). <em>Good governance</em>. <a href="https://support.qs.com/hc/en-gb/articles/8575855263644-Good-Governance">https://support.qs.com/hc/en-gb/articles/8575855263644-Good-Governance</a>
</div>
<div id="ref-QS_optout" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-b). <em><span class="nocase">Opt-out policy</span></em>. <a href="https://support.qs.com/hc/en-gb/articles/360019107060-Opt-out-policy">https://support.qs.com/hc/en-gb/articles/360019107060-Opt-out-policy</a>
</div>
<div id="ref-QS_papers" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-c). <em>Paper counts - breakdown</em>. <a href="https://support.qs.com/hc/en-gb/articles/360019107160-Paper-Counts-breakdown">https://support.qs.com/hc/en-gb/articles/360019107160-Paper-Counts-breakdown</a>
</div>
<div id="ref-QS_paperdef" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-d). <em>Paper definitions</em>. <a href="https://support.qs.com/hc/en-gb/articles/360019156319-Paper-Definitions">https://support.qs.com/hc/en-gb/articles/360019156319-Paper-Definitions</a>
</div>
<div id="ref-QS_scopus" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-e). <em><span>QS Scopus User Guide</span></em>. <a href="https://support.qs.com/hc/en-gb/articles/4411497775506-QS-Scopus-User-Guide">https://support.qs.com/hc/en-gb/articles/4411497775506-QS-Scopus-User-Guide</a>
</div>
<div id="ref-QS_sustain" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-f). <em><span>QS World University Rankings: Sustainability</span></em>. <a href="https://support.qs.com/hc/en-gb/articles/8551503200668-QS-World-University-Rankings-Sustainability">https://support.qs.com/hc/en-gb/articles/8551503200668-QS-World-University-Rankings-Sustainability</a>
</div>
<div id="ref-SIR_method" class="csl-entry" role="listitem">
SCImago Research Group. (n.d.-a). <em>Ranking methodology</em>. <a href="https://www.scimagoir.com/methodology.php">https://www.scimagoir.com/methodology.php</a>
</div>
<div id="ref-SIR" class="csl-entry" role="listitem">
SCImago Research Group. (n.d.-b). <em><span>SCImago Institutions Ranking</span></em>. <a href="https://www.scimagoir.com/rankings.php">https://www.scimagoir.com/rankings.php</a>
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Information on the availability of data, including a link to download the version of the data used (if available), is provided for all rankings in the respective “Ranking Details” section.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>For example, in the SCImago Institutions Ranking, the <a href="https://www.scimagoir.com/institution.php?idp=21592">Deutsche Krebsforschungszentrum</a> is listed in the national language, while in ROR, the English name <a href="https://ror.org/04cdgtt98">German Cancer Research Center</a> is used as the primary designation.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Clicking on the figures enlarges them for better viewing.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Formally, <span class="citation" data-cites="Moed2016">Moed (<a href="#ref-Moed2016" role="doc-biblioref">2016</a>)</span> defines <em>preference</em> as: <span class="math inline">\(P= \dfrac{\bigg(\dfrac{n[i, j]}{\sum_i n[i, j]}\bigg)}{\bigg(\dfrac{\sum_jn[i, j]}{\sum_i\sum_jn[i, j]}\bigg)}\)</span>, where <span class="math inline">\(n[i, j]\)</span> represents the number of institutions from country <span class="math inline">\(i\)</span> in ranking system <span class="math inline">\(j\)</span>, <span class="math inline">\(\sum_in[i, j]\)</span> is the sum of all <span class="math inline">\(n[i, j]\)</span> across all <span class="math inline">\(i\)</span> (countries), <span class="math inline">\(\sum_jn[i, j]\)</span> is the sum of all <span class="math inline">\(n[i, j]\)</span> across all <span class="math inline">\(j\)</span> (ranking systems), and <span class="math inline">\(\sum_i\sum_jn[i, j]\)</span> is the sum of all <span class="math inline">\(n[i, j]\)</span> across all <span class="math inline">\(i\)</span> (countries) and all <span class="math inline">\(j\)</span> (ranking systems).<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section>
</div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oa-datenpraxis\.de\/en");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
       
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
<li class="nav-item">
    <a class="nav-link" href="./impressum.html">
<p><a href="https://www.hu-berlin.de/de/hu/impressum">Legal Notice</a></p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="./datenschutz.html">
<p>Privacy Statement</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://creativecommons.org/licenses/by/4.0/deed.en">
<p><iconify-icon role="img" inline="" icon="bxl:creative-commons" style="font-size: 1.5em;" aria-label="Icon creative-commons from bxl Iconify.design set." title="Icon creative-commons from bxl Iconify.design set."></iconify-icon><iconify-icon role="img" inline="" icon="humbleicons:creative-commons-by" style="font-size: 1.5em;" aria-label="Icon creative-commons-by from humbleicons Iconify.design set." title="Icon creative-commons-by from humbleicons Iconify.design set."></iconify-icon></p>
</a>
  </li>  
    <li class="nav-item">
 Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 4.0 International license.
  </li>  
</ul>
</div>
    <div class="nav-footer-right">
       
    </div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>
</body>
</html>
