website:
  page-footer: 
    center:
      - href: impressum.qmd
      - href: datenschutz.qmd
      - text: "{{< iconify bxl:creative-commons size=xl >}} {{< iconify humbleicons:creative-commons-by size=xl >}}"
        href: "https://creativecommons.org/licenses/by/4.0/deed.de"
      - text: "Sofern nicht anders angegeben, ist der Inhalt dieser Website unter einer Creative Commons Namensnennung 4.0 International Lizenz lizenziert."
  navbar:
    left:
      - text: "Über das Projekt"
        menu:
          - partners.qmd
          - arbeitspakete.qmd
      - href: publications.qmd
        text: "Publikationen"
      - text: "Veranstaltungen"
        menu:    
          - events.qmd
          - archive.qmd
      - text: "Ressourcen"
        menu:
          - dashboard_uebersicht.qmd
          - notebooks.qmd
          - materialsammlung.qmd
          
