project:
  type: website
  output-dir: docs

website:
  #reader-mode: true
  back-to-top-navigation: true
  #page-navigation: true
  margin-header: |
    ![](../images/logo_oa_datenpraxis.png)
  title: "OA Datenpraxis"
  navbar:
    logo: images/logo_oa_datenpraxis.png
    tools:
      - icon: mastodon
        href: https://openbiblio.social/@oa_datenpraxis
      - icon: envelope
        href: mailto:info.oa-datenpraxis@listserv.dfn.de
      - icon: github
        href: https://github.com/oa-datenpraxis/oa-datenpraxis.github.io
  search: false
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    #toc-location: left
    grid:
      sidebar-width: 50px
      body-width: 850px
      margin-width: 150px

babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: de
    text: "DE"
  - name: en
    text: "EN"
  mainlanguage: 'de'
  languages: ['en']

