website:
  navbar:
    left:
      - href: partners.qmd
        text: "Project Partners"
      - href: publications.qmd
        text: "Publications"
      - text: "Project Plan"
        menu: 
          - arbeitspakete.qmd
          #- toolbox.qmd
      - text: "News"
        menu:    
          - events.qmd
          - archive.qmd
