website:
  page-footer: 
    center:
      - href: impressum.qmd
      - href: datenschutz.qmd
      - text: "{{< iconify bxl:creative-commons size=xl >}} {{< iconify humbleicons:creative-commons-by size=xl >}}"
        href: "https://creativecommons.org/licenses/by/4.0/deed.de"
      - text: "Sofern nicht anders angegeben, ist der Inhalt dieser Website unter einer Creative Commons Namensnennung 4.0 International Lizenz lizenziert."
  navbar:
    left:
      - href: partners.qmd
        text: "Projektpartner"
      - href: publications.qmd
        text: "Publikationen"
      - text: "Projektvorhaben"
        menu: 
          - arbeitspakete.qmd
          #- toolbox.qmd
      - text: "Aktuelles"
        menu:    
          - events.qmd
          - archive.qmd
      - text: "OA Dashboards"
        menu:
          - dashboards.qmd
          - dashboards_schema.qmd
