website:
  page-footer: 
    center:
      - href: impressum.qmd
      - href: datenschutz.qmd
      - text: "{{< iconify bxl:creative-commons size=xl >}} {{< iconify humbleicons:creative-commons-by size=xl >}}"
        href: "https://creativecommons.org/licenses/by/4.0/deed.en"
      - text: "Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 4.0 International license."
  navbar:
    left:
      - href: partners.qmd
        text: "Project Partners"
      - href: publications.qmd
        text: "Publications"
      - text: "Project Plan"
        menu: 
          - arbeitspakete.qmd
      - text: "News"
        menu:    
          - events.qmd
          - archive.qmd
      - text: "OA Dashboards"
        menu:
          - uebersicht.qmd
          - dashboards.qmd
          - dashboards_schema.qmd

