---
title: "Archive"
---

## Past Events

### Open-Access-Tage 2025, 17--19 September 2025, Konstanz

#### [Workshop: Praktiken und Infrastrukturen des Open-Access-Monitorings](events/oat25_20250919.qmd)

### OA Datenpraxis Webinar Series

#### [28.03.2025: Erfassung von Publikationskosten an wissenschaftlichen Einrichtungen in Deutschland](events/webinar_20250328.qmd)

#### [04.04.2025: Open Metadata for University Rankings illustrated by the Leiden Ranking](events/webinar_20250404.qmd)

### 9th Library Congress, 18--19 June 2025, Bremen

#### [Hands-on Lab: Open-Access-Monitoring Dashboards mit Quarto](events/bid25_20250624.qmd)

#### [Presentation: Offene Metadaten als Bezugspunkt für die Verhandlung und Evaluierung von Open-Access-Transformationsverträgen](events/bid25_20250626.qmd)

#### [Presentation: Erfassung von Publikationskosten an wissenschaftlichen Einrichtungen in Deutschland](events/bid25_20250627.qmd)

### 25th DINI Annual Conference, 18--19 September 2024, Potsdam

#### [Transparenz in der Wissenschaft -- Strategien für offene Informationsversorgung](events/dini24_20240919.qmd)

### Open-Access-Tage 2024, 10--12 September 2024, Cologne

#### [Stand und Perspektive des Open-Access-Reportings](events/oat24_20240910.qmd)
