---
title: "Archiv"
---
 
## Vergangene Veranstaltungen

### OA Datenpraxis Webinarreihe

#### [14.04.2026: Open-Access-Reporting - Initiativen und Guidelines](events/webinar_20260414.qmd)

#### [27.03.2026: Open-Access-Reporting in der Praxis](events/webinar_20260327.qmd)

#### [04.04.2025: Offene Metadaten für Hochschulrankings am Beispiel des Leiden Ranking](events/webinar_20250404.qmd)

#### [28.03.2025: Erfassung von Publikationskosten an wissenschaftlichen Einrichtungen in Deutschland](events/webinar_20250328.qmd)

### openCost Konferenz, 17.--19. März 2026, Hamburg

#### [Poster: Recording Publication of Costs at Research Performing Organizations in Germany](events/occ26_20260318.qmd)

### Open-Access-Tage 2025, 17.--19. September 2025, Konstanz

#### [Workshop: Praktiken und Infrastrukturen des Open-Access-Monitorings](events/oat25_20250919.qmd)

### 9. Bibliothekskongress, 24.--27. Juni 2025, Bremen

#### [Hands-on Lab: Open-Access-Monitoring Dashboards mit Quarto](events/bid25_20250624.qmd)

#### [Vortrag: Offene Metadaten als Bezugspunkt für die Verhandlung und Evaluierung von Open-Access-Transformationsverträgen](events/bid25_20250626.qmd)

#### [Vortrag: Erfassung von Publikationskosten an wissenschaftlichen Einrichtungen in Deutschland](events/bid25_20250627.qmd)

### 25. DINI-Jahrestagung, 18.--19. September 2024, Potsdam

#### [Transparenz in der Wissenschaft -- Strategien für offene Informationsversorgung](events/dini24_20240919.qmd)

### Open-Access-Tage 2024, 10.--12. September 2024, Köln

#### [Stand und Perspektive des Open-Access-Reportings](events/oat24_20240910.qmd)
