---
title: "Open-Access-Dashboard Collection"
header-includes:
  - |
    <style>
    @media screen and (min-width: 1280px) {
      body .page-columns {
      display: inline-grid;
      gap: 0;
      grid-template-columns: [screen-start] 1.5em [screen-start-inset] 5fr [page-start page-start-inset] 7px [body-start-outset] 7px [body-start] 1.5em [body-content-start] minmax(1280px, calc(900px - 3em)) [body-content-end] 1.5em [body-end] 21px [body-end-outset] minmax(45px, 87px) [page-end-inset] 21px [page-end] 5fr [screen-end-inset] 1.5em [screen-end] !important;
      }
    }
    @media screen and (min-width: 1500px) {
      body .page-columns {
      display: inline-grid;
      gap: 0;
      grid-template-columns: [screen-start] 1.5em [screen-start-inset] 5fr [page-start page-start-inset] 7px [body-start-outset] 7px [body-start] 1.5em [body-content-start] minmax(1700px, calc(900px - 3em)) [body-content-end] 1.5em [body-end] 21px [body-end-outset] minmax(45px, 87px) [page-end-inset] 21px [page-end] 5fr [screen-end-inset] 1.5em [screen-end] !important;
      }
    }
    </style>
---

```{r, echo=FALSE, message=FALSE}
library(here)
library(DT)
library(readxl)
```

```{r, echo=FALSE, message=FALSE}
dashboards <- read_excel(here("files","Dashboards_Website.xlsx"))
```

```{r, echo=FALSE}
dashboards$URL <- ifelse(grepl("^https?://", dashboards$URL),
 paste0("<a href='", dashboards$URL, "' target='_blank'>", dashboards$URL, "</a>"),
 dashboards$URL)
dashboards$ROR <- ifelse(grepl("^https://ror.org/[0-9a-z]{9}$", dashboards$ROR),
 paste0("<a href='", dashboards$ROR, "' target='_blank'>", dashboards$ROR, "</a>"),
 ifelse(dashboards$ROR == "N/A", "N/A", dashboards$ROR))
#dashboards$ROR <- sapply(regmatches(dashboards$ROR, gregexpr("https://ror.org/[0-9a-z]{9}", dashboards$ROR)), function(url) paste0("<a href='", url, "' target='_blank'>", url, "</a>"))
datatable(dashboards,escape = FALSE,options = list(searchHighlight = TRUE, responsive = TRUE))
```