---
title: Metadata Schema
header-includes:
  - |
    <style>
    @media screen and (min-width: 1280px) {
      body .page-columns {
      display: inline-grid;
      gap: 0;
      grid-template-columns: [screen-start] 1.5em [screen-start-inset] 5fr [page-start page-start-inset] 7px [body-start-outset] 7px [body-start] 1.5em [body-content-start] minmax(1280px, calc(900px - 3em)) [body-content-end] 1.5em [body-end] 21px [body-end-outset] minmax(45px, 87px) [page-end-inset] 21px [page-end] 5fr [screen-end-inset] 1.5em [screen-end] !important;
      }
    }
    @media screen and (min-width: 1500px) {
      body .page-columns {
      display: inline-grid;
      gap: 0;
      grid-template-columns: [screen-start] 1.5em [screen-start-inset] 5fr [page-start page-start-inset] 7px [body-start-outset] 7px [body-start] 1.5em [body-content-start] minmax(1700px, calc(900px - 3em)) [body-content-end] 1.5em [body-end] 21px [body-end-outset] minmax(45px, 87px) [page-end-inset] 21px [page-end] 5fr [screen-end-inset] 1.5em [screen-end] !important;
      }
    }
    </style>
---

| ID  | Property          | Definition                                                                                                                                                                                                                                                                                                                                                                                                                                                          | Occ | Values                                                                                          | Example                                                                                             |
|-----|-------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----|-------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|
| 1   | Name              | name given to the dashboard by its authors, from (in descending priority): provided citation form, name given in associated publication, self-description on the website (header, ‘about' page, self-referring term throughout the website), browser tab name; year is removed from dashboard name if there are versions for multiple years; instances of dashboard collections are named after the scheme '[Name of dashboard collection]: [Name of organization]' | 1   |                                                                                                 | French Open Science Monitor, CWTS Leiden Ranking, OpenAIRE Monitor Dashboard: Universität Göttingen |
| 2   | URL               | URL to homepage of the dashboard; if listed dashboard is only one of other dashboard-unrelated services on a website, URL of the specific webpage                                                                                                                                                                                                                                                                                                                   | 1   |                                                                                                 | https://frenchopensciencemonitor.esr.gouv.fr/                                                       |
| 3   | Time period       | Time period in years from the year of earliest data presented in the dashboard to the year of latest data; Note: This is not the year of publication in the dashboard - ‘year of latest data’ earlier than 2024 does not necessarily mean the dashboard is inactive; the Leiden Ranking 2024 e.g. refers to data from 2019 - 2022                                                                                                                                   | 1-n | [year of common era] - [year of common era]                                                     | 2018 – 2024                                                                                         |
| 4   | Operator          | Name of operator responsible for running the dashboard; if that operator does not have an associated ROR, but there is an organization containing the operator that has a ROR, this organization is listed after the original operator, separated by comma; multiple direct operators are separated by semicolon.                                                                                                                                                   | 1-n |                                                                                                 | Centre for Science and Technology Studies (CWTS), Leiden University                                 |
| 4.1 | ROR               | ROR of the organization(s) listed under 4 if available, N/A if unavailable                                                                                                                                                                                                                                                                                                                                                                                          | 1-n | ROR ID as an operable URL, N/A                                                                  | https://ror.org/027bh9e22                                                                           |
| 4.2 | Operator type     | Type of organization running the dashboard, distinguishing two major types of research-related organizations, Research Performing and Funding Organizations ('RPO' and 'RFO' respectively), with `other' for everything else                                                                                                                                                                                                                                        | 1-n | Research performing organization (RPO), Research funding organization (RFO), other              | RPO                                                                                                 |
| 5.1 | Scope             | Scope of the coverage of dashboard: international if data for more than one country, national if data for one country, institutional if data on one or more organizations but not country-wide                                                                                                                                                                                                                                                                      | 1   | international, national, research institution                                                   | international                                                                                       |
| 5.2 | Countries         | Country code of the organization(s) whose data are represented in the dashboard, represented with country code value ‘Europe’ if more than 1 country but all from EU + Switzerland OR Norway OR UK value ‘global’ if more than 1 country and more than 3 countries outside of ‘Europe’                                                                                                                                                                              | 1-n | Controlled vocabulary: 3-letter ISO 3166-1 alpha-3 country code in addition: ‘Europe’, ‘global’ | DEU                                                                                                 |
| 6   | Data type         |  Type of data that the dashboard shows 'publications' for data on textual publications such as e.g. journal articles ‘data’ for research data ‘software’ for research software ‘infrastructures’ for data on e.g. repositories ‘other’ for data that does not fall under any of the other categories                                                                                                                                                                | 1-n | publications, data, software, infrustructures, other                                            | publications                                                                                        |
| 7   | Dashboard license | Copyright license of the software used to create the dashboard; if the dashboard provides a generic license for its website without specifically mentioning the software or its dataset, this license is instead entered here                                                                                                                                                                                                                                       | 1-n | controlled vocabulary: SPDX License List entries, N/A                                           | MIT, Apache-2.0                                                                                     |
| 8   | Data license      | Copyright license under which the data of the dashboard is published                                                                                                                                                                                                                                                                                                                                                                                                | 1-n | controlled vocabulary: SPDX License List entries, N/A                                           | CC-BY-4,0, CC0-1.0                                                                                  |
| 9   | Data source       | availability of the data source the dashboard is based on: ‘open’ if data comes from an open source such as e.g. OpenAlex, ‘proprietary’ if not, both values if dashboard uses data sources of both types                                                                                                                                                                                                                                                           | 1-n | open, proprietary, N/A                                                                          | open                                                                                                |
| 10  | Collection        | names the dashboard collection the dashboard is part of if applicable;  'N/A' otherwise                                                                                                                                                                                                                                                                                                                                                                             | 1   | string of the dashboard collection name, N/A                                                    | OpenAIRE Monitor Dashboard, CHORUS dashboard                                                        |
| 11  | Documentation     | free text field in which relevant links and comments are gathered; these can include: links to the specific part of the website where the various licenses are mentioned, DOIs to accompanying publications about the dashboard and other comments                                                                                                                                                                                                                  | 0-n |                                                                                                 |                                                                                                     |