---
title: "OA Dashboards"
---
## OA-Dashboard-Collection

Mit der wachsenden Bedeutung von Open Access stellt sich die Frage nach dem Anteil am Publikationsaufkommen von Forschungseinrichtungen, Ländern und auch auf globaler Ebene. Im Projekt OA Datenpraxis entwickeln wir eine Übersicht über Dashboards zu Open Access. 

Dafür haben wir eine Recherche zu relevanten Dashboards durchgeführt und ein eigenes Metadatenschema zur Indexierung erstellt. Im Mai 2025 haben wir einen Community-Prozess gestartet, um die Sammlung weiterzuentwickeln und auszubauen.

Sie finden die Open-Access-Dashboard-Collection [hier](dashboards.qmd) und das dazugehörige Metadatenschema [hier](dashboards_schema.qmd).

Falls Sie Änderungsvorschläge haben oder ein Dashboard haben, was hier noch nicht gelistet wird, schreiben Sie uns sehr gerne hier: [oa-datenpraxis-dashboards@listserv.dfn.de](mailto:oa-datenpraxis-dashboards@listserv.dfn.de)
Wir freuen uns über jeden Hinweis und tragen neue Dashboards ein.

Falls Sie selbst tätig werden wollen, finden Sie eine editierbare Version der Dashboard-Collection hier: 
[https://nextcloud.gfz.de/s/QG38J6kEDbJ8DXz](https://nextcloud.gfz.de/s/QG38J6kEDbJ8DXz) Dort können Sie neue Vorschläge selbst eintragen.




