---
title: "Datenschutz"
---

Personenbezogenen Daten werden über die Website weder automatisch noch manuell direkt gesammelt, gespeichert und verarbeitet.

Diese Website enthält jedoch Links oder Schaltflächen, die zu Diensten Dritter wie Mastodon oder E-Mail führen. Die Nutzung dieser Funktionen kann zu einer Datenerfassung führen. Wenn Sie auf diese Schaltflächen, Tools oder Inhalte zugreifen, werden möglicherweise automatisch bestimmte Browserinformationen an den Dienstanbieter gesendet. Bitte lesen Sie die Datenschutzerklärungen der Dienstanbieter für weitere Informationen.

Diese Website wird auf GitHub Pages gehostet. GitHub kann bei der Interaktion mit seinen Diensten personenbezogene Daten erfassen. Weitere Informationen finden Sie in der [GitHub-Datenschutzerklärung](https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement).

Weitere Informationen finden Sie auch in der [Datenschutzerklärung zu den Webseiten der Humboldt-Universität zu Berlin](https://www.hu-berlin.de/de/hu/impressum/datenschutzerklaerung).