---
title: "Notebooks"
language:
    toc-title-website: "Auf dieser Seite"
---

# [Open Access Cost Monitoring with OpenAPC](OpenAPC.qmd)

This notebook is a tool for library and information professionals dealing with cost monitoring in terms of Open Access publication output at their institution. It shows how to leverage the OpenAPC data set to collect and analyze cost information using R. No software installation or prior programming knowledge required. At the end of the notebook you will find some short excercises that can be executed directly in your browser. 

# [Open Access Monitoring with OpenAlex](OpenAlex.qmd)

This notebook is a tool for library and information professionals dealing with monitoring Open Access publication output at their institution. It shows how to leverage OpenAlex to retrieve and analyze publication data using R. No software installation or prior programming knowledge required. At the end of the notebook you will find some short excercises that can be executed directly in your browser.

# [Affiliation Search using ROR IDs](ROR.qmd)

This notebook serves as a tool for librarians and information professionals monitoring their institution's publication output. It compares ROR-based versus string-based search strategies in OpenAlex for retrieving publication data with R, accounting for institutional hierarchies (parent institutions and their child/related institutions) and demonstrating differences in publication coverage. No software installation or prior programming knowledge required.

