---
title: "Publikationen"
---

## Publikationen aus dem Projekt

## Vorarbeiten der Projektpartner

Fraser, N., Hobert, A., Jahn, N., Mayr, P., & Peters, I. (2023). No deal: German researchers’ publishing and citing behaviors after Big Deal negotiations with Elsevier. *Quantitative Science Studies*, *4*(2), 325–352. <https://doi.org/10.1162/qss_a_00255>

Hobert, A., Jahn, N., Mayr, P., Schmidt, B., & Taubert, N. (2021). Open access uptake in Germany 2010–2018: Adoption in a diverse research landscape. *Scientometrics*, *126*(12), 9751–9777. <https://doi.org/10.1007/s11192-021-04002-0>

Jahn, N. (2024). *How open are hybrid journals included in transformative agreements?* (arXiv:2402.18255). arXiv. <http://arxiv.org/abs/2402.18255>

Jahn, N., Matthias, L., & Laakso, M. (2022). Toward transparency of hybrid open access through publisher-provided metadata: An article-level study of Elsevier. *Journal of the Association for Information Science and Technology*, *73*(1), 104–118. <https://doi.org/10.1002/asi.24549>

Pampel, H. (2022). From library budget to information budget: Fostering transparency in the transformation towards open access. *Insights the UKSG journal*, *35*, 8. <https://doi.org/10.1629/uksg.576>

Taubert, N., Hobert, A., Jahn, N., Bruns, A., & Iravani, E. (2023). Understanding differences of the OA uptake within the German university landscape (2010–2020): Part 1—Journal-based OA. *Scientometrics*, *128*(6), 3601–3625. <https://doi.org/10.1007/s11192-023-04716-3>
