<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<link rel="alternate" hreflang="de" href="https://oa-datenpraxis.de/rankings.html" />
<link rel="alternate" hreflang="en" href="https://oa-datenpraxis.de/en/rankings.en.html" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Open Access in institutionellen Rankings – OA Datenpraxis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>
<script src="site_libs/quarto-nav/quarto-nav.js"></script><script src="site_libs/quarto-nav/headroom.min.js"></script><script src="site_libs/clipboard/clipboard.min.js"></script><script src="site_libs/quarto-html/quarto.js" type="module"></script><script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script><script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script><script src="site_libs/quarto-html/popper.min.js"></script><script src="site_libs/quarto-html/tippy.umd.min.js"></script><script src="site_libs/quarto-html/anchor.min.js"></script><link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script><link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f3966d63841dad6a94c94c7fab4e9718.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/iconify-2.1.0/iconify-icon.min.js"></script><script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script><link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="styles.css">
</head>
<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./images/logo_oa_datenpraxis.png" alt="" class="navbar-logo light-content"><img src="./images/logo_oa_datenpraxis.png" alt="" class="navbar-logo dark-content"></a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">OA Datenpraxis</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item"><div class="dropdown" id="languages-links-parent">
<button class="btn btn-primary dropdown-toggle babelquarto-languages-button" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="languages-button"><i class="bi bi-globe2"></i> DE</button><ul class="dropdown-menu" id="languages-links"><li><a class="dropdown-item" href="https://oa-datenpraxis.de/en/rankings.html" id="language-link-en">EN</a></li></ul>
</div></li>
<li class="nav-item">
    <a class="nav-link" href="./partners.html"> 
<span class="menu-text">Projektpartner</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./publications.html"> 
<span class="menu-text">Publikationen</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projektvorhaben" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projektvorhaben</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projektvorhaben">
<li>
    <a class="dropdown-item" href="./arbeitspakete.html">
 <span class="dropdown-text">Arbeitspakete</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-aktuelles" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Aktuelles</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-aktuelles">
<li>
    <a class="dropdown-item" href="./events.html">
 <span class="dropdown-text">Veranstaltungen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./archive.html">
 <span class="dropdown-text">Archiv</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-oa-dashboards" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">OA Dashboards</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-oa-dashboards">
<li>
    <a class="dropdown-item" href="./dashboard_uebersicht.html">
 <span class="dropdown-text">OA Dashboards Kontakt</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./dashboards.html">
 <span class="dropdown-text">Open-Access-Dashboard Collection</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./dashboards_schema.html">
 <span class="dropdown-text">Metadatenschema</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-notebooks" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Notebooks</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-notebooks">
<li>
    <a class="dropdown-item" href="./OpenAPC.html">
 <span class="dropdown-text">Open Access Cost Monitoring with OpenAPC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./OpenAlex.html">
 <span class="dropdown-text">Open Access Monitoring with OpenAlex</span></a>
  </li>  
    </ul>
</li>
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://openbiblio.social/@oa_datenpraxis" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-mastodon"></i></a>
    <a href="mailto:info.oa-datenpraxis@listserv.dfn.de" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-envelope"></i></a>
    <a href="https://github.com/oa-datenpraxis/oa-datenpraxis.github.io" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-margin-header"><div class="margin-header-item">
<p><a href="../images/logo_oa_datenpraxis.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="../images/logo_oa_datenpraxis.png" class="img-fluid"></a></p>
</div></div>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Open Access in institutionellen Rankings</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Institutionelle oder Hochschulrankings genießen eine hohe Aufmerksamkeit in Wissenschaftspolitik und Öffentlichkeit, weil es ihnen gelingt, wissenschaftliche Einrichtungen auf globaler Ebene übersichtlich miteinander zu vergleichen. Sie dienen verschiedenen Interessengruppen, wie politischen Entscheidungsträgern, Hochschulmanagern oder Studieninteressierten, unter anderem als Instrument zur strategischen Entscheidungsfindung, Veranschaulichung der institutionellen Exzellenz oder bei der Wahl des Studienorts <span class="citation" data-cites="Waltman2012">(<a href="#ref-Waltman2012" role="doc-biblioref">Waltman et al., 2012</a>)</span>. Die jeweilige Methodik, auf der die Rankings basieren, ist mitunter vielzähliger Kritikpunkte ausgesetzt, beispielsweise wegen ihrer Tendenz, mehrere Dimensionen des Leistungsspektrums wissenschaftlicher Einrichtungen zu einer einzigen, oft undurchsichtigen Punktzahl zusammenzufassen <span class="citation" data-cites="vanRaan2005 Piro2016 Diprose2023">(<a href="#ref-Diprose2023" role="doc-biblioref">Diprose et al., 2023</a>; <a href="#ref-Piro2016" role="doc-biblioref">Piro &amp; Sivertsen, 2016</a>; <a href="#ref-vanRaan2005" role="doc-biblioref">van Raan, 2005</a>)</span>. Dieser Ansatz erschwert nicht nur die Interpretation der Rankings, sondern berücksichtigt auch nicht hinreichend die unterschiedlichen Aufgaben und Prioritäten der Einrichtungen <span class="citation" data-cites="Waltman2012 Huang2020">(<a href="#ref-Huang2020" role="doc-biblioref">Huang, Neylon, Brookes-Kenworthy, et al., 2020</a>; <a href="#ref-Waltman2012" role="doc-biblioref">Waltman et al., 2012</a>)</span>.</p>
<p>In den letzten Jahren hat die Einbeziehung von Open-Access-Kennzahlen in Hochschulrankings an Bedeutung gewonnen. Open Access bezeichnet den freien und uneingeschränkten Online-Zugang zu Forschungsergebnissen <span class="citation" data-cites="Suber2012">(<a href="#ref-Suber2012" role="doc-biblioref">Suber, 2012</a>)</span> und ist zu einem wichtigen Indikator für das Engagement einer wissenschaftlichen Einrichtung für eine offene und transparante Wissenschaftspraxis geworden. Diese Entwicklung wird zusätzlich durch die Vorgaben von Förderorganisationen unterstützt, die Open Access zunehmend als Voraussetzung für die Forschungsförderung betrachten <span class="citation" data-cites="Wellcome_Trust NIH DFG Fournier2017 Huang2020a Ruecknagel2021">(<a href="#ref-DFG" role="doc-biblioref">Deutsche Forschungsgemeinschaft, 2025</a>; <a href="#ref-Fournier2017" role="doc-biblioref">Fournier, 2017</a>; <a href="#ref-Huang2020a" role="doc-biblioref">Huang, Neylon, Hosking, et al., 2020</a>; <a href="#ref-NIH" role="doc-biblioref">National Institutes of Health, 2024</a>; <a href="#ref-Ruecknagel2021" role="doc-biblioref">Rücknagel, 2021</a>; <a href="#ref-Wellcome_Trust" role="doc-biblioref">Wellcome, 2025</a>)</span>. Diese Vorgaben setzen neben dem Selbstverständnis vieler Einrichtungen einen zusätzlichen Anreiz Forschungsergebnisse im Open Access zugänglich zu machen. Die Integration von Open-Access-Kennzahlen in Hochschulrankings ermöglicht den Aktivitäten der Einrichtungen im Bereich Open Access Rechnung zu tragen und bietet eine zusätzliche Vergleichsdimension <span class="citation" data-cites="Diprose2023">(<a href="#ref-Diprose2023" role="doc-biblioref">Diprose et al., 2023</a>)</span>.</p>
<p>Es konnten fünf institutionelle Rankings mit Open Access als Vergleichsdimension identifiziert werden: das Leiden Ranking 2024 (LR), das Leiden Ranking Open Edition 2024 (LROE), das SCImago Institutions Ranking 2024 (SIR), das Quacquarelli Symonds World University Rankings: Sustainability 2025 (QS) und das COKI OA Dashboard 2025 (COKI). Alle fünf Rankings enthalten einen oder mehrere Open-Access-Indikatoren und sind hinsichtlich ihrer geografischen Abdeckung global ausgerichtet.</p>
<p>Diese Seite bietet eine Übersicht über die Charakteristika der fünf Rankings, sowie eine Untersuchung dazu, inwieweit die Ergebnisse der Rankings miteinander vergleichbar sind. Dies beinhaltet unter anderem einen Vergleich der von den Rankings verwendeten Datenquellen und Open-Access-Indikatoren, sowie eine Erhebung dazu, in welchem Umfang sich die Einrichtungen an der Datenerhebung durch die Rankinganbieter beteiligen können. Der Fokus liegt dabei insbesondere auf der Open-Access-Dimension.</p>
<section id="institutionellen-rankings-mit-open-access-als-vergleichsdimension" class="level2"><h2 class="anchored" data-anchor-id="institutionellen-rankings-mit-open-access-als-vergleichsdimension">Institutionellen Rankings mit Open Access als Vergleichsdimension</h2>
<p>Die folgenden Abschnitte beginnen mit einer Beschreibung der Kernmerkmale der ausgewählten Rankings. Am Ende jedes Abschnitts werden Details zu den Rankings in einem aufklappbaren Textkasten mit der Überschrift „Ranking-Details“ zusammengefasst. Dazu gehört insbesondere eine umfassende Liste der in jedem Ranking verwendeten Open-Access-Indikatoren.</p>
<section id="leiden-ranking" class="level3"><h3 class="anchored" data-anchor-id="leiden-ranking">Leiden Ranking</h3>
<p>Das Leiden Ranking wird seit 2007 jährlich vom Centre for Science and Technology Studies (CWTS) der Universität Leiden in den Niederlanden erstellt <span class="citation" data-cites="Waltman2012 LR_updates">(<a href="#ref-LR_updates" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-e</a>; <a href="#ref-Waltman2012" role="doc-biblioref">Waltman et al., 2012</a>)</span>. Das Ranking bietet keine klassische Rangliste, bei der eine Gesamtkennzahl berechnet wird, jedoch verschiedene bibliometrische Indikatoren entlang der Dimensionen <em>scientific impact</em>, <em>collaboration</em>, <em>Open Access</em> und <em>gender</em>. Die Indikatoren werden sowohl in größenabhängiger (absolute Zahlen) als auch in größenunabhängiger (relative Anteile) Form dargestellt, um Unterschiede in der Größe der Universitäten zu berücksichtigen. Das Ranking bietet auch Trendanalysen über Zeiträume und Stabilitätsintervalle, um statistische Unsicherheiten zu berücksichtigen <span class="citation" data-cites="LR_general LR_method">(<a href="#ref-LR_general" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-c</a>, <a href="#ref-LR_method" role="doc-biblioref">n.d.-a</a>)</span>.</p>
<p>Die Version 2024 des Leiden Ranking umfasst bibliometrische Daten für 1.506 Universitäten weltweit <span class="citation" data-cites="LR_method">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>)</span>. Indikatoren werden jeweils für Zeiträume von vier Jahren angegeben, die Version 2024 erweitert diese um den Zeitraum 2019–2022 <span class="citation" data-cites="LR_method">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>)</span>. Die bibliographischen Daten stammen aus dem Web of Science, wobei jedoch nur Artikel und Reviews berücksichtigt werden, die in internationalen wissenschaftlichen Zeitschriften veröffentlicht wurden <span class="citation" data-cites="LR_method">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>)</span>. Die Auswahl der Universitäten erfolgt auf der Grundlage ihrer Forschungsleistung, wobei diese mindestens 800 sogenannte <em>core publications</em> vorweisen müssen, um in das Ranking aufgenommen zu werden. Unter <em>core publications</em> werden Veröffentlichungen verstanden, die in internationalen wissenschaftlichen Zeitschriften in solchen Feldern veröffentlicht wurden, die für die Zitationsanalyse geeignet sind. Diese Publikationen müssen in englischer Sprache verfasst sein, mindestens eine:n Autor:in haben, dürfen nicht zurückgezogen (<em>retracted</em>) worden sein und müssen in einem sogenannten <em>core journal</em> erschienen sein. <em>core journals</em> zeichnen sich durch ihre internationale Ausrichtung aus und müssen in einem Feld angesiedelt sein, das für die Zitationsanalyse geeignet ist. Das Leiden Ranking verwendet keine Daten, die direkt von Universitäten stammen <span class="citation" data-cites="LR_method LR_general">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>, <a href="#ref-LR_general" role="doc-biblioref">n.d.-c</a>)</span>.</p>
<p>Ein wesentliches Merkmal des Leiden Ranking ist der Fokus auf Open-Access-Veröffentlichungen. Mit der Version 2019 des Rankings wurden Indikatoren zum Open-Access-Publizieren hinzugefügt <span class="citation" data-cites="LR_updates">(<a href="#ref-LR_updates" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-e</a>)</span>. Um den Open-Access-Status von Publikationen zu bestimmen, nutzt das Leiden Ranking OpenAlex als Datenquelle <span class="citation" data-cites="LR_method LR_general">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>, <a href="#ref-LR_general" role="doc-biblioref">n.d.-c</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 2024</p>
<p><strong>Website:</strong> <a href="https://www.leidenranking.com/" class="uri">https://www.leidenranking.com/</a></p>
<p><strong>Ersteller:</strong> <a href="https://www.universiteitleiden.nl/en/social-behavioural-sciences/cwts">Centre for Science and Technology Studies (CWTS)</a></p>
<p><strong>Ranking Typ:</strong> Hochschulranking</p>
<p><strong>Sektoren:</strong> Hochschulen</p>
<p><strong>Link zur Methodik:</strong> <a href="https://traditional.leidenranking.com/Content/CWTS%20Leiden%20Ranking%202024.pdf" class="uri">https://traditional.leidenranking.com/Content/CWTS%20Leiden%20Ranking%202024.pdf</a></p>
<p><strong>Datenquellen:</strong> Web of Science (Publikationen), OpenAlex (Open Access Status)</p>
<p><strong>Dimension mit Open Access Indikatoren (Gewichtung):</strong> Open Access</p>
<p><strong>Open Access Indikatoren (Gewichtung):</strong></p>
<ul>
<li>Gesamtzahl der Veröffentlichungen einer Universität</li>
<li>Anzahl und Anteil der Open-Access-Veröffentlichungen einer Universität</li>
<li>Anzahl und Anteil der Gold-Open-Access-Veröffentlichungen einer Universität</li>
<li>Anzahl und Anteil der Hybrid-Open-Access-Publikationen einer Universität</li>
<li>Die Anzahl und der Anteil der Bronze-Open-Access-Publikationen einer Universität</li>
<li>Die Anzahl und der Anteil der grünen Open-Access-Publikationen einer Universität</li>
<li>Die Anzahl und der Anteil der Publikationen einer Universität, deren Open-Access-Status unbekannt ist</li>
</ul>
<p><strong>Publikations-/Update-Rythmus:</strong> jährlich</p>
<p><strong>Anzahl an Institutionen:</strong> 1.506 Hochschulen</p>
<p><strong>Geographische Abdeckung:</strong> global</p>
<p><strong>Darstellung:</strong> Multi-Indikatoren Ranking</p>
<p><strong>Datenverfügbarkeit:</strong> Ergebnisdaten verfügbar unter CC-BY Lizenz: <span class="citation" data-cites="LR2024_data">Van Eck (<a href="#ref-LR2024_data" role="doc-biblioref">2024a</a>)</span></p>
</div>
</div>
</div>
</section><section id="leiden-ranking-open-edition" class="level3"><h3 class="anchored" data-anchor-id="leiden-ranking-open-edition">Leiden Ranking Open Edition</h3>
<p>Das Leiden Ranking Open Edition wird seit 2024 <span class="citation" data-cites="LROE2024">(<a href="#ref-LROE2024" role="doc-biblioref">Waltman et al., 2024</a>)</span> jährlich vom Centre for Science and Technology Studies (CWTS) der Universität Leiden in den Niederlanden erstellt. Es ist eine annähernde Reproduktion des traditionellen Leiden Ranking unter Nutzung offener Datenquellen <span class="citation" data-cites="LROE2024">(<a href="#ref-LROE2024" role="doc-biblioref">Waltman et al., 2024</a>)</span> und bietet ebenfalls keine klassische Rangliste, sondern verschiedene bibliometrische Indikatoren entlang der Dimensionen <em>scientific impact</em>, <em>collaboration</em>, und <em>Open Access</em>. Die Indikatoren werden in der Open Edition ebenfalls sowohl in größenabhängiger (absolute Zahlen) als auch in größenunabhängiger (relative Anteile) Form dargestellt, um Unterschiede in der Größe der Universitäten zu berücksichtigen. Die Open Edition des Leiden Ranking bietet zudem ebenfalls Trendanalysen über Zeiträume und Stabilitätsintervalle, um statistische Unsicherheiten zu berücksichtigen <span class="citation" data-cites="LROE_method LROE_updates">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>, <a href="#ref-LROE_updates" role="doc-biblioref">n.d.-f</a>)</span>.</p>
<p>Die Version 2024 des Leiden Ranking umfasst bibliometrische Daten für 1.506 Universitäten weltweit <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Indikatoren werden jeweils für Zeiträume von vier Jahren angegeben, die Version 2024 erweitert diese um den Zeitraum 2019–2022 <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Die bibliographischen Daten stammen aus OpenAlex, wobei jedoch nur sogenannte <em>core publications</em> berücksichtigt werden <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Im Vergleich zum traditionellen Leiden Ranking zählen in der Open Edition zusätzlich Publikationen vom Typ Buchkapitel, die in Buchreihen veröffentlicht wurden zu den <em>core publications</em>. Ferner müssen alle Publikationen nicht nur Autor:innenangaben, sondern auch Affiliationsangaben und Referenzen enthalten, um zu den <em>core publications</em> zu zählen. Alle anderen Kriterien für die <em>core publications</em> und <em>core journals</em> sind deckungsgleich zum traditionellen Leiden Ranking <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>.</p>
<p>Auch das Leiden Ranking Open Edition legt einen Fokus auf Open-Access-Veröffentlichungen und bietet weitestgehend die selben Open-Access-Indikatoren wie das traditionelle Leiden Ranking, mit Ausnahme der Indikatoren zu Publikationen mit unklarem Open-Access-Status <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Darüber hinaus weist das Leiden Ranking Open Edition die Besonderheit auf, dass auf der Weboberfläche die den Indikatoren zugrunde liegenden Publikationen einsehen werden können <span class="citation" data-cites="LROE2024a">(<a href="#ref-LROE2024a" role="doc-biblioref">van Eck, Waltman, et al., 2024</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 2024</p>
<p><strong>Website:</strong> <a href="https://www.open.leidenranking.com/" class="uri">https://www.open.leidenranking.com/</a></p>
<p><strong>Ersteller:</strong> <a href="https://www.universiteitleiden.nl/en/social-behavioural-sciences/cwts">Centre for Science and Technology Studies (CWTS)</a></p>
<p><strong>Ranking Typ:</strong> Hochschulranking</p>
<p><strong>Sektoren:</strong> Hochschulen</p>
<p><strong>Link zur Methodik:</strong> <a href="https://open.leidenranking.com/Content/CWTS%20Leiden%20Ranking%20Open%20Edition%202024.pdf" class="uri">https://open.leidenranking.com/Content/CWTS%20Leiden%20Ranking%20Open%20Edition%202024.pdf</a></p>
<p><strong>Datenquellen:</strong> OpenAlex</p>
<p><strong>Dimension mit Open Access Indikatoren (Gewichtung):</strong> Open Access</p>
<p><strong>Open Access Indikatoren (Gewichtung):</strong></p>
<ul>
<li>Gesamtzahl der Veröffentlichungen einer Universität</li>
<li>Anzahl und Anteil der Open-Access-Veröffentlichungen einer Universität</li>
<li>Anzahl und Anteil der Gold-Open-Access-Veröffentlichungen einer Universität</li>
<li>Anzahl und Anteil der Hybrid-Open-Access-Publikationen einer Universität</li>
<li>Die Anzahl und der Anteil der Bronze-Open-Access-Publikationen einer Universität</li>
<li>Die Anzahl und der Anteil der grünen Open-Access-Publikationen einer Universität</li>
</ul>
<p><strong>Publikations-/Update-Rythmus:</strong> jährlich</p>
<p><strong>Anzahl an Institutionen:</strong> 1.506 Hochschulen</p>
<p><strong>Geographische Abdeckung:</strong> global</p>
<p><strong>Darstellung:</strong> Multi-Indikatoren Ranking</p>
<p><strong>Datenverfügbarkeit:</strong> Rohdaten und Ergebnisdaten verfügbar unter CC0 Lizenz:</p>
<ul>
<li>Rohdaten: <span class="citation" data-cites="LROE2024_raw">Van Eck (<a href="#ref-LROE2024_raw" role="doc-biblioref">2024b</a>)</span>
</li>
<li>Ergebnisdaten: <span class="citation" data-cites="LROE2024_results">Van Eck (<a href="#ref-LROE2024_results" role="doc-biblioref">2024c</a>)</span>
</li>
</ul>
</div>
</div>
</div>
</section><section id="scimago-institutions-ranking" class="level3"><h3 class="anchored" data-anchor-id="scimago-institutions-ranking">SCImago Institutions Ranking</h3>
<p>Das SCImago Institutions Ranking wird seit 2009 jährlich von der SCImago Research Group erstellt <span class="citation" data-cites="Rousseau2018">(<a href="#ref-Rousseau2018" role="doc-biblioref">Rousseau et al., 2018</a>)</span>. Das Ranking bietet eine klassische Rangliste (league table) von wissenschaftlichen und forschungsnahen Einrichtungen anhand eines zusammengesetzten Indikators auf einer Skala zwischen 0 und 100. Der zusammengesetzte Indikator kombiniert Bewertungen entlang dreier Dimensionen: Forschung, Innovation und gesellschaftliche Wirkung. Der zusammengesetzte Indikator ergibt sich aus einer gewichtete Kombination von Metriken entlang dieser Dimensionen, wobei sowohl größenabhängige als auch größenunabhängige Metriken verwendet werden. Für jede Einrichtung bietet das Ranking zusätzlich noch eine Reihe von Grafiken beispielsweise zu der Rangentwicklung über die Zeit, Vergleichen auf nationaler, regionaler oder globaler Ebene, oder ähnlichen Institutionen gemäß des Publikationsprofils <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>.</p>
<p>Die Version 2025 des SCImago Institutions Ranking umfasst Daten für 9.756 Institutionen weltweit <span class="citation" data-cites="SIR">(<a href="#ref-SIR" role="doc-biblioref">SCImago Research Group, n.d.-b</a>)</span>. Der zusammengesetzte Indikator wird pro Jahr für einen Zeitraum von fünf Jahren bis zwei Jahre vor Veröffentlichung des Rankings angegeben, für die Version 2025 also für den Zeitraum 2019–2023. Die bibliographischen Daten stammen aus Scopus. Die Auswahl der Institutionen erfolgt auf der Grundlage ihrer Veröffentlichungsleistung. Im letzten Jahr des betrachteten Zeitraums müssen die Institutionen mindestens 100 in Scopus indexierte Publikationen veröffentlicht haben, um in das Ranking aufgenommen zu werden. Ferner müssen mindestens 75% des gesamten Publikationsvolumens einer Einrichtung sogenannte zitierfähige Dokumente ausmachen. Zu den zitierfähigen Dokumenten werden für das SCImago Institutions Ranking die Publikationstypen Artikel, Buchkapitel, Konferenzbeiträge, Reviews und Short Surveys gezählt <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>.</p>
<p>Innerhalb der Forschungsdimension, die mit 50% in den zusammengesetzten Indikator einfließt, wurde mit der Version 2019 ein Open-Access-Indikator dem Ranking hinzugefügt. Dieser geht mit 2% Gewichtung in die Forschungsdimension ein und misst den Prozentsatz der Dokumente, die in Open-Access-Zeitschriften veröffentlicht wurden oder in Unpaywall indexiert sind. Um den Open-Access-Status von Publikationen zu bestimmen, nutzt das SCImago Institutions Ranking Unpaywall als Datenquelle <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 2025</p>
<p><strong>Website:</strong> <a href="https://www.scimagoir.com/" class="uri">https://www.scimagoir.com/</a></p>
<p><strong>Ersteller:</strong> <a href="https://www.scimagolab.com/">SCImago Research Group</a></p>
<p><strong>Ranking Typ:</strong> Institutionenranking</p>
<p><strong>Sektoren:</strong> Behörden, Hochschulen, Unternehmen, Gesundheitsorganisationen, Non-Profit Organisationen</p>
<p><strong>Link zur Methodik:</strong> <a href="https://www.scimagoir.com/methodology.php" class="uri">https://www.scimagoir.com/methodology.php</a></p>
<p><strong>Datenquellen:</strong> Scopus (Publikationen), Unpaywall (Open Access Status)</p>
<p><strong>Dimension mit Open Access Indikatoren (Gewichtung):</strong> Research (50%)</p>
<p><strong>Open Access Indikatoren (Gewichtung):</strong> Prozentualer Anteil der Dokumente, die in Open-Access-Zeitschriften veröffentlicht oder in Unpaywall indexiert sind (2%)</p>
<p><strong>Publikations-/Update-Rythmus:</strong> jährlich</p>
<p><strong>Anzahl an Institutionen:</strong> 9.756 Hochschulen und forschungsnahe Einrichtungen</p>
<p><strong>Geographische Abdeckung:</strong> global</p>
<p><strong>Darstellung:</strong> Rangliste (league table)</p>
<p><strong>Datenverfügbarkeit:</strong> Ergebnisdaten verfügbar über die Ranking Website, keine Lizenzangabe: <a href="https://www.scimagoir.com/rankings.php" class="uri">https://www.scimagoir.com/rankings.php</a></p>
</div>
</div>
</div>
</section><section id="qs-sustainability-ranking" class="level3"><h3 class="anchored" data-anchor-id="qs-sustainability-ranking">QS Sustainability Ranking</h3>
<p>Das QS World University Rankings: Sustainability wird seit 2023 jährlich von Quacquarelli Symonds erstellt, nachdem bereits 2022 eine Pilotversion veröffentlicht wurde <span class="citation" data-cites="QS_date">(<a href="#ref-QS_date" role="doc-biblioref">Quacquarelli Symonds, 2024</a>)</span>. Das Ranking bietet eine klassische Rangliste (league table) von Hochschulen anhand eines zusammengesetzten Indikators sowohl für die einzelnen Kategorien und Unterkategorien (<em>Lenses</em>), als auch eine Gesamtpunktzahl. Dabei werden die kategorialen Punktzahlen für alle bewerteten Institutionen angezeigt, während die Gesamtpunktzahlen nur bis zu einem bestimmten Punkt angezeigt und danach ausgeblendet werden <span class="citation" data-cites="QS_scores">(<a href="#ref-QS_scores" role="doc-biblioref">Quacquarelli Symonds, n.d.-a</a>)</span>. Das QS World University Rankings: Sustainability bewertet Institutionen entlang dreier Dimensionen: <em>Environmental Impact</em>, <em>Social Impact</em>, und <em>Governance</em>.</p>
<p>Die Version 2025 des QS World University Rankings: Sustainability umfasst Daten für 1.744 Hochschulen weltweit <span class="citation" data-cites="QS_date">(<a href="#ref-QS_date" role="doc-biblioref">Quacquarelli Symonds, 2024</a>)</span>. Die bibliographischen Daten stammen aus Scopus und bilden einen 5-jahres Zeitraum ab <span class="citation" data-cites="QS_papers">(<a href="#ref-QS_papers" role="doc-biblioref">Quacquarelli Symonds, n.d.-d</a>)</span>. Es werden dabei ausschließlich die Publikationstypen Artikel, Review, Konferenzbeitrag, Buch, Buchkapitel, Article in Press und Business Article berücksichtigt <span class="citation" data-cites="QS_paperdef QS_scopus">(<a href="#ref-QS_paperdef" role="doc-biblioref">Quacquarelli Symonds, n.d.-e</a>, <a href="#ref-QS_scopus" role="doc-biblioref">n.d.-f</a>)</span>. Institutionen werden nur in das QS World University Rankings: Sustainability aufgenommen, wenn sie einerseits Eignungskriterien für die Aufnahme in mindestens eines der Rankings <em>QS World University Rankings</em>, <em>QS Rankings by Region</em> oder <em>QS Rankings by Subject</em> erfüllen und zusätzlich noch eine Punktzahl ungleich Null für spezifische Indikatoren innerhalb der <em>Environmental Impact</em> und <em>Social Impact</em> erreichen <span class="citation" data-cites="QS_sustain">(<a href="#ref-QS_sustain" role="doc-biblioref">Quacquarelli Symonds, n.d.-g</a>)</span>.</p>
<p>Innerhalb der <em>Governance</em>-Dimension, die mit 10% in die Gesamtpunktzahl einfließt, bildet ein Indikator Open-Access-Publikationen ab. Dieser geht mit 1% Gewichtung in die <em>Governance</em>-Dimension ein und misst den Anteil an Open-Access-Publikationen am gesamten Publikationvolumen. Der Anteil wird einzeln für die sechs berücksichtigten Felder berechnet und zu einer gewichteten Summe aggregiert. Gold- und Hybrid-Publikationen werden bei der Berechnung stärker gewichtet als Publikationen, die über den grünen Open-Access-Weg veröffentlicht wurden. Um den Open-Access-Status von Publikationen zu bestimmen, nutzt das QS World University Rankings: Sustainability Unpaywall als Datenquelle <span class="citation" data-cites="QS_governance">(<a href="#ref-QS_governance" role="doc-biblioref">Quacquarelli Symonds, n.d.-b</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 2025</p>
<p><strong>Website:</strong> <a href="https://www.topuniversities.com/sustainability-rankings" class="uri">https://www.topuniversities.com/sustainability-rankings</a></p>
<p><strong>Ersteller:</strong> <a href="https://www.qs.com/">Quacquarelli Symonds Ltd.</a></p>
<p><strong>Ranking Typ:</strong> Hochschulranking</p>
<p><strong>Sektoren:</strong> Hochschulen</p>
<p><strong>Link zur Methodik:</strong> <a href="https://support.qs.com/hc/en-gb/articles/8551503200668-QS-World-University-Rankings-Sustainability" class="uri">https://support.qs.com/hc/en-gb/articles/8551503200668-QS-World-University-Rankings-Sustainability</a></p>
<p><strong>Datenquellen:</strong> Scopus (Publikationen), Unpaywall (Open Access Status)</p>
<p><strong>Dimension mit Open Access Indikatoren (Gewichtung):</strong> Governance (10%)</p>
<p><strong>Open Access Indikatoren (Gewichtung):</strong> Der Anteil der gesamten Forschungsergebnisse einer Einrichtung, die laut Unpaywall als Open Access verfügbar sind (1%)</p>
<p><strong>Publikations-/Update-Rythmus:</strong> jährlich</p>
<p><strong>Anzahl an Institutionen:</strong> 1.744 Hochschulen</p>
<p><strong>Geographische Abdeckung:</strong> global</p>
<p><strong>Darstellung:</strong> Rangliste (league table)</p>
<p><strong>Datenverfügbarkeit:</strong> Ergebnisdaten verfügbar über die Ranking Website nach Registrierung, keine Lizenzangabe: <a href="https://www.topuniversities.com/sustainability-rankings" class="uri">https://www.topuniversities.com/sustainability-rankings</a></p>
</div>
</div>
</div>
</section><section id="coki-oa-dashboard" class="level3"><h3 class="anchored" data-anchor-id="coki-oa-dashboard">COKI OA Dashboard</h3>
<p>Das COKI Open Access Dashboard wird seit 2022 von der Curtin Open Knowledge Intitiative erstellt <span class="citation" data-cites="COKI_date COKI_newsletter">(<a href="#ref-COKI_date" role="doc-biblioref">Curtin Open Knowledge Initiative, 2022</a>; <a href="#ref-COKI_newsletter" role="doc-biblioref">Curtin Open Knowledge Initiative &amp; Wilson, 2022</a>)</span>. Das Dashboard ist kein klassisches Ranking, jedoch lassen sich Institutionen und Länder nach dem Open Access Anteil sowie den gesamten und Open-Access-Publikationsvolumina sortieren <span class="citation" data-cites="COKI_date">(<a href="#ref-COKI_date" role="doc-biblioref">Curtin Open Knowledge Initiative, 2022</a>)</span>. Das Dashboard zeigt ferner für die einzelnen Länder und Institutionen an, über welche Plattform die Open-Access-Veröffentlichungen verfügbar gemacht werden, sowohl aggregiert über den gesamten Publikationszeitraum, als auch aufgeschlüsselt für die einzelnen Publikationsjahre <span class="citation" data-cites="COKI_date">(<a href="#ref-COKI_date" role="doc-biblioref">Curtin Open Knowledge Initiative, 2022</a>)</span>.</p>
<p>Die Version vom 18.08.2025 des COKI Open Access Dashboard umfasst Daten für 227 Länder und 56.187 Institutionen weltweit <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>. Die bibliographischen Daten stammen aus mehreren offenen Datenquellen und berücksichtigen den Publikationszeitraum 2000–2024, zur Identifikation von Publikationen wird insbesondere Crossref genutzt <span class="citation" data-cites="COKI_how COKI_dashboard">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>, <a href="#ref-COKI_dashboard" role="doc-biblioref">n.d.-d</a>)</span>. Die Auswahl der Publikationstypen ist im Vergleich zu den anderen Rankings weniger restriktiv, ausgeschlossen werden lediglich Publikationen mit den Typen Datensätze, Datenbanken, Komponenten, Berichtskomponenten, Peer Reviews, Fördermittel, Tagungsbände, Zeitschriftenausgaben, Berichtsreihen, Buchverzeichnisse, sowie alle Publikationen ohne angegebenen Publikationstyp <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>. Institutionen müssen mindestens 50 Publikationen aufweisen, um in das COKI Open Access Dashboard aufgenommen zu werden, es sei denn, die Institutionen waren bereits im Datensatz aufgenommen, als dieser noch auf Microsoft Academic Graph basierte <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>.</p>
<p>Das COKI Open Access Dashboard legt den Fokus ausschließlich auf Open-Access-Aktivitäten der Institutionen und Länder. Während in der Listenansicht vorwiegend die absolute Anzahl sowie den prozentuale Anteil an Open-Access-Veröffentlichungen dargestellt wird, zeigen Detailansichten zu einzelnen Institutionen und Ländern differenziertere Aufschlüsselungen zu Publikationsaktivitäten und -orten, ergänzt durch Visualisierungen <span class="citation" data-cites="COKI_dashboard">(<a href="#ref-COKI_dashboard" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-d</a>)</span>. Um den Open-Access-Status von Publikationen zu bestimmen, nutzt das COKI Open Access Dashboard Unpaywall als Datenquelle <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ranking Details
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Version:</strong> 18.08.2025</p>
<p><strong>Website:</strong> <a href="https://open.coki.ac/" class="uri">https://open.coki.ac/</a></p>
<p><strong>Ersteller:</strong> <a href="https://openknowledge.community/">Curtin Open Knowledge Initiative</a></p>
<p><strong>Ranking Typ:</strong> Länder- und Institutionen-Ranking</p>
<p><strong>Sektoren:</strong> Förderorganisationen, Behörden, Hochschulen, Unternehmen, Gesundheitsorganisationen, Non-Profit Organisationen, Infrastrukturorganisationen, Archive, Sonstige</p>
<p><strong>Link zur Methodik:</strong> <a href="https://open.coki.ac/how/" class="uri">https://open.coki.ac/how/</a></p>
<p><strong>Datenquellen:</strong> Crossref (Publikationen), Unpaywall (Open Access Status)</p>
<p><strong>Dimension mit Open Access Indikatoren (Gewichtung):</strong> –</p>
<p><strong>Open Access Indikatoren (Gewichtung):</strong></p>
<ul>
<li>Prozentualer Anteil an Open Access Veröffentlichungen</li>
<li>Gesamtanzahl der Veröffentlichungen</li>
<li>Gesamtanzahl an Open Access Veröffentlichungen</li>
<li>Prozentualer Anteil an Artikeln, die über den Verlag Open Access zugänglich sind</li>
<li>Prozentualer Anteil an Artikeln, die über andere Platformen Open Access zugänglich sind (Repositorien, Preprint-Server, etc.)</li>
<li>Prozentualer Anteil an Artikeln, die sowohl über den Verlag, als auch über andere Platformen Open Access zugänglich sind</li>
<li>Prozentualer Anteil an Closed Artikeln</li>
<li>Prozentualer Anteil an Artikeln, die in einer Open Access Zeitschrift veröffentlicht wurden</li>
<li>Prozentualer Anteil an Artikeln, die in einer Hybrid Zeitschrift</li>
<li>Prozentualer Anteil an Artikeln, die über den Verlag ohne Wiederverwendungsrechte Open Access sind</li>
<li>Prozentualer Anteil an Artikeln, die über institutionelle Repositorien Open Access sind</li>
<li>Prozentualer Anteil an Artikeln, die über Preprint Server Open Access sind</li>
<li>Prozentualer Anteil an Artikeln, die über Fachrepositorien Open Access sind</li>
<li>Prozentualer Anteil an Artikeln, die über anderweitige, öffentliche Repositorien Open Access sind</li>
<li>Prozentualer Anteil an Artikeln, die über anderweitige Webseiten oder Portale Open Access sind</li>
</ul>
<p><strong>Publikations-/Update-Rythmus:</strong> regelmäßig</p>
<p><strong>Anzahl an Institutionen:</strong> 56.187 Institutionen</p>
<p><strong>Geographische Abdeckung:</strong> global</p>
<p><strong>Darstellung:</strong> Multi-Indikatoren Dashboard</p>
<p><strong>Datenverfügbarkeit:</strong> Ergebnisdaten verfügbar über die Ranking Website unter CC-BY Lizenz: <span class="citation" data-cites="COKI2025_07_21">Hosking et al. (<a href="#ref-COKI2025_07_21" role="doc-biblioref">2025</a>)</span></p>
</div>
</div>
</div>
</section></section><section id="vergleichbarkeit-der-ranking-ergebnisse" class="level2 page-columns page-full"><h2 class="anchored" data-anchor-id="vergleichbarkeit-der-ranking-ergebnisse">Vergleichbarkeit der Ranking-Ergebnisse</h2>
<p>Um zu beurteilen, wie vergleichbar die Ergebnisse der ausgewählten Rankings sind, konzentrieren sich die nachfolgenden Abschnitte auf die Überprüfung folgender Aspekte: die von den Rankings verwendeten Datenquellen, die von den Rankings verwendeten Open-Access-Indikatoren und deren Gewichtung, die Anzahl der in allen Rankings vertretenen Institutionen, die geografische Verteilung der Institutionen über Länder und Weltregionen hinweg sowie die Möglichkeit der institutionellen Beteiligung am Datenerhebungsprozess der Ranking-Anbieter.</p>
<p>Es soll dabei herausgearbeitet werden, inwiefern sich die einzelnen Rankingsysteme unterscheiden und welche Auswirkungen dies mitunter für die Nutzung eines bestimmten Rankings bei Open-Access-Monitoringaktivitäten oder der strategischen Entscheidungsfindung haben kann.</p>
<section id="datenquellen" class="level3 page-columns page-full"><h3 class="anchored" data-anchor-id="datenquellen">Datenquellen</h3>
<p>In diesem Abschnitt werden die von den fünf Rankings verwendeten Datenquellen untersucht, wobei der Fokus auf folgenden zwei Kategorien von Datenquellen liegt: zum einen Datenquellen, die zur Erhebung bibliografischer Daten verwendet werden, und zum anderen Datenquellen, die zur Bestimmung des Open-Access-Status herangezogen werden. Unterschiede in der Abdeckung, Vollständigkeit und Methodik dieser Datenquellen können zu Abweichungen bei der Berechnung von Metriken führen und somit die Vergleichbarkeit der Ergebnisse unterschiedlicher Rankings einschränken. Ferner wird untersucht, ob sich aufgrund der verwendeten Datenquellen disziplinäre Unterschiede zwischen den Rankings ergeben.</p>
<section id="bibliographische-datenquellen" class="level4"><h4 class="anchored" data-anchor-id="bibliographische-datenquellen">Bibliographische Datenquellen</h4>
<div id="tbl-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle 1: Verwendete Datenquellen für die Erhebung bibliographischer Daten
</figcaption><div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: left;">Ranking</th>
<th style="text-align: center;">Web of Science</th>
<th style="text-align: center;">Scopus</th>
<th style="text-align: center;">OpenAlex</th>
<th style="text-align: center;">Crossref</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Leiden Ranking</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Leiden Ranking Open Edition</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCImago Institutions Ranking</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">QS Sustainability Ranking</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">COKI OA Dashboard</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section><section id="open-access-datenquellen" class="level4"><h4 class="anchored" data-anchor-id="open-access-datenquellen">Open-Access-Datenquellen</h4>
<div id="tbl-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle 2: Verwendete Datenquellen für die Bestimmung des Open-Access-Status
</figcaption><div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: left;">Ranking</th>
<th style="text-align: center;">Unpaywall</th>
<th style="text-align: center;">OpenAlex</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Leiden Ranking</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leiden Ranking Open Edition</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SCImago Institutions Ranking</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">QS Sustainability Ranking</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">COKI OA Dashboard</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section><section id="disziplinäre-unterschiede" class="level4 page-columns page-full"><h4 class="anchored" data-anchor-id="disziplinäre-unterschiede">Disziplinäre Unterschiede</h4>
<div class="column-page">
<div id="fig-fields" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-fields-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe width="1040" height="560" src="https://app.powerbi.com/view?r=eyJrIjoiZmI0YzljYjYtYWZlNy00YzUzLWE1YjYtYjdkNmYwMDUzNjFmIiwidCI6ImNhMmE3Zjc2LWRiZDctNGVjMC05MTA4LTZiM2Q1MjRmYjdjOCIsImMiOjh9"></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fields-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung 1: Disziplinäre Unterschiede zwischen dem traditionellen Leiden Ranking 2024 und dem Leiden Ranking Open Edition 2024 (Quelle: <a href="https://app.powerbi.com/view?r=eyJrIjoiZmI0YzljYjYtYWZlNy00YzUzLWE1YjYtYjdkNmYwMDUzNjFmIiwidCI6ImNhMmE3Zjc2LWRiZDctNGVjMC05MTA4LTZiM2Q1MjRmYjdjOCIsImMiOjh9">Open Dashboard 2024</a>, <span class="citation" data-cites="LROE_resources">(<a href="#ref-LROE_resources" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-d</a>)</span>)
</figcaption></figure>
</div>
</div>
</section></section><section id="open-access-indikatoren" class="level3"><h3 class="anchored" data-anchor-id="open-access-indikatoren">Open-Access-Indikatoren</h3>
<p>Innerhalb der evaluativen Bibliometrie konzentrieren sich sogenannte Produktivitätsindikatoren auf die Auszählung von Publikationsvolumina, um die Produktivität von Einzelpersonen, Institutionen oder Ländern zu quantifizieren <span class="citation" data-cites="Gauch2023">(<a href="#ref-Gauch2023" role="doc-biblioref"><strong>Gauch2023?</strong></a>)</span>. Open-Access-Indikatoren lassen sich in diesem Zusammenhang als eine Form von Produktivitätsindikatoren verstehen, da sie meist die Anzahl an Open-Access-Publikationen auszählen und daraus ein approximierendes Maß für die Produktivität von Forschenden, Institutionen oder Ländern im Bereich Open Access generieren.</p>
<p>Aus einer guten bibliometrischen Praxis heraus, wie sie etwa im Leiden Manifest <span class="citation" data-cites="Hicks2015">(<a href="#ref-Hicks2015" role="doc-biblioref"><strong>Hicks2015?</strong></a>)</span> umrissen ist, erfordert die Auswahl der im Kontext von Rankings verwendeten Indikatoren sorgfältige Überlegungen bezüglich deren Eignung für den Vergleich von Institutionen. Ein Vergleich zwischen Einrichtungen aus unterschiedlichen regionalen Kontexten oder mit unterschiedlicher Anzahl an Forschenden und Publikationsvolumina kann problematisch sein, wenn die Indikatoren lediglich absolute Anzahlen an Publikationen darstellen, da die spezifischen Bedingungen und Herausforderungen jeder Einrichtung nicht berücksichtigt werden. Um eine bessere Vergleichbarkeit zwischen Einrichtungen zu schaffen, finden daher bei der Indikatorenkonstruktion verschiedene Formen der Normalisierung Anwendung <span class="citation" data-cites="Gauch2023">(<a href="#ref-Gauch2023" role="doc-biblioref"><strong>Gauch2023?</strong></a>)</span>. Eine Form der Normalisierung in Bezug auf Open-Access-Indikatoren kann sein, die absolute Anzahl der Open-Access-Publikationen einer Einrichtung ins Verhältnis zu setzen zur absoluten Anzahl aller Publikationen einer Einrichtung im untersuchten Zeitraum.</p>
<p>Neben einzelnen Indikatoren, werden auch sogenannte zusammengesetze Indikatoren (<em>composite indicators</em>) für einige Rankings verwendet, die als Rangliste angelegt sind. Diese Indikatoren werden aus gewichteten Aggregaten von einzelnen Indikatoren generiert <span class="citation" data-cites="Glaenzel2009 Johnes2018">(<a href="#ref-Glaenzel2009" role="doc-biblioref"><strong>Glaenzel2009?</strong></a>; <a href="#ref-Johnes2018" role="doc-biblioref"><strong>Johnes2018?</strong></a>)</span>. Die Idee hinter zusammengesetzten Indikatoren besteht darin, komplexe Phänomene wissenschaftlicher Aktivitäten durch die Kombination und Verdichtung verschiedener Indikatoren zu einem einzigen, umfassenden Maß abzubilden. Durch diese Art der Linearisierung in eine einzelne Metrik, die sich sortieren lässt, ermöglichen zusammengesetze Indikatoren eine einfachere Vergleichbarkeit zwischen Einrichtungen, Personen oder Ländern <span class="citation" data-cites="quick_notes">(<a href="#ref-quick_notes" role="doc-biblioref"><strong>quick_notes?</strong></a>)</span>. Dennoch gehen gewisse Problematiken mit zusammengesetzten Indikatoren einher, eine gute Übersicht findet sich bei <span class="citation" data-cites="Forthmann2024">(<a href="#ref-Forthmann2024" role="doc-biblioref"><strong>Forthmann2024?</strong></a>)</span>. Zu den Problematiken und Kritikpunkten gehören beispielsweise, dass die Auswahl der Gewichtung einzelner Komponenten bei zusammengesetzen Indikatoren oft undurchsichtig und teils willkürlich erfolgt. Dabei haben die Gewichte der Einzelkomponenten einen beachtlichen Einfluss auf das resultierende Ranking <span class="citation" data-cites="Glaenzel2009 Forthmann2024">(<a href="#ref-Glaenzel2009" role="doc-biblioref"><strong>Glaenzel2009?</strong></a>; <a href="#ref-Forthmann2024" role="doc-biblioref"><strong>Forthmann2024?</strong></a>)</span>. Ferner wird auch kritisiert, dass es oft an hinreichender Transparenz bezüglich der Indikatorenkonstruktion mangelt, was die Interpretation der Rankings erschweren kann <span class="citation" data-cites="Forthmann2024">(<a href="#ref-Forthmann2024" role="doc-biblioref"><strong>Forthmann2024?</strong></a>)</span>.</p>
<p>Beide Versionen des Leiden Rankings bieten im Kern zwei Arten von Open-Access-Indikatoren: 1) Indikatoren, die das Gesamtpublikationsvolumen an Open-Access-Publikationen einer Hochschule über einen vier-Jahreszeitraum ausweisen und 2) Indikatoren, die den Anteil des Open-Access-Publikationsvolumens am Gesamtpublikationsvolumen einer Hochschule über einen vier-Jahreszeitraum ausweisen. Beide Indikatoren werden einmal insgesamt für die Open-Access-Publikationen ausgewiesen und zusätzlich noch einmal separat für die gängigen Open-Access-Statustypen (gold, hybrid, grün, bronze, sowie für das traditionelle Leiden Ranking unknown). Neben den Open-Access-Indikatoren wird auch das Gesamtpublikationsvolumen pro Einrichtung angegeben. Auch wenn ein Vergleich zwischen Einrichtungen anhand absoluter Anzahlen Limitationen hat, so kann es doch sinnvoll sein, absolute Zahlen auszuweisen, um die Transparenz und Nachvollziehbarkeit der Indikatoren zu verbessern. Die Angabe der absoluten Anzahlen ermöglicht es den Einrichtungen, die Anteilswerte zu überprüfen und deren Genauigkeit zu beurteilen.</p>
<p>Ähnlich wie die beiden Leiden Rankings, weist auch das COKI OA Dashboard sowohl absolute Anzahlen als auch relative Anteile in Bezug auf das Open-Access-Publikationsvolumen einer Einrichtung aus. Die im COKI OA Dashboard ausgewiesenen Indikatoren unterscheiden sich im Umfang zwischen der institutionellen Übersichtsseite und den Detailseiten der einzelnen Institutionen. Die Übersichtsseite, die einem Vergleich aller im COKI OA Dashboard repräsentierten Einrichtungen dient, weist dabei folgende Indikatoren für den Publikationszeitraum 2000–2024 aus: 1) den prozentualen Anteil an Open Access Veröffentlichungen, 2) ein gestapeltes Balkendiagramm welche die prozentualen Anteile an Artikeln visualisiert, die über den Verlag, andere Platformen, beides oder gar nicht im Open Access zugänglich sind. Das Balkendiagramm weist jedoch die jeweiligen Prozente nicht aus, 3) die Gesamtanzahl der Veröffentlichungen einer Einrichtung und 4) die Gesamtanzahl an Open Access Veröffentlichungen einer Einrichtung. Die Detailseiten der einzelnen Institutionen enthalten weitere spezifische Indikatoren, die eine detailliertere Übersicht des Open-Access-Publizierens einer Einrichtung ermöglichen. Insbesondere sind auf der Detailseite auch die Prozentangaben für das gestapelte Balkendiagramm angegeben und es werden unter anderem auch zeitliche Verläufe dargestellt. Auffällig ist, dass es eine Diskrepanz zwischen der Übersichtsseite und der Detailseite einer Einrichtung bezogen auf die absoluten Anzahlen für das Publikationsvolumen insgesamt und das Open-Access-Publikationsvolumen gibt. Auf der Übersichstsseite werden die exakten Werte angegeben, während auf der Detailsseite gerundete Werte dargestellt werden. Zudem handelt es sich bei dem Wert des prozentualen Open-Access-Anteils auf beiden Seiten um einen gerundeten Wert. Während die Angabe absoluter Zahlen, ähnlich zu den Leiden Rankings, für eine bessere Überprüfbarkeit der Indikatoren sorgt, ist die Darstellung gerundeter Werte weniger exakt.</p>
<p>Das SCImago Institutions Ranking verwendet einen zusammengesetzten Indikator, der verschiedene Indikatoren aus den drei Bereichen <em>Research</em>, <em>Innovation</em> und <em>Societal</em> aggregiert. Die <em>Research</em>-Dimension geht mit 50% Gewicht in den zusammengesetzen Indikator ein und ist gegenüber den beiden anderen Dimension mit 30% (<em>Innovation</em>) und 20% (<em>Societal</em>) Gewichtung demnach deutlich stärker fokussiert. Der Open-Access-Indikator ist im SCImago Institutions Ranking Teil der <em>Research</em>-Dimension und geht mit einem Gewicht von 2% in diese ein. Er gehört damit zu den am wenigsten stark gewichteten Indikatoren innerhalb der <em>Research</em>-Dimension und des zusammengesetzen Indikators insgesamt. Der Open-Access-Indikator gibt den prozentualen Anteil der Publikationen an, die in Open-Access-Zeitschriften veröffentlicht oder in Unpaywall indexiert sind <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>. Das SCImago Institutions Ranking weist aber weder den Open-Access-Indikator noch die von den Einrichtungen erreichte Gesamtpunktzahl aus, sondern gibt lediglich den resultierenden Rang an.</p>
<p>Ähnlich wie das SCImago Institutions Ranking verwendet auch das QS Sustainability Ranking einen zusammengesetzten Indikator. Das QS Sustainability Ranking aggregiert dazu verschiedene Indikatoren aus den Bereichen <em>Environmental Impact</em>, <em>Social Impact</em>, und <em>Governance</em>. Die <em>Governance</em>-Dimension geht mit 10% Gewicht in den zusammengesetzen Indikator ein und ist damit im Gegensatz zur den Gewichtungn der beiden anderen Dimensionen mit jeweils 45 % deutlich weniger stark fokussiert. Der Open-Access-Indikator ist im QS Sustainability Ranking Teil der <em>Governance</em>-Dimension und geht mit einem Gewicht von 1% in diese ein. Alle Indikatoren innerhalb der <em>Governance</em>-Dimension haben das gleiche Gewicht zugewiesen, werden also gleichwertig für die Dimension berücksichtigt. Der Open-Access-Indikator gibt den Anteil der gesamten Forschungsergebnisse einer Einrichtung an, die laut Unpaywall als Open Access verfügbar sind <span class="citation" data-cites="QS_governance">(<a href="#ref-QS_governance" role="doc-biblioref">Quacquarelli Symonds, n.d.-b</a>)</span>. Bei der Indikatorenkonstruktion wird zwischen verschiedenen Open-Access-Statustypen (gold, hybrid, grün) und Feldern unterschieden, denen unterschiedliche Gewichtungen zugewiesen sind. Der finale Open-Access-Indikator wird anhand der einzelnen Werte pro Feld aggregiert und auf einen Wertebereich zwischen 0 und 100 skaliert <span class="citation" data-cites="QS_governance">(<a href="#ref-QS_governance" role="doc-biblioref">Quacquarelli Symonds, n.d.-b</a>)</span>. Der Datensatz QS Sustainability Ranking weist zusätzlich zur Gesamtpunktzahl für jede Dimension gesondert die erreichte Punktzahl aus. Die Gesamtpunktzahl wird dabei nur bis zum Rang 902 angegeben.</p>
<p>Insgesamt ist erkennbar, dass sich die fünf Rankingsysteme teilweise stark in der Verwendung von Open-Access-Indikatoren unterscheiden, auch wenn alle beschriebenen Open-Access-Indikatoren die Produktivität von Einrichtungen in Bezug auf Open Access messen und darstellen. Unterschiede und Herausforderungen für die Vergleichbarkeit der Rankingergebnisse ergeben sich beispielsweise aus der Berücksichtigung verschiedener Open-Access-Statustypen (gold, hybrid, grün, etc.) zur Klassifikation von Open-Access-Publikationen. Hierbei ergibt sich auch eine Pfadabhängigkeit zu der verwendeten Datenquelle, anhand derer die Open-Access-Publikationen identifiziert werden. Beide Versionen des Leiden Ranking verwenden OpenAlex als Datenquelle zur Identifikation von Open-Access-Publikationen und weisen ferner die Open-Access-indikatoren gesondert für alle Open-Access-Statustypen aus. Das QS Sustainability Ranking hingegen stützt sich auf Unpaywall als Datenquelle, scheint jedoch nur zwischen goldenen, hybriden und grünen Open-Access-Publikationen zu unterscheiden <span class="citation" data-cites="QS_governance">(<a href="#ref-QS_governance" role="doc-biblioref">Quacquarelli Symonds, n.d.-b</a>)</span>. Das SCImago Institutions Ranking verwendet Unpaywall als Datenquelle, scheint jedoch keine Open-Access-Statustypen zu unterscheiden <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>. Das COKI OA Dashboard verwendet ebenfalls Unpaywall als Datenquelle zur Identifikation von Open-Access-Publikationen, weist aber im vergleich zu den anderen Ranking nicht die typischen Open-Access-Statustypen mit ihren Farben aus. Vielmehr werden im COKI OA Dashboard goldene, hybride und bronze Publikationen zu der Kategorie <em>Publisher Open</em> zusammengefasst. Diese Unterschiede erschweren die Vergleichbarkeit zwischen den Rankingsystemen in Bezug auf Open Access.</p>
<p>Durch die differenziertere Darstellung der Indikatoren verlangen beide Versionen des Leiden Ranking sowie das COKI OA Dashboard von den Nutzenden eine gesonderte Betrachtung der einzelnen Dimensionen, um eine umfassende Bewertung der Einrichtungen vornehmen zu können. Dies geht mit einer höheren Komplexität bei der Interpretation der Ergebnisse einher. Das SCImago Institutions Ranking und das QS SUstainability Ranking vereinfachen diese Komplexität durch die verwendeten zusammengesetzen Indikatoren. Allerdings erweisen sich die zusammengesetzen Indikatoren als weniger geeignet für das Open-Access-Monitoring und die Bewertung von Open-Access-Aktivitäten, da die spezifischen auf Open Access bezogenen Werte nicht direkt aus den zusammengesetzten Indikatoren abgeleitet werden können. Darüber hinaus spielen Open-Access-Indikatoren beim SCImago Institutions Ranking und dem QS Sustainability Ranking eine deutlich untergeordnete Rolle, da sie jeweils nur einen geringen Anteil an der Gesamtwertung ausmachen.</p>
</section><section id="überschneidung-von-institutionen" class="level3"><h3 class="anchored" data-anchor-id="überschneidung-von-institutionen">Überschneidung von Institutionen</h3>
<p>Zur Bestimmung der institutionellen Überschneidungen zwischen den Rankings wurden zunächst die verfügbaren Ergebnisdaten der Rankings heruntergeladen<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Neben den Namen und Standorten (Länderangaben, teilweise auch Angaben zu Regionen und Unterregion) aller Institutionen, enthalten die Daten der beiden Versionen des Leiden Rankings sowie des COKI OA Dashboards auch Identifier aus dem <a href="https://ror.org/">Research Organization Registry (ROR)</a>. Darüber hinaus umfassen die Daten des COKI OA Dashboard und des SCImago Institutions Ranking Sektorenzuordnungen für alle in den Rankings abgebildeten Institutionen.</p>
<p>Um identische Institutionen zwischen den Rankings anhand ihrer ROR-IDs eindeutig zuordnen zu können, mussten zunächst die Daten des SCImago Institutions Rankings und des QS Sustainability Rankings um ROR-IDs ergänzt werden. Dazu wurde der gesamte ROR-Datensatz in der Version 1.69 <span class="citation" data-cites="ror_data">(<a href="#ref-ror_data" role="doc-biblioref">Research Organization Registry, 2025</a>)</span> heruntergeladen. Anschließend wurde jeweils für beide Rankings ein maschineller Abgleich auf Basis der institutionellen Namensansetzung und der Länderangabe mit den ROR-Daten durchgeführt. Die QS Daten enthielten Einträge für insgesamt 1.743 Institutionen<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, von denen 1.204 Institutionen mittels des maschinellen Abgleichs ROR-IDs zugeordnet werden konnten. Für die restlichen 539 Institutionen wurde eine manuelle Zuordnung der ROR-IDs vorgenommen, wobei allerdings für 7 Institutionen keine Zuordnung erfolgen konnte. Zur quantitativen Bestimmung der institutionellen Überschneidungen konnten demnach lediglich 1.736 Institutionen aus dem QS Sustainability Ranking berücksichtigt werden.</p>
<p>Schwieriger gestaltete sich die Zuordnung von ROR-IDs zu den 9.755 im SCImago Institutions Ranking inkludierten Institutionen<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Über den maschinellen Abgleich auf Basis der institutionellen Namensansetzung und der Länderangabe konnten ROR-IDs lediglich zu 4.714 Institutionen zugeordnet werden. In Teilen könnte dies darauf zurückzuführen sein, dass das SCImago Institutions Ranking auch Institutionen listet, die als multinational gekennzeichnet sind <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>. Dies scheint insbesondere Unternehmen zu betreffen, die überregional agieren, beispielsweise <a href="https://www.scimagoir.com/institution.php?idp=89900">Google</a>. Zwar bietet ROR auch IDs für Unternehmen (siehe <a href="https://ror.org/00njsd438">Google</a>), scheint dabei jedoch eindeutige Länderzuordnungen vorzunehmen. Die größere Schwierigkeit für den maschinellen Abgleich stellen jedoch vermutlich unterschiedliche Namensansetzungen zwischen dem SCImago Institutions Ranking und ROR dar<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. Um die Abdeckung mit ROR-IDs für das SCImago Institutions Ranking zu erhöhen, wurde ein fuzzy matching Ansatz getestet, der auch alternative Namensformen und Akronyme aus dem ROR-Datensatz berücksichtigte. Das Ergebnis war jedoch nicht hinreichend genau und hätte einen hohen Datenbereinigungsaufwand erfordert. Insgesamt stellt dies eine deutliche Limitation für die Verwendbarkeit des SCImago-Datensatzes für eine globale Analyse der institutionellen Überschneidungen dar.</p>
<p>Aufgrund der Probleme bei der Zuordnung von ROR-IDs wurde entschieden, die Analyse der institutionellen Überschneidungen auf Einrichtungen aus Deutschland zu beschränken. Im Datensatz des QS Sustainability Ranking konnten insgesamt 50 Einrichtungen aus Deutschland identifiziert werden, von denen allen eine ROR-ID zugeordnet werden konnte. Im Datensatz des SCImago Institutions Ranking konnten insgesamt 364 Einrichtungen aus Deutschland identifiziert werden, von denen 342 keine ROR-ID über den maschinellen Abgleich zugeordnet werden konnten. Daher wurde eine manuelle Zuordnung vorgenommen, wobei jedoch für 6 der 342 Einrichtungen keine Zuordnung einer ROR-ID erfolgen konnte. Für die Analyse der institutionellen Überschneidungen deutscher Einrichtungen konnten demnach 385 Einrichtungen für das SCImago Institutions Ranking berücksichtigt werden.</p>
<p><a href="#fig-2" class="quarto-xref">Abb. 2</a> stellt quantitativ die institutionellen Überschneidungen deutscher Einrichtungen zwischen den Rankings dar. Die Abbildung bezieht dabei nur die Institutionen ein, denen ROR-IDs zugeordnet werden konnten.</p>
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="upset">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/all_de_institution_upset.png" class="lightbox" data-gallery="upset" title="Abbildung 2: Institutionelle Überschneidungen für alle deutschen Institutionen mit ROR-IDs in fünf Rankingsystemen"><img src="rankings/plots/all_de_institution_upset.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung 2: Institutionelle Überschneidungen für alle deutschen Institutionen mit ROR-IDs in fünf Rankingsystemen
</figcaption></figure>
</div>
<p>Insgesamt konnten nach dem Abgleich der ROR-IDs 2.928 einzigartige Instiutionen aus Deutschland über alle Rankingsysteme hinweg identifiziert werden. Anhand von <a href="#fig-2" class="quarto-xref">Abb. 2</a> ist zu erkennen, dass das COKI OA Dashboard deutlich mehr deutsche Einrichtungen abbildet, als alle anderen Rankingsysteme, sowohl insgesamt (2.927 Institutionen, 99,97 %), als auch in Bezug auf die Anzahl an Institutionen, die in keinem anderen Rankingsystem abgebildet werden (2.570 Institutionen, 87,77 %). Dies könnte insbesondere darauf zurückzuführen sein, dass das COKI OA Dashboard einerseits einen relativ langen Publikationszeitraum abbildet (2000–2024) und andererseits auch Institutionen aus mehreren Sektoren, sowie Institutionen mit einem relativ geringen Publikationsvolumen von i.d.R. mindestens 50 Publikationen in das Ranking aufnimmt <span class="citation" data-cites="COKI_how COKI_data">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>, <a href="#ref-COKI_data" role="doc-biblioref">n.d.-b</a>)</span>.</p>
<p><a href="#fig-2" class="quarto-xref">Abb. 2</a> zeigt ferner, dass von den 358 aus dem SCImago Institutions Ranking berücksichtigten Institutionen, 1 Institution (0,03 %) in keinem anderen Ranking erfasst ist. Dahingegen werden alle Instiutionen aus beiden Versionen des Leiden Rankings sowie aus dem QS Sustainability Ranking auch in mindestens einem weiteren Ranking abgebildet. Insgesamt sind lediglich 47 Institutionen (1,61 %) in allen fünf Rankingsystemen erfasst.</p>
<p>Während das QS Sustainability Ranking sowie beide Versionen des Leiden Ranking lediglich Hochschulen in ihre Rankings einbeziehen, sind im COKI OA Dashboard und dem SCImago Institutions Ranking auch Institutionen aus anderen Sektoren erfasst. Hochschulen werden im COKI-Datensatz mit dem Institutionentyp <em>Education</em> klassifiziert, während im Datensatz des SCImago Institutions Ranking der Sektor <em>Universities</em> für Hochschulen zugewiesen ist. Um folgend die institutionellen Überschneidungen der deutschen Hochschulen zwischen den fünf Rankingsystemen zu untersuchen, wurde im zusammengeführten Datensatz aller Rankingsysteme eine Spalte <em>sector</em> hinzugefügt. Für Einrichtungen, die in beiden Versionen des Leiden Ranking oder im QS Sustainability Ranking abgebildet sind, wurde die Sektorzuordnung <em>Universities</em> ergänzt. Für Einrichtungen, die im SCImago Institutions Ranking oder COKI OA Dashboard abgebildet sind wurde die ursprüngliche Klassifikation beibehalten. Anschließend wurde der Datensatz nach Einrichtungen gefiltert, denen in der <em>sector</em>-Spalte die Werte <em>Universities</em> oder <em>Education</em> zugewiesen waren.</p>
<p><a href="#fig-3" class="quarto-xref">Abb. 3</a> stellt folgend die institutionellen Überschneidungen bezogen auf deutsche Hochschulen zwischen den Rankings dar. Die Abbildung bezieht dabei ebenfalls nur diejenigen Institutionen ein, denen ROR-IDs zugeordnet werden konnten.</p>
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="upset">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/univs_de_institution_upset.png" class="lightbox" data-gallery="upset" title="Abbildung 3: Institutionelle Überschneidungen für deutsche Hochschulen mit ROR-IDs in fünf Rankingsystemen"><img src="rankings/plots/univs_de_institution_upset.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung 3: Institutionelle Überschneidungen für deutsche Hochschulen mit ROR-IDs in fünf Rankingsystemen
</figcaption></figure>
</div>
<p>Insgesamt konnten 395 verschiedene deutsche Hochschulen über alle Rankingsysteme hinweg identifiziert werden. <a href="#fig-3" class="quarto-xref">Abb. 3</a> zeigt, dass das COKI OA Dashboard auch in Bezug auf die deutschen Hochschulen deutlich mehr Institutionen abbildet, als alle anderen Rankingsysteme, sowohl insgesamt (395 Institutionen, 100 %), als auch in Bezug auf die Anzahl an Institutionen, die in keinem anderen Rankingsystem erfasst sind (287 Institutionen, 72,66 %). Nach Angaben des Statistischen Bundesamt wurden im Wintersemester 2024/2025 insgesamt 422 deutsche Hochschulen gezählt <span class="citation" data-cites="destatis">(<a href="#ref-destatis" role="doc-biblioref">Statistisches Bundesamt, 2025</a>)</span>. Demnach bildet das COKI OA Dashboard nach aktuellem Stand 93,6 % aller deutschen Hochschulen ab. Es ist zudem das einzige Rankingsystem, dass Hochschulen abbildet, die in keinem anderen Ranking erfasst sind. Die absolute Anzahl an deutschen Hochschulen, die in allen fünf Rankingsystemen erfasst sind ist mit 47 Hochschulen unverändert zur absoluten Anzahl aller deutschen Einrichtungen, die in allen fünf Rankingsystemen erfasst sind.</p>
<p>Das COKI OA Dashboard und das SCImago Institutions Ranking sind die beiden einzigen der untersuchten Rankingsysteme, die nicht nur Hochschulen in ihre Rankings mit einbeziehen. In Bezug auf Deutschland entfallen auf die insgesamt 2.927 deutschen Einrichtungen, die im COKI OA Dashboard abgebildet sind 13,5 % auf deutsche Hochschulen. Im Vergleich entfallen auf die insgesamt 358 deutschen Einrichtungen, die im SCImago Institutions Ranking abgebildet sind, 30,17 % auf deutsche Hochschulen. Für beide Rankingsysteme lässt sich demnach feststellen, dass der Großteil an abgebildeten Einrichtungen, zumindest in Bezug auf Deutschland, anderen Sektoren zugewiesen ist.</p>
</section><section id="geographische-verteilung" class="level3"><h3 class="anchored" data-anchor-id="geographische-verteilung">Geographische Verteilung</h3>
<p>Abbildungen <a href="#fig-leidenmaps" class="quarto-xref">4</a> und <a href="#fig-maps" class="quarto-xref">5</a><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> zeigen folgend die geographische Verteilung der Instiutionen in Bezug auf die Länder und Weltregionen, in denen sie lokalisiert sind. Auch wenn alle fünf Rankings eine globale Ausrichtung haben, soll anhand der Abbildungen visualisiert werden, ob es Unterschiede in der geographischen Verteilung zwischen den Rankings gibt. Um eine bessere Vergleichbarkeit zu gewährleisten wurden für alle Rankingsysteme die Instiutionen auf jene eingeschränkt, die dem Hochschulsektor (<em>Universities</em>, <em>Education</em>) zugeordnet sind.</p>
<div id="fig-leidenmaps" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-leidenmaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-leidenmaps" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-LR" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-LR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/lr_map.png" class="lightbox" data-gallery="map" title="Abbildung 4 (a): Leiden Ranking 2024"><img src="rankings/plots/lr_map.png" class="img-fluid figure-img" data-ref-parent="fig-leidenmaps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-LR-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Leiden Ranking 2024
</figcaption></figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-leidenmaps" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-LROE" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-LROE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/lroe_map.png" class="lightbox" data-gallery="map" title="Abbildung 4 (b): Leiden Ranking Open Edition 2024"><img src="rankings/plots/lroe_map.png" class="img-fluid figure-img" data-ref-parent="fig-leidenmaps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-LROE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Leiden Ranking Open Edition 2024
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-leidenmaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung 4: Geographische Verteilung der in den Leiden Rankings abgebildeten Institutionen auf Länder und Weltregionen
</figcaption></figure>
</div>
<div id="fig-maps" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-maps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-maps" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-sir" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sir-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/sir_univ_map.png" class="lightbox" data-gallery="map" title="Abbildung 5 (a): SCImago Institutions Ranking 2025 (Universities)"><img src="rankings/plots/sir_univ_map.png" class="img-fluid figure-img" data-ref-parent="fig-maps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sir-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) SCImago Institutions Ranking 2025 (Universities)
</figcaption></figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-maps" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-qs" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-qs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/qs_map.png" class="lightbox" data-gallery="map" title="Abbildung 5 (b): QS Sustainability Ranking 2025"><img src="rankings/plots/qs_map.png" class="img-fluid figure-img" data-ref-parent="fig-maps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-qs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) QS Sustainability Ranking 2025
</figcaption></figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-maps" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-coki" class="quarto-float quarto-figure quarto-figure-center anchored" data-group="map">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-coki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="rankings/plots/coki_univ_map.png" class="lightbox" data-gallery="map" title="Abbildung 5 (c): COKI OA Dashboard 2025 (Education)"><img src="rankings/plots/coki_univ_map.png" class="img-fluid figure-img" data-ref-parent="fig-maps"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-coki-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) COKI OA Dashboard 2025 (Education)
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-maps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung 5: Geographische Verteilung der in den Rankingssystemen SIR, QS und COKI abgebildeten Institutionen auf Länder und Weltregionen
</figcaption></figure>
</div>
<p>Betrachtet man die absoluten Anzahlen an Hochschulen, so zeigen Abbildungen <a href="#fig-leidenmaps" class="quarto-xref">4</a> und <a href="#fig-maps" class="quarto-xref">5</a> insbesondere, dass für beide Versionen des Leiden Rankings sowie das SCImago Instiutions Ranking die meisten Hochschulen in China ansässig sind (LR: 313 Institutionen, LROE: 313 Institutionen, SIR: 634 Institutionen). Hingegen sind für das QS Sustainability Ranking sowie das COKI OA Dashboard die meisten Institutionen in den Vereinigten Staaten von Amerika ansässig (QS: 238 Institutionen, COKI: 2688 Institutionen). Ferner verdeutlichen die Abbildungen, dass, mit Ausnahme des COKI OA Dashboards, insbesondere einige Länder aus dem globalen Süden gar nicht in den Rankingsystemen repräsentiert sind.</p>
<p>Zusätzlich zur absoluten Anzahl an Hochschulen soll im Folgenden die relative Verteilung der Hochschulen über Länder und Rankingsysteme hinweg anhand der <em>preference</em> nach <span class="citation" data-cites="Moed2016">Moed (<a href="#ref-Moed2016" role="doc-biblioref">2016</a>)</span> betrachtet werden. <span class="citation" data-cites="Moed2016">Moed (<a href="#ref-Moed2016" role="doc-biblioref">2016</a>)</span> definiert die <em>preference</em> als<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>:</p>
<blockquote class="blockquote">
<p>The preference of ranking system R for a particular country C is expressed as the ratio of the actual and the expected number of institutions from C appearing in R, where the expected number is based on the total number of institutions across countries and across systems, under the assumption of independence of these two variables. A value of 1.0 indicates that the number of institutions from C in R is ‘as expected’.</p>
</blockquote>
<p>Der resultierende Präferenzwert (<em>preference score</em>) misst also, ob ein Land, gemessen an der Anzahl dort ansässiger Institutionen, innerhalb eines Rankingsystems überproportional oder unterproportional repräsentiert ist. Das Maß ist bei einem Wert von 1 neutral, d.h. die Anzahl an Institutionen aus einem Land in einem Rankingsystem entspricht den Erwartungen. Werte über 1 deuten darauf hin, dass mehr Institutionen aus einem Land in einem Rankingsystem erfasst sind als erwartet. Werte unter 1 deuten darauf hin, dass weniger Institutionen aus einem Land in einem Rankingsystem erfasst sind als erwartet.</p>
<p><a href="#tbl-pref" class="quarto-xref">Tab. 3</a> stellt für alle fünf Rankingsysteme für die Top 5 Länder, gemessen am Präferenzwert (<em>preference score</em>), sowie Deutschland die absolute Anzahl an Hochschulen und den jweiligen Präferenzwert dar.</p>
<div id="tbl-pref" class="quarto-layout-panel anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pref-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle 3: Präferenzwerte der Top 5 Länder und Deutschland pro Rankingsystem
</figcaption><div aria-describedby="tbl-pref-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 37%">
<col style="width: 22%">
<col style="width: 24%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Ranking</th>
<th style="text-align: left;">Land</th>
<th style="text-align: left;">Nr. Hochschulen</th>
<th style="text-align: left;">preference score</th>
</tr></thead>
<tbody>
<tr class="odd">
<td rowspan="7" style="text-align: left;">Leiden</td>
<td style="text-align: left;">Luxemburg</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,45</td>
</tr>
<tr class="even">
<td style="text-align: left;">Australien</td>
<td style="text-align: left;">35</td>
<td style="text-align: left;">2,34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Spanien</td>
<td style="text-align: left;">47</td>
<td style="text-align: left;">2,32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Italien</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">2,22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: left;">313</td>
<td style="text-align: left;">2,15</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deutschland</td>
<td style="text-align: left;">57</td>
<td style="text-align: left;">1,46</td>
</tr>
<tr class="even">
<td rowspan="7" style="text-align: left;">SIR</td>
<td style="text-align: left;">Färöer-Inseln</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Französisch-Guayana</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grenada</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guadeloupe</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lesotho</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,55</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Deutschland</td>
<td style="text-align: left;">108</td>
<td style="text-align: left;">0,82</td>
</tr>
<tr class="odd">
<td rowspan="7" style="text-align: left;">COKI</td>
<td style="text-align: left;">Myanmar</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kambodscha</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nicaragua</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="even">
<td style="text-align: left;">Somalia</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">El Salvador</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">1,61</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deutschland</td>
<td style="text-align: left;">397</td>
<td style="text-align: left;">0,96</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 26%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Ranking</th>
<th style="text-align: left;">Land</th>
<th style="text-align: left;">Nr. Hochschulen</th>
<th style="text-align: left;">preference score</th>
</tr></thead>
<tbody>
<tr class="odd">
<td rowspan="7" style="text-align: left;">Leiden OE</td>
<td style="text-align: left;">Luxemburg</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,45</td>
</tr>
<tr class="even">
<td style="text-align: left;">Australien</td>
<td style="text-align: left;">35</td>
<td style="text-align: left;">2,34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Spanien</td>
<td style="text-align: left;">47</td>
<td style="text-align: left;">2,32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Italien</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">2,22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: left;">313</td>
<td style="text-align: left;">2,15</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deutschland</td>
<td style="text-align: left;">57</td>
<td style="text-align: left;">1,46</td>
</tr>
<tr class="even">
<td rowspan="7" style="text-align: left;">QS</td>
<td style="text-align: left;">Brunei</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">3,70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hongkong</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">3,17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malta</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2,96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saudi-Arabien</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">2,67</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jordanien</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">2,50</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Deutschland</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">1,11</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</figure>
</div>
<p><a href="#tbl-pref" class="quarto-xref">Tab. 3</a> zeigt unterschiedliche geografische Abdeckungen der verschiedenen Rankingsysteme in Bezug auf die überproportinal repräsentierten Länder auf. So sind beide Versionen des Leiden Ranking tendenziell auf Europa ausgerichtet, das SCImago Institutions Ranking tendenziell auf Nord- und Südamerika, das COKI OA Dashboard überwiegend auf Asien und Mittelamerika und das QS Sustainability Ranking primär auf Asien. Eine Besonderheit stellt das COKI OA Dashboard dar. Insgesamt weist der COKI Datensatz 68 Länder mit dem selben Präferenzwert von 1,61 auf. Die in <a href="#tbl-pref" class="quarto-xref">Tab. 3</a> dargestellten Länder sind jene ersten fünf Einträge, die sich aus einer absteigenden Sortierung nach der Anzahl an Institutionen aus den jeweiligen Ländern ergeben. Die Beobachtung, dass eine Vielzahl an Ländern den selben Präferenzwert haben ist darauf zurückzuführen, dass die 68 Länder ausschließlich im COKI OA Dashboard enthalten sind.</p>
<p>Bezogen auf Deutschland zeigt <a href="#tbl-pref" class="quarto-xref">Tab. 3</a>, dass beiden Versionen des Leiden Ranking sowie das QS Sustainability Ranking mit Präferenzwerten von 1,46 und 1,11 eine überproportionale bzw. leicht überproportionale Anzahl an deutschen Hochschulen in ihre Rankings einbeziehen. Dies deutet darauf hin, dass in diesen Rankingsystemen deutsche Hochschulen mit einer absoluten Anzahl von 50 und 57 Hochschulen leicht überrepräsentiert bis überrepräsentiert sind. Hingegen sind im COKI OA Dashboard mit einer absoluten Anzahl von 397 zwar wesentlich mehr deutsche Hochschulen im Ranking enthalten, allerdings zeigt der Präferenzwert von 0.96, dass diese Anzahl unter dem Erwartungswert liegt. Für das SCImago Institutions Ranking beträgt der Präferenzwert für deutsche Hochschulen lediglich 0,82. Dies deutet darauf hin, dass Einrichtungen aus Deutschland in diesem Ranking unterrepräsentiert sind, obwohl die absolute Anzahl an deutschen Hochschulen mit 108 die Zweithöchste ist.</p>
</section><section id="institutionelle-beteiligung-bei-der-datenerhebung" class="level3"><h3 class="anchored" data-anchor-id="institutionelle-beteiligung-bei-der-datenerhebung">Institutionelle Beteiligung bei der Datenerhebung</h3>
<p>Dieser Abschnitt befasst sich mit den Datenerhebungsverfahren der verschiedenen Rankinganbieter und untersucht inwieweit sich Einrichtungen an der sie betreffenden Datenerhebung beteiligen können.</p>
<p>Für das traditionelle Leiden Ranking erhebt das CWTS keinerlei Daten direkt von den gerankten Einrichtungen <span class="citation" data-cites="LR_method LR_general">(<a href="#ref-LR_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-a</a>, <a href="#ref-LR_general" role="doc-biblioref">n.d.-c</a>)</span>. Das Ranking basiert auf Daten aus dem Web of Science, die vom CWTS aufbereitet und standardisiert werden. Da es sich beim Web of Science jedoch um eine proprietäre Datenquelle handelt, die mit lizenzrechtlichen Restriktionen einhergeht, ist es dem CWTS nicht möglich die Rohdaten sowie die kuratierten Daten offen zugänglich zu machen <span class="citation" data-cites="LeidenData">(<a href="#ref-LeidenData" role="doc-biblioref">van Eck, Visser, et al., 2024</a>)</span>. Dadurch ist es den betreffenden Einrichtungen nicht ohne Weiteres möglich die Datenqualität zu überprüfen.</p>
<p>Für das Leiden Ranking Open Edition werden ebenfalls keine Daten direkt bei den Einrichtungen erhoben <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Im Gegensatz zum traditionellen Leiden Ranking greift das Leiden Ranking Open Edition jedoch auf offene Datenquellen, wie OpenAlex und ROR, zur Erstellung des Rankings zurück <span class="citation" data-cites="LROE_method">(<a href="#ref-LROE_method" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-b</a>)</span>. Durch die Verwendung von offenen Datenquellen und aufgrund der Bereitstellung der Roh- und Ergebnisdaten durch das CWTS <span class="citation" data-cites="LROE_resources">(<a href="#ref-LROE_resources" role="doc-biblioref">Centre for Science and Technology Studies, Leiden University, n.d.-d</a>)</span> ist es den gerankten Einrichtungen möglich, einerseits die Qualität der Daten zu überprüfen und andererseits am Datenkurierungsprozess teilzunehmen, indem die Einrichtungen Probleme mit der Datenqualität an die jeweiligen Akteure melden <span class="citation" data-cites="LeidenData">(<a href="#ref-LeidenData" role="doc-biblioref">van Eck, Visser, et al., 2024</a>)</span>.</p>
<p>Die Methodik des SCImago Institutions Rankings beschreibt, dass für das Ranking Daten aus verschiedenen Quellen erhoben werden, dies sind: Scopus, PATSTAT, Google, Semrush, Unpaywall, PlumX Metrics, Mendeley und Overton <span class="citation" data-cites="SIR_method">(<a href="#ref-SIR_method" role="doc-biblioref">SCImago Research Group, n.d.-a</a>)</span>. Die Methodik erwähnt keine Möglichkeit der institutionellen Beteiligung bei der Datenerhebung, weshalb davon ausgegangen wird, dass keine Daten direkt von den gerankten Institutionen erhoben werden. Die bibliographischen Daten für das SCImago Institutions Ranking stammen aus Scopus, einer proprietären Datenquelle, die, ähnlich wie das Web of Science, mit lizenzrechtlichen Einschränkungen einhergeht. Die Rohdaten des SCImago Institutions Ranking sind nicht öffentlich zugänglich, wodurch davon auszugehen ist, dass gerankte Institutionen nicht ohne Weiteres die Möglichkeit haben, die sie betreffenden Daten zu überprüfen oder zu korrigieren, bevor sie in das Ranking einbezogen werden. Zur Bestimmung des Open-Access-Status verwendet das SCImago Institutions Ranking mit Unpaywall eine offene Datenquelle. Ähnlich wie beim Leiden Ranking Open Edition könnte für die Open-Access-Daten eine Beteiligung der betreffenden Einrichtungen am Datenkuratierungsprozess möglich sein, indem Probleme mit der Datenqualität direkt an Unpaywall gemeldet werden. Insgesamt weist die Methodik des SCImago Institutions Ranking wenig Informationen bezüglich Datenqualität und mögliche Einschränkungen auf, es wird auch nicht transparent kommuniziert, welche Möglichkeiten es für Einrichtungen gibt zu einer verbesserten Datenqualität beizutragen.</p>
<p>Die COKI Open Access Dashboard verwendet zur Datenerhebung ausschließlich offene Datenquellen, darunter Crossref, Unpaywall, oder ROR <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>. Die Methodik des COKI OA Dashboard beschreibt detailliert den Prozess der Datenerhebung anhand externer Datenquellen, macht jedoch keine Angaben zu einer Datenlieferung durch die gerankten Institutionen selbst <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span>. Es ist daher davon auszugehen, dass es keine direkte institutionelle Beteiligung bei der Datenerhebung gibt. Da der COKI-Datensatz auf offenen Datenquellen basiert, ist ähnlich wie beim Leiden Ranking Open Edition davon auszugehen, dass die betreffenden Institutionen die Möglichkeit haben sich indirekt am Datenkuratierungsprozess zu beteiligen, indem sie Probleme mit der Datenqualität direkt an die jeweiligen Verantwortlichen der verschiedenen Datenquellen melden. Darüber hinaus kommuniziert COKI Limitationen des eigenen Datensatzes <span class="citation" data-cites="COKI_how">(<a href="#ref-COKI_how" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-c</a>)</span> und bietet verschiedene Kontaktmöglichkeiten <span class="citation" data-cites="COKI_contact">(<a href="#ref-COKI_contact" role="doc-biblioref">Curtin Open Knowledge Initiative, n.d.-a</a>)</span>, sodass Einrichtungen auch die Möglichkeit haben, aktiv an der Verbesserung der Daten des COKI-Datensatzes mitzuwirken.</p>
<p>Das QS Sustainability Ranking ist das einzige der fünf untersuchten Rankingsysteme, dass eine direkte Beteiligung der betreffenden Institutionen bei der Datenerhebung vorsieht. Die Methodik des QS Sustainability Ranking beschreibt, dass QS generell alle Institutionen ermutigt, Daten für die QS Rankings bereitzustellen <span class="citation" data-cites="QS_sustain">(<a href="#ref-QS_sustain" role="doc-biblioref">Quacquarelli Symonds, n.d.-g</a>)</span>. Zur Datenübermittlung stellt QS eine spezielle Plattform bereit, die Methodik bietet jedoch keine genaue Auflistung, welche Daten erfragt werden <span class="citation" data-cites="QS_sustain">(<a href="#ref-QS_sustain" role="doc-biblioref">Quacquarelli Symonds, n.d.-g</a>)</span>. Sollten Institutionen, die für die Aufnahme in das QS Sustainability Ranking qualifiziert sind keine Daten liefern, so bewertet QS diese Institutionen auf Grundlage von proprietären und öffentlich verfügbaren Daten oder zuvor von der jeweiligen Einrichtung bereitgestellten Daten. Ein gänzliches opt-out aus dem Ranking von institutioneller Seite ist demnach nicht vorgesehen. QS argumentiert dies damit, dass die Inklusion aller qualifizierenden Einrichtungen die Zuverlässigkeit der Rankings erhöht <span class="citation" data-cites="QS_optout">(<a href="#ref-QS_optout" role="doc-biblioref">Quacquarelli Symonds, n.d.-c</a>)</span>. Allerdings bietet QS keine Angaben dazu, wie viele der gerankten Einrichtungen tatsächlich die Möglichkeit zur Datenlieferung wahrnehmen.</p>
<p>Insgesamt zeigt sich, dass die Möglichkeit für Einrichtungen, sich an der sie betreffenden Datenerhebung der Rankinganbieter zu beteiligen, nur begrenzt gegeben ist. Das QS Sustainability Ranking ist das einzige Rankingsystem, das direkt Daten von den betreffenden Institutionen erhebt, wobei nicht ganz klar ist, welche spezifischen Daten von den Einrichtungen abgefragt werden. Die anderen Rankingsysteme verwenden ausschließlich Daten aus externen Quellen, die nicht direkt von den Institutionen erhoben werden. Die Verwendung von offenen Datenquellen, wie im Leiden Ranking Open Edition oder dem COKI OA Dashboard, kann jedoch den Einrichtungen eine Möglichkeit bieten, die Qualität der sie betreffenden Daten zu verbessern. Qualitativ hochwertige Quelldaten, sowie transparente Methodiken für die Erstellung von Rankings können ferner dazu beitragen das Vertrauen in Verlässlichkeit und Aussagekraft der Rankingsysteme zu verbessern.</p>



</section></section><a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default">
<section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-destatis" class="csl-entry" role="listitem">
Statistisches Bundesamt. (2025). <em><span class="nocase">Hochschulen nach Hochschularten</span></em>. <a href="https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Hochschulen/Tabellen/hochschulen-hochschularten.html">https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Hochschulen/Tabellen/hochschulen-hochschularten.html</a>
</div>
<div id="ref-Wellcome_Trust" class="csl-entry" role="listitem">
Wellcome. (2025). <em>Open access policy</em>. <a href="https://wellcome.org/research-funding/guidance/ending-a-grant/open-access-guidance/open-access-policy">https://wellcome.org/research-funding/guidance/ending-a-grant/open-access-guidance/open-access-policy</a>
</div>
<div id="ref-DFG" class="csl-entry" role="listitem">
Deutsche Forschungsgemeinschaft. (2025). <em><span>Verwendungsrichtlinien</span>: <span class="nocase">Allgemeine Bedingungen für Förderverträge mit der Deutschen Forschungsgemeinschaft e.V. (DFG)</span></em>. <a href="https://www.dfg.de/resource/blob/348088/dfg-2-00-de-v0125.pdf">https://www.dfg.de/resource/blob/348088/dfg-2-00-de-v0125.pdf</a>
</div>
<div id="ref-COKI2025_07_21" class="csl-entry" role="listitem">
Hosking, R., Diprose, J. P., Roelofs, A., Chien, T.-Y., Montgomery, L., &amp; Neylon, C. (2025). <em>COKI open access dataset (2025-07-21)</em> [Data set]. Zenodo. <a href="https://doi.org/10.5281/zenodo.16257454">https://doi.org/10.5281/zenodo.16257454</a>
</div>
<div id="ref-ror_data" class="csl-entry" role="listitem">
Research Organization Registry. (2025). <em>ROR data (v1.69)</em> [Data set]. Zenodo. <a href="https://doi.org/10.5281/ZENODO.16762508">https://doi.org/10.5281/ZENODO.16762508</a>
</div>
<div id="ref-NIH" class="csl-entry" role="listitem">
National Institutes of Health. (2024). <em><span>NIH Public Access Policy Overview</span></em>. <a href="https://grants.nih.gov/grants/guide/notice-files/NOT-OD-25-047.html">https://grants.nih.gov/grants/guide/notice-files/NOT-OD-25-047.html</a>
</div>
<div id="ref-QS_date" class="csl-entry" role="listitem">
Quacquarelli Symonds. (2024). <em>QS world university rankings: Sustainability 2025 | now live!</em> <a href="https://www.qs.com/insights/articles/qs-world-university-rankings-sustainability-2025-now-live/">https://www.qs.com/insights/articles/qs-world-university-rankings-sustainability-2025-now-live/</a>
</div>
<div id="ref-LROE2024a" class="csl-entry" role="listitem">
van Eck, N. J., Waltman, L., &amp; Neijssel, M. (2024). <em><span class="nocase">Launch of the CWTS Leiden Ranking Open Edition 2024</span></em>. <a href="https://www.leidenmadtrics.nl/articles/launch-of-the-cwts-leiden-ranking-open-edition-2024">https://www.leidenmadtrics.nl/articles/launch-of-the-cwts-leiden-ranking-open-edition-2024</a>
</div>
<div id="ref-LeidenData" class="csl-entry" role="listitem">
van Eck, N. J., Visser, M., &amp; Waltman, L. (2024). <em><span class="nocase">Opening up the CWTS Leiden Ranking: Toward a decentralized and open model for data curation</span></em>. <a href="https://www.leidenmadtrics.nl/articles/opening-up-the-cwts-leiden-ranking-toward-a-decentralized-and-open-model-for-data-curation">https://www.leidenmadtrics.nl/articles/opening-up-the-cwts-leiden-ranking-toward-a-decentralized-and-open-model-for-data-curation</a>
</div>
<div id="ref-LROE2024" class="csl-entry" role="listitem">
Waltman, L., van Eck, N. J., Visser, M., Neijssel, M., Montgomery, L., Neylon, C., Kramer, B., Demes, K., &amp; Priem, J. (2024). <em><span class="nocase">Introducing the Leiden Ranking Open Edition</span></em>. <a href="https://www.leidenmadtrics.nl/articles/introducing-the-leiden-ranking-open-edition">https://www.leidenmadtrics.nl/articles/introducing-the-leiden-ranking-open-edition</a>
</div>
<div id="ref-LR2024_data" class="csl-entry" role="listitem">
Van Eck, N. J. (2024a). <em>CWTS leiden ranking 2024</em> [Data set]. Zenodo. <a href="https://doi.org/10.5281/ZENODO.12606083">https://doi.org/10.5281/ZENODO.12606083</a>
</div>
<div id="ref-LROE2024_raw" class="csl-entry" role="listitem">
Van Eck, N. J. (2024b). <em>CWTS leiden ranking open edition 2024 - data</em> [Data set]. Zenodo. <a href="https://doi.org/10.5281/ZENODO.13868129">https://doi.org/10.5281/ZENODO.13868129</a>
</div>
<div id="ref-LROE2024_results" class="csl-entry" role="listitem">
Van Eck, N. J. (2024c). <em>CWTS leiden ranking open edition 2024 - results</em> [Data set]. Zenodo. <a href="https://doi.org/10.5281/ZENODO.13868018">https://doi.org/10.5281/ZENODO.13868018</a>
</div>
<div id="ref-Diprose2023" class="csl-entry" role="listitem">
Diprose, J. P., Hosking, R., Rigoni, R., Roelofs, A., Chien, T.-Y., Napier, K., Wilson, K., Huang, C.-K. (Karl)., Handcock, R. N., Montgomery, L., &amp; Neylon, C. (2023). A user-friendly dashboard for tracking global open access performance. <em>The Journal of Electronic Publishing</em>, <em>26</em>(1). <a href="https://doi.org/10.3998/jep.3398">https://doi.org/10.3998/jep.3398</a>
</div>
<div id="ref-COKI_newsletter" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative, &amp; Wilson, K. (2022). <em><span>COKI 2022 Update Newsletter</span></em>. <a href="https://openknowledge.community/coki-2022-update-newsletter/">https://openknowledge.community/coki-2022-update-newsletter/</a>
</div>
<div id="ref-COKI_date" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (2022). <em><span>Tracking Global Open Access</span></em>. <a href="https://openknowledge.community/oa-dashboard/">https://openknowledge.community/oa-dashboard/</a>
</div>
<div id="ref-Ruecknagel2021" class="csl-entry" role="listitem">
Rücknagel, J. (2021). <em>Fördererauflagen zu open access - was gilt es zu beachten?</em> <a href="https://doi.org/10.5281/ZENODO.4694319">https://doi.org/10.5281/ZENODO.4694319</a>
</div>
<div id="ref-Huang2020" class="csl-entry" role="listitem">
Huang, C.-K. (Karl)., Neylon, C., Brookes-Kenworthy, C., Hosking, R., Montgomery, L., Wilson, K., &amp; Ozaygen, A. (2020). Comparison of bibliographic data sources: Implications for the robustness of university rankings. <em>Quantitative Science Studies</em>, <em>1</em>(2), 445–478. <a href="https://doi.org/10.1162/qss_a_00031">https://doi.org/10.1162/qss_a_00031</a>
</div>
<div id="ref-Huang2020a" class="csl-entry" role="listitem">
Huang, C.-K. (Karl)., Neylon, C., Hosking, R., Montgomery, L., Wilson, K. S., Ozaygen, A., &amp; Brookes-Kenworthy, C. (2020). Evaluating the impact of open access policies on research institutions. <em>eLife</em>, <em>9</em>. <a href="https://doi.org/10.7554/elife.57067">https://doi.org/10.7554/elife.57067</a>
</div>
<div id="ref-Rousseau2018" class="csl-entry" role="listitem">
Rousseau, R., Egghe, L., &amp; Guns, R. (2018). Research evaluation. In <em>Becoming metric-wise</em> (pp. 247–292). Elsevier. <a href="https://doi.org/10.1016/b978-0-08-102474-4.00008-x">https://doi.org/10.1016/b978-0-08-102474-4.00008-x</a>
</div>
<div id="ref-Fournier2017" class="csl-entry" role="listitem">
Fournier, J. (2017). 1c. Open-access-policies und ihre gestaltung durch forschungsförderer. In <em>Praxishandbuch open access</em> (pp. 21–27). De Gruyter. <a href="https://doi.org/10.1515/9783110494068-003">https://doi.org/10.1515/9783110494068-003</a>
</div>
<div id="ref-Moed2016" class="csl-entry" role="listitem">
Moed, H. F. (2016). A critical comparative analysis of five world university rankings. <em>Scientometrics</em>, <em>110</em>(2), 967–990. <a href="https://doi.org/10.1007/s11192-016-2212-y">https://doi.org/10.1007/s11192-016-2212-y</a>
</div>
<div id="ref-Piro2016" class="csl-entry" role="listitem">
Piro, F. N., &amp; Sivertsen, G. (2016). How can differences in international university rankings be explained? <em>Scientometrics</em>, <em>109</em>(3), 2263–2278. <a href="https://doi.org/10.1007/s11192-016-2056-5">https://doi.org/10.1007/s11192-016-2056-5</a>
</div>
<div id="ref-Suber2012" class="csl-entry" role="listitem">
Suber, P. (2012). <em>Open access</em>. The MIT Press. <a href="https://doi.org/10.7551/mitpress/9286.001.0001">https://doi.org/10.7551/mitpress/9286.001.0001</a>
</div>
<div id="ref-Waltman2012" class="csl-entry" role="listitem">
Waltman, L., Calero‐Medina, C., Kosten, J., Noyons, E. C. M., Tijssen, R. J. W., Eck, N. J. van, Leeuwen, T. N. van, Raan, A. F. J. van, Visser, M. S., &amp; Wouters, P. (2012). The leiden ranking 2011/2012: Data collection, indicators, and interpretation. <em>Journal of the American Society for Information Science and Technology</em>, <em>63</em>(12), 2419–2432. <a href="https://doi.org/10.1002/asi.22708">https://doi.org/10.1002/asi.22708</a>
</div>
<div id="ref-vanRaan2005" class="csl-entry" role="listitem">
van Raan, A. F. J. (2005). Fatal attraction: Conceptual and methodological problems in the ranking of universities by bibliometric methods. <em>Scientometrics</em>, <em>62</em>(1), 133–143. <a href="https://doi.org/10.1007/s11192-005-0008-6">https://doi.org/10.1007/s11192-005-0008-6</a>
</div>
<div id="ref-LR_method" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-a). <em><span>CWTS Leiden Ranking 2024: Methodology</span></em>. Retrieved June 11, 2025, from <a href="https://traditional.leidenranking.com/Content/CWTS%20Leiden%20Ranking%202024.pdf">https://traditional.leidenranking.com/Content/CWTS%20Leiden%20Ranking%202024.pdf</a>
</div>
<div id="ref-LROE_method" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-b). <em><span>CWTS Leiden Ranking Open Edition 2024: Methodology</span></em>. Retrieved June 11, 2025, from <a href="https://open.leidenranking.com/Content/CWTS%20Leiden%20Ranking%20Open%20Edition%202024.pdf">https://open.leidenranking.com/Content/CWTS%20Leiden%20Ranking%20Open%20Edition%202024.pdf</a>
</div>
<div id="ref-LR_general" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-c). <em><span class="nocase">Information about the CWTS Leiden Ranking</span></em>. Retrieved June 11, 2025, from <a href="https://traditional.leidenranking.com/information/general">https://traditional.leidenranking.com/information/general</a>
</div>
<div id="ref-LROE_resources" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-d). <em><span>Resources</span></em>. Retrieved November 14, 2025, from <a href="https://open.leidenranking.com/resources">https://open.leidenranking.com/resources</a>
</div>
<div id="ref-LR_updates" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-e). <em><span class="nocase">Updates and corrections</span></em>. Retrieved November 14, 2025, from <a href="https://traditional.leidenranking.com/information/updates">https://traditional.leidenranking.com/information/updates</a>
</div>
<div id="ref-LROE_updates" class="csl-entry" role="listitem">
Centre for Science and Technology Studies, Leiden University. (n.d.-f). <em><span class="nocase">Updates and corrections</span></em>. Retrieved November 14, 2025, from <a href="https://open.leidenranking.com/information/updates">https://open.leidenranking.com/information/updates</a>
</div>
<div id="ref-COKI_contact" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (n.d.-a). <em>Contact</em>. <a href="https://open.coki.ac/contact/">https://open.coki.ac/contact/</a>
</div>
<div id="ref-COKI_data" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (n.d.-b). <em>Data</em>. <a href="https://open.coki.ac/data/">https://open.coki.ac/data/</a>
</div>
<div id="ref-COKI_how" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (n.d.-c). <em>How it works</em>. <a href="https://open.coki.ac/how/">https://open.coki.ac/how/</a>
</div>
<div id="ref-COKI_dashboard" class="csl-entry" role="listitem">
Curtin Open Knowledge Initiative. (n.d.-d). <em>Open access dashboard</em>. <a href="https://open.coki.ac/">https://open.coki.ac/</a>
</div>
<div id="ref-QS_scores" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-a). <em>Displayed scores and ranks</em>. <a href="https://support.qs.com/hc/en-gb/articles/360019155519-Displayed-Scores-and-Ranks">https://support.qs.com/hc/en-gb/articles/360019155519-Displayed-Scores-and-Ranks</a>
</div>
<div id="ref-QS_governance" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-b). <em>Good governance</em>. <a href="https://support.qs.com/hc/en-gb/articles/8575855263644-Good-Governance">https://support.qs.com/hc/en-gb/articles/8575855263644-Good-Governance</a>
</div>
<div id="ref-QS_optout" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-c). <em><span class="nocase">Opt-out policy</span></em>. <a href="https://support.qs.com/hc/en-gb/articles/360019107060-Opt-out-policy">https://support.qs.com/hc/en-gb/articles/360019107060-Opt-out-policy</a>
</div>
<div id="ref-QS_papers" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-d). <em>Paper counts - breakdown</em>. <a href="https://support.qs.com/hc/en-gb/articles/360019107160-Paper-Counts-breakdown">https://support.qs.com/hc/en-gb/articles/360019107160-Paper-Counts-breakdown</a>
</div>
<div id="ref-QS_paperdef" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-e). <em>Paper definitions</em>. <a href="https://support.qs.com/hc/en-gb/articles/360019156319-Paper-Definitions">https://support.qs.com/hc/en-gb/articles/360019156319-Paper-Definitions</a>
</div>
<div id="ref-QS_scopus" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-f). <em><span>QS Scopus User Guide</span></em>. <a href="https://support.qs.com/hc/en-gb/articles/4411497775506-QS-Scopus-User-Guide">https://support.qs.com/hc/en-gb/articles/4411497775506-QS-Scopus-User-Guide</a>
</div>
<div id="ref-QS_sustain" class="csl-entry" role="listitem">
Quacquarelli Symonds. (n.d.-g). <em><span>QS World University Rankings: Sustainability</span></em>. <a href="https://support.qs.com/hc/en-gb/articles/8551503200668-QS-World-University-Rankings-Sustainability">https://support.qs.com/hc/en-gb/articles/8551503200668-QS-World-University-Rankings-Sustainability</a>
</div>
<div id="ref-SIR_method" class="csl-entry" role="listitem">
SCImago Research Group. (n.d.-a). <em>Ranking methodology</em>. <a href="https://www.scimagoir.com/methodology.php">https://www.scimagoir.com/methodology.php</a>
</div>
<div id="ref-SIR" class="csl-entry" role="listitem">
SCImago Research Group. (n.d.-b). <em><span>SCImago Institutions Ranking</span></em>. <a href="https://www.scimagoir.com/rankings.php">https://www.scimagoir.com/rankings.php</a>
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Informationen zur jeweiligen Datenverfügbarkeit inklusive eines Links zum Download der verwendeten Version der Daten – sofern vorhanden – sind für alle Rankings in dem jeweiligen Kasten mit den Ranking Details erfasst.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><span class="citation" data-cites="QS_date">Quacquarelli Symonds (<a href="#ref-QS_date" role="doc-biblioref">2024</a>)</span> berichtet, dass 1.744 Instiutionen in der Version 2025 geranked wurden. Die Daten zeigen hier jedoch eine Abweichung um eine Einrichtung.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Die bereitgestellten Daten zeigen eine Abweichung um eine Institution zu der von SCImago auf der Rankingwebsite berichteten Anzahl an gerankten Institutionen <span class="citation" data-cites="SIR">(<a href="#ref-SIR" role="doc-biblioref">SCImago Research Group, n.d.-b</a>)</span>. Die bereitgestellte csv-Datei enthält zwar 9.756 Zeilen, jedoch handelt es sich bei der ersten Zeile lediglich um eine Kopfzeile.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Beispielsweise wird im SCImago Institutions Ranking das <a href="https://www.scimagoir.com/institution.php?idp=21592">Deutsche Krebsforschungszentrum</a> in der Landessprache angesetzt, während in ROR die englische Namensvariante <a href="https://ror.org/04cdgtt98">German Cancer Research Center</a> als Hauptansetzung verwendet wird.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Durch Klick auf die Abbildungen werden diese vergrößert dargestellt.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Formal definiert <span class="citation" data-cites="Moed2016">Moed (<a href="#ref-Moed2016" role="doc-biblioref">2016</a>)</span> die <em>preference</em> mit: <span class="math inline">\(P= \dfrac{\bigg(\dfrac{n[i, j]}{\sum_i n[i, j]}\bigg)}{\bigg(\dfrac{\sum_jn[i, j]}{\sum_i\sum_jn[i, j]}\bigg)}\)</span>, wobei <span class="math inline">\(n[i, j]\)</span> die Anzahl an Institutionen aus Land <span class="math inline">\(i\)</span> im Rankingsystem <span class="math inline">\(j\)</span>, <span class="math inline">\(\sum_in[i, j]\)</span> die Summe aller <span class="math inline">\(n[i, j]\)</span> über alle <span class="math inline">\(i\)</span> (Länder), <span class="math inline">\(\sum_jn[i, j]\)</span> die Summe aller <span class="math inline">\(n[i, j]\)</span> über alle <span class="math inline">\(j\)</span> (Rankingsysteme), und <span class="math inline">\(\sum_i\sum_jn[i, j]\)</span> die Summe aller <span class="math inline">\(n[i, j]\)</span> über alle <span class="math inline">\(i\)</span> (Länder) und alle <span class="math inline">\(j\)</span> (Rankingsysteme) angibt.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section>
</div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oa-datenpraxis\.de\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
       
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
<li class="nav-item">
    <a class="nav-link" href="./impressum.html">
<p><a href="https://www.hu-berlin.de/de/hu/impressum">Impressum</a></p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="./datenschutz.html">
<p>Datenschutz</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://creativecommons.org/licenses/by/4.0/deed.de">
<p><iconify-icon role="img" inline="" icon="bxl:creative-commons" style="font-size: 1.5em;" aria-label="Icon creative-commons from bxl Iconify.design set." title="Icon creative-commons from bxl Iconify.design set."></iconify-icon><iconify-icon role="img" inline="" icon="humbleicons:creative-commons-by" style="font-size: 1.5em;" aria-label="Icon creative-commons-by from humbleicons Iconify.design set." title="Icon creative-commons-by from humbleicons Iconify.design set."></iconify-icon></p>
</a>
  </li>  
    <li class="nav-item">
 Sofern nicht anders angegeben, ist der Inhalt dieser Website unter einer Creative Commons Namensnennung 4.0 International Lizenz lizenziert.
  </li>  
</ul>
</div>
    <div class="nav-footer-right">
       
    </div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>
</body>
</html>
