---
title: Presentation <br/> Erfassung von Publikationskosten an wissenschaftlichen Einrichtungen in Deutschland
subtitle: 9th Library Congress 2025, 24 - 27 June 2025, Bremen
---

## Dates

**Date:** 27.06.2025

**Time:** 11:00--11:30 AM CEST

**Room:** Focke-Wulf Saal

[Programme on the organiser's website](https://2025.bid-kongress.de/programm/)

## Description

Data on publications and costs are required for the strategic and operational design of the open access transformation. The presentation presents the results of a survey conducted as part of the OA Datenpraxis project funded by the German Research Foundation (DFG) in 2024. The survey investigated how data on publication costs are currently recorded at scientific institutions in Germany. Representatives of universities, universities of applied sciences, institutes of non-university research organisations (Fraunhofer-Gesellschaft, Helmholtz Association, Leibniz Association and Max Planck Society) and federal departmental research institutions were addressed. Of the 583 people invited, 258 (44.3 %) completed the questionnaire. The survey is the first comprehensive survey to record publication costs in Germany.

The results show that the majority of respondents at least partially record publication costs. However, the processes are not regulated in a binding manner everywhere. 33.1% of respondents stated that publication costs are recorded decentrally in several departments in several systems at their institution. On average, 2.4 areas of an institution are involved in the processes. 66.3% of respondents rated the cooperation between the institutions involved as ‘very good’ or ‘fairly good’. The reliability of the recording process varies depending on the source of funds, with the use of funds managed by a central service organisation being rated as the most reliable. 80.2% rated the contribution of recording publication costs to shaping the open access transformation as ‘very important’ or ‘fairly important’. However, the data collected is not the basis for strategic decisions at all institutions. The implementation of an information budget by 2025 is considered unlikely at most institutions.