---
title: Vortrag <br/> Erfassung von Publikationskosten an wissenschaftlichen Einrichtungen in Deutschland
subtitle: 9. Bibliothekskongress 2025, 24. – 27. Juni 2025, Bremen
---

## Daten

**Datum:** 27.06.2025

**Uhrzeit:** 11:00--11:30 Uhr

**Saal:** Focke-Wulf Saal

[Programm auf der Seite des Veranstalters](https://2025.bid-kongress.de/programm/)

## Beschreibung

Zur strategischen und operativen Gestaltung der Open-Access-Transformation werden Daten zu Publikationen und Kosten benötigt. Der Vortrag stellt Ergebnisse einer Umfrage vor, die im Rahmen des von der Deutschen Forschungsgemeinschaft (DFG) geförderten Projekts OA Datenpraxis im Jahr 2024 durchgeführt wurde. Die Umfrage erhob, wie Daten zu Publikationskosten aktuell an wissenschaftlichen Einrichtungen in Deutschland erfasst werden. Adressiert wurden Vertreter*innen von Universitäten, Fachhochschulen, Instituten außeruniversitärer Forschungseinrichtungen (Fraunhofer-Gesellschaft, Helmholtz-Gemeinschaft, Leibniz-Gesellschaft und Max-Planck-Gesellschaft) sowie Ressortforschungseinrichtungen des Bundes. Von den 583 eingeladenen Personen füllten 258 (44,3 %) den Fragebogen aus. Die Umfrage ist die erste umfassende Erhebung zur Erfassung von Publikationskosten in Deutschland.

Die Ergebnisse zeigen, dass die Mehrzahl der Befragten Publikationskosten zumindest teilweise erfassen. Die Abläufe sind jedoch nicht überall verbindlich geregelt. 33,1 % der Befragten gaben an, dass Publikationskosten an ihrer Einrichtung dezentral an mehreren Abteilungen in mehreren Systemen erfasst werden. Durchschnittlich sind 2,4 Bereiche einer Einrichtung in die Prozesse involviert. 66,3 % der Befragten bewerteten die Zusammenarbeit der beteiligten Einrichtungen als “sehr gut” oder “eher gut”. schätzen die Erfassung je nach Mittelherkunft unterschiedlich zuverlässig ein, am zuverlässigsten wird der Einsatz von Mitteln bewertet, die von einer zentralen Serviceeinrichtung verwaltet werden. 80,2 % bewerteten den Beitrag der Erfassung von Publikationskosten für die Gestaltung der Open-Access-Transformation als "sehr wichtig" oder "eher wichtig". Die erfassten Daten sind jedoch nicht an allen Einrichtungen Grundlage strategischer Entscheidungen. Die Umsetzung eines Informationsbudgets bis 2025 wird an den meisten Einrichtungen als unwahrscheinlich angesehen.