---
title: Poster <br/> Recording Publication of Costs at Research Performing Organizations in Germany
subtitle: openCost Conference, 17 - 19 March 2026, Hamburg
---

## Dates

**Date:** 18.03.2026

**Time:** 12:30 PM to 14:00 PM CEST

[Programme on the organiser's website](https://indico.desy.de/event/50077/timetable/#20260317)

## Description

The poster presents the results of a survey conducted in 2024 as part of the project OA Datenpraxis, funded by the German Research Foundation (DFG). The survey examined how data on publication costs are currently recorded at research performing institutions in Germany. 583 representatives of universities, universities of applied sciences, institutes of non-university research organizations (Fraunhofer Society, Helmholtz Association, Leibniz Association, and Max Planck Society), and federal departmental research institutions were invited to participate in the survey. 258 (44.3%) completed the questionnaire. The survey is the first comprehensive survey on recording publication costs in Germany.
