---
title: OA Datenpraxis Webinar <br/> How to - Das Publikationsaufkommen Ihrer Einrichtung mit einer offenen Datenquelle erfassen
---

## Daten

**Datum:** 01.07.2026

**Uhrzeit:** 10:00--12:00 Uhr

**Ort:** Online über Zoom

**Registrierung unter:** [https://hu-berlin.zoom-x.de/meeting/register/GPbfrtfySsWJUyCbWxt2qw](https://hu-berlin.zoom-x.de/meeting/register/GPbfrtfySsWJUyCbWxt2qw) (Beschränkt auf 30 Teilnehmende)

## Beschreibung

Sie fragen sich, was, wie viel und wo Forschende Ihrer Einrichtung publizieren? In diesem Webinar möchten wir Ihnen zeigen, wie Sie das Publikationsaufkommen an Ihrer Einrichtung erfassen können. Dazu nutzen wir OpenAlex, eine offene Quelle für Forschungsinformationen.
Wir demonstrieren, wie Sie mit Hilfe eines R-Notebooks Daten Ihrer Einrichtung anhand der ROR-ID über die OpenAlex API abfragen können. Anschließend werden wir den abgefragten Datensatz gemeinsam explorieren und für die Auswertung vorbereiten. Dabei gehen wir exemplarisch auf das Qualitätsproblem der variierenden Ansetzung von Verlagsnamen ein und zeigen, wie es adressiert werden kann. Abschließend zeigen wir, wie sich anhand der bereinigten Daten Metriken für das Monitoring des Publikationsverhaltens an Ihrer Einrichtung berechnen lassen.

Diese Veranstaltung richtet sich an Mitarbeitende in wissenschaftlichen Einrichtungen, die an Monitoring und Berichterstattung im Kontext der Open-Access-Transformation interessiert sind.

In der Veranstaltung führen wir Sie Schritt für Schritt durch den verwendeten Code. Darum sind Vorkenntnisse oder die Installation von Software nicht erforderlich.
Bitte erstellen Sie vorab einen API-key für OpenAlex [1] und einen kostenlosen Posit-Cloud Account [2].
Gerne können Sie auch vorab Wünsche zu Metriken an uns richten, die wir dann in der Veranstaltung berechnen.

[1]: [https://developers.openalex.org/api-reference/authentication](https://developers.openalex.org/api-reference/authentication)
[2]: [https://posit.cloud/plans/free](https://posit.cloud/plans/free)
