---
title: OA Datenpraxis Webinar <br/> Erfassung von Publikationskosten an wissenschaftlichen Einrichtungen in Deutschland
---

## Dates

**Date:** 28.03.2025

**Time:** 10:00--11:00 AM CET

**Location:** Online via Zoom

**Registrtration:**  [https://hu-berlin.zoom-x.de/webinar/register/WN_pKTlDzjsQwC7QspLxwMHCg](https://hu-berlin.zoom-x.de/webinar/register/WN_pKTlDzjsQwC7QspLxwMHCg)

## Description

The webinar will present the results of a survey conducted as part of the OA Datenpraxis project funded by the German Research Foundation (DFG) in 2024.

The survey, which was developed in dialogue with representatives of the DEAL subgroup ‘Communication’, investigated how data on publication costs are currently collected at scientific institutions in Germany. Representatives of universities, universities of applied sciences, institutes of non-university research organisations and federal departmental research institutions were addressed. Of the 583 people invited, 258 (44.3 %) took part in the survey. The survey is the first comprehensive survey on publication costs in Germany.

This webinar is aimed at professionals who are interested in open access monitoring, in particular the recording of open access publication costs.

### Programme

After a presentation of the survey results, participants will have the opportunity to ask questions about the survey. This will be followed by a panel discussion with members of the DEAL group on some key aspects of recording publication costs.

- Welcome by Heinz Pampel (5 minutes)
- Presentation of the survey results by Dorothea Strecker (30 minutes)
- Q&A on the survey (10 minutes)
- Panel discussion with members of the DEAL Group (15 minutes)