---
title: OA Datenpraxis Webinar <br/> Tools zum Monitoring von Publikationskosten in der Open-Access-Transformation
---

## Daten

**Datum:** 11.06.2026

**Uhrzeit:** 10:00--13:00 Uhr

**Ort:** Online über Zoom

**Registrierung unter:** [https://uni-goettingen.zoom-x.de/meeting/register/cGbvA7rLT8Wkohq01WEpAg](https://uni-goettingen.zoom-x.de/meeting/register/cGbvA7rLT8Wkohq01WEpAg)

## Beschreibung

Im Rahmen dieses Workshops möchten wir Tools und Workflows zum Monitoring von Publikationskosten im Kontext der Open-Access-Transformation vorstellen und diskutieren. In kurzen Praxisbeiträgen berichten Referent:innen aus wissenschaftlichen Einrichtungen über ihre Erfahrungen mit unterschiedlichen Systemen und Anwendungen. 

Die Veranstaltung richtet sich an Mitarbeitende wissenschaftlicher Einrichtungen, die mit Monitoring, Berichterstattung und dem Management von Publikationskosten im Kontext der Open-Access-Transformation betraut sind.

### Programm

In unserem Programm werden folgende Tools vorgestellt:

10:00-10:20 FOLIO - Praxisbericht: Martin Bauschmann
10:20-10:40 CODA - Praxisbericht: Linda Achilles
10:40-11:00 ALMA – Praxisbericht: Eike Spielberg
11:00-11:20 DSpace – Praxisbericht: Lara Babic
11:20-11:40 Pause
11:40-12:00 Output – Praxisbericht: Sascha Bosse
12:00-12:20 Eprints - Gernot Deinzer
12:20-12:40 MyCoRe - Alexander Wagner
12:40-13:00 Diskussion


Im Mittelpunkt stehen Fragen der Erfassung, Auswertung und Berichterstattung von Publikationskosten sowie die Einbindung dieser Daten in lokale Monitoring- und Reporting-Prozesse. In einer anschließenden Q&A-Session haben die Teilnehmenden Gelegenheit, sich über Erfahrungen, Herausforderungen und Lösungsansätze aus der Praxis auszutauschen.

