---
title: OA Datenpraxis Webinar <br/> edit-a-thon Materialsammlung für die Gestaltung des institutionellen Publikationskostenmonitorings
---

## Daten

**Datum:** 15.07.2026

**Uhrzeit:** 11:00--12:00 Uhr

**Ort:** Online über Zoom

**Registrierung unter:** [https://hu-berlin.zoom-x.de/meeting/register/59gtK8FQSYm8yu9J7lvwGg](https://hu-berlin.zoom-x.de/meeting/register/59gtK8FQSYm8yu9J7lvwGg)

## Beschreibung

Im Zuge der Open-Access-Transformation haben sich diverse Finanzierungswege für das wissenschaftliche Publizieren herausgebildet. Die zuverlässige Erfassung von Publikationskosten gewinnt damit an Relevanz, sie stellt wissenschaftliche Einrichtungen jedoch auch vor erhebliche Herausforderungen.

Darum haben die DFG-geförderten Projekte OA Datenpraxis und Transform2Open in einer gemeinsamen Initiative eine Sammlung textbasierten Materialien erstellt, die ie Praktiker:innen den Einstieg in das institutionelle Publikationskostenmonitoring erleichtern können.

In diesem edit-a-thon möchten wir gemeinsam mit der Open-Access-Community Vorschläge für die Überarbeitung und Ergänzung der Materialsammlung erarbeiten.

Die Veranstaltung richtet sich an Mitarbeitende wissenschaftlicher Einrichtungen, die mit Monitoring, Berichterstattung und dem Management von Publikationskosten im Kontext der Open-Access-Transformation betraut sind.
