---
title: OA Datenpraxis Webinar <br/> Erfassung von Publikationskosten an wissenschaftlichen Einrichtungen in Deutschland
---

## Daten

**Datum:** 28.03.2025

**Uhrzeit:** 10:00--11:00 Uhr

**Ort:** Online über Zoom

**Registrierung unter:**  [https://hu-berlin.zoom-x.de/webinar/register/WN_pKTlDzjsQwC7QspLxwMHCg](https://hu-berlin.zoom-x.de/webinar/register/WN_pKTlDzjsQwC7QspLxwMHCg)

## Beschreibung

In dem Webinar werden Ergebnisse einer Umfrage vorgestellt, die im Rahmen des von der Deutschen Forschungsgemeinschaft (DFG) geförderten Projekts OA Datenpraxis im Jahr 2024 durchgeführt wurde.

Die Umfrage, die im Dialog mit Vertreter:innen der DEAL-Untergruppe “Kommunikation” entwickelt wurde, erhob, wie Daten zu Publikationskosten aktuell an wissenschaftlichen Einrichtungen in Deutschland erfasst werden. Adressiert wurden Vertreter:innen von Universitäten, Fachhochschulen, Instituten außeruniversitärer Forschungseinrichtungen sowie Ressortforschungseinrichtungen des Bundes. Von 583 eingeladenen Personen beteiligten sich 258 (44,3  %) an der Umfrage. Die Umfrage ist die erste umfassende Erhebung zur Erfassung von Publikationskosten in Deutschland.

Dieses Webinar richtet sich an Professionals, die sich für Open-Access-Monitoring, insbesondere die Erfassung von Open-Access-Publikationskosten, interessieren.

### Programm

Nach einer Präsentation der Umfrageergebnisse haben Teilnehmende die Möglichkeit, Fragen zur Umfrage zu stellen. Anschließend werden einige zentrale Aspekte der Erfassung von Publikationskosten in einer Paneldiskussion mit Mitgliedern der DEAL-Gruppe erörtert.

- Begrüßung durch Heinz Pampel (5 Minuten)
- Vorstellung der Umfrageergebnisse durch Dorothea Strecker (30 Minuten)
- Q&A zur Umfrage (10 Minuten)
- Paneldiskussion mit Mitgliedern der DEAL-Gruppe (15 Minuten)