---
title: OA Datenpraxis Webinar <br/> Open-Access-Reporting in der Praxis
---

## Daten

**Datum:** 27.04.2024

**Uhrzeit:** 12:30--14:00 Uhr

**Ort:** Online über Zoom

**Registrierung unter:** [https://hu-berlin.zoom.us/meeting/register/lzRSvMZGToupf-vp9L8Kdg#/registration](https://hu-berlin.zoom.us/meeting/register/lzRSvMZGToupf-vp9L8Kdg#/registration)

## Beschreibung

In diesem Webinar möchten wir die Realität der Berichterstattung im Kontext der Open-Access-Transformation beleuchten. In kurzen Vorträgen berichten Juliane Mörsel von der Bibliothek des Karlsruher Instituts für Technologie und Dirk Pieper von der Universitätsbibliothek Bielefeld von der Reporting-Praxis an ihren Einrichtungen. In der anschließenden Q&A-Session haben Teilnehmende die Gelegenheit, sich zu Erfahrungen und Herausforderungen, die ihnen in der Praxis begegnen, auszutauschen.

Diese Veranstaltung richtet sich an Mitarbeitende in wissenschaftlichen Einrichtungen, die mit Monitoring und Berichterstattung im Kontext der Open-Access-Transformation betraut sind.

### Programm

-   Begrüßung (5 Minuten)
-   Vortrag Juliane Mörsel (20 Minuten + 5 Minuten Fragen)
-   Vortrag Dirk Pieper (20 Minuten + 5 Minuten Fragen)
-   Q&A-Session (35 Minuten)
